Form api refactoring
primait/pyxis pull request #103
Opened 2022-03-10 11:45 UTC by alessiosantangelo

2022-03-10 13:57 UTC, lauratrapani commented on packages/pyxis-elm/src/Commons/Properties/Gap.elm
> +    Medium
Qua dovrebbe essere `Small`

2022-03-10 13:57 UTC, lauratrapani commented on packages/pyxis-elm/src/Components/Form/FieldSet.elm
> +    { header : List (Grid.Col msg)
Qui lascerei la possibilità di inserire le `Row` dato che potrebbe esserci una row large anche nell'header, o comunque potrebbero esserci più row. Stessa cosa nel footer

2022-03-10 13:57 UTC, lauratrapani commented on packages/pyxis-elm/src/Components/Form/FieldSet.elm
> +withHeader a (FieldSet configuration) =
Mi è sembrato di capire anche parlando con gli altri che si preferisca mettere nomi più parlanti per gli argomenti

2022-03-10 18:25 UTC, emanuelemacri requested changes
Alcune sciochezze e qualche domanda

2022-03-10 18:25 UTC, emanuelemacri commented on packages/pyxis-elm/src/Components/Form/Grid/Row.elm
> +    Size Size.medium
Anche la `mediumSize` idealmente non esiste sulla row, abbiamo solo:
- small
- large
- fullWidth (che è quella di default)

2022-03-10 18:25 UTC, emanuelemacri commented on packages/pyxis-elm/src/Components/Form/Grid/Row.elm
> +    Size Size.fullWidth
Questa cosa l'avevo fatta io ma non mi fa impazzire, dici che va bene avere una `Size.fullWidth`?

2022-03-10 18:25 UTC, emanuelemacri commented on packages/pyxis-elm/src/Examples/Form/Views/BaseInformation.elm
> +                        []
cazzatina, ma almeno abbiamo un test più "reale"
```suggestion
                    [ Grid.simpleCol
```

2022-03-10 18:25 UTC, emanuelemacri commented on packages/pyxis-elm/src/Examples/Form/Views/BaseInformation.elm
> +                        []
idem qui e in altre parti dell'esempio
```suggestion
                    [ Grid.simpleCol
```

2022-03-10 18:25 UTC, emanuelemacri commented on packages/pyxis-elm/src/Examples/Form/Views/InsuranceType.elm
> +                            |> RadioCardGroup.withOptions
Non è un problema di questa PR, ma è stato mergiato un bug nei `RadioCardGroup`, vengono visualizzati tutti come checkbox.

Si dovrebbe risolvere facilmente dal file `RadioCardGroup.elm`, nella funzione `render` va sostituito:
`CardGroup.renderCheckbox` con `CardGroup.renderRadio`

2022-03-10 18:25 UTC, emanuelemacri commented on packages/pyxis-elm/src/Examples/Form/example.css
>  }
Questo era giusto come prima 😁

2022-03-10 18:25 UTC, emanuelemacri commented on packages/pyxis-elm/src/Stories/Book.elm
> +            , ElmBook.ThemeOptions.navAccentHighlight "#f3f4f4"
GRAZIE ❤️, lo volevo fare pure io, ma ovviamente l'ho lasciato indietro. Stava diventando un casino da leggere

2022-03-11 08:07 UTC, ascandone commented on packages/pyxis-elm/src/Components/Form/Grid/Row.elm
> +    Size Size.fullWidth
Secondo me appena c'è tempo dovremmo mettere le size per ogni component
Attualmente è tutto un mischione, ogni component prende tutte le size anche se alcune non hanno effetto, e non è nemmeno documentato da nessuna parte quali sono quelle accettate

2022-03-11 08:10 UTC, ascandone commented on packages/pyxis-elm/src/Stories/Chapters/Form.elm
> +    |> Grid.render
A che serve il `|> Grid.render` sotto? Come mai la funzione non restituisce direttamente html?

2022-03-11 08:24 UTC, ascandone requested changes

2022-03-11 08:24 UTC, ascandone commented on packages/pyxis-elm/src/Components/Form/Grid.elm
> +    = Gap Gap
Questa rappresentazione diventa abbastanza scomoda man mano che aumentano le opzioni
What about qualcosa del genere?
```elm
-- Privato
type alias Config =
  { gap : Gap
   , ...
  }

-- Private
config : Config
config =
  { gap = Gap.medium
  }

-- Esposto (opaco)
type Option = Option (Config -> Config)

withGap : Gap -> Option
withGap gap = Option <| \c -> { c | gap = gap }

-- nella view
render =
  let config =  List.foldl (\(Option f) conf -> f conf) config
  in
  -- qui ho il solito record "config" , anzichè fare "List.find"
  Html.div ..
```

2022-03-11 08:37 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Form/Grid/Row.elm
> +    Size Size.medium
Direi che a questo punto elimino `fullWidth` che non ha senso di essere una dimensione e la sostituisco con la size `Medium`. 
Di fatti se i possibili valori modificabili per una `rowSize` sono `large e small` ha senso che il valore di default sia `medium` anche se questo non ha una classe CSS associata.

2022-03-11 08:57 UTC, emanuelemacri commented on packages/pyxis-elm/src/Components/Form/Grid/Row.elm
> +    Size Size.medium
Però è strano che se scrivo `medium` mi esca una row più "grande" di `large`, forse possiamo mettere proprio `default`?

2022-03-11 09:42 UTC, ascandone commented on packages/pyxis-elm/src/Components/Form/Grid.elm
> +    = Option (Configuration msg -> Configuration msg)
Ok, comunque giusto per essere puntiglioso (non mi uccidere) io `Configuration` lo chiamerei `Config` per essere consistente al resto del naming https://github.com/primait/pyxis/wiki/Elm-API-guidelines
Forse ancora meglio sarebbe `ConfigData`

Mentre Option lo rinominerei Attribute per non fare confusione con gli altri Option (ma questo è un po' soggettivo)

2022-03-11 09:43 UTC, ascandone approved these changes

2022-03-11 10:29 UTC, emanuelemacri requested changes

2022-03-11 10:29 UTC, emanuelemacri commented on packages/pyxis-elm/src/Components/Form/FieldSet.elm
>          ]
Dovrebbe essere così (mi son spiegato male prima probabilmente):
- tra `header`, `content` e `footer` ci deve essere un `largeGap`.
- internamente a `content` c'è una griglia con `smallGap` 

Te la scrivo male, poi magari si può splittare

```
{-| Renders the FieldSet.
-}
render : FieldSet msg -> Html msg
render (FieldSet configuration) =
    Html.fieldset
        [ Attributes.class "form-fieldset" ]
        [ configuration.header
            ++ [ Grid.simpleOneColRow
                    [ Grid.render [] configuration.content ]
               ]
            ++ configuration.footer
            |> Grid.render [ Grid.largeGap ]
        ]
```

2022-03-11 10:51 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Form/Grid.elm
> +    = Option (Configuration msg -> Configuration msg)
Ok per `ConfigData` mentre sono meno convinto di chiamare le `Option` `Attribute` in quanto mi da l'idea che si confondano maggiormente con gli `Html.Attributes`

2022-03-11 11:23 UTC, emanuelemacri approved these changes

2022-03-11 13:29 UTC, merged