[DS-60]: [Pyxis React] Add Input component
primait/pyxis pull request #104
Opened 2022-03-11 17:11 UTC by emanuelemacri

First input implementation

https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/DS-60

2022-03-14 09:55 UTC, alessiosantangelo requested changes
In generale farei le seguenti modifiche: 
- `props` dei componenti in ordine alfabetico
- `props` dei types in ordine alfabetico 
- quando un type viene usato solo localmente ed è uno union type definirei inline i suoi possibili valori

2022-03-14 09:55 UTC, alessiosantangelo commented on packages/pyxis-react/package.json
> +    "generate-component": "generate-react component",
Seguendo la sintassi che usiamo per i commands dovrebbe essere `component:generate`.

2022-03-14 09:55 UTC, alessiosantangelo commented on packages/pyxis-react/src/App.tsx
> +import Form from './components/Form';
```suggestion
import { Item, Label, Input } from './components/Form';
```

2022-03-14 09:55 UTC, alessiosantangelo commented on packages/pyxis-react/src/components/Form/Form.tsx
> +export default Form;
```suggestion
export default {Label, Input, Item };
```

2022-03-14 09:55 UTC, alessiosantangelo commented on packages/pyxis-react/src/components/Form/Input/Addon/Addon.test.tsx
> +    render(<Addon addon="stronzoni" id="stronzi" />);
Diamogli un contenuto più polite 😂

2022-03-14 09:55 UTC, alessiosantangelo commented on packages/pyxis-react/src/components/Form/Input/Addon/Addon.tsx
> +export const getAddonStringType = (addon:AddonType):AddonStringType => {
Se i miei occhi non mentono questo metodo non lo stiamo usando

2022-03-14 09:55 UTC, alessiosantangelo commented on packages/pyxis-react/src/components/Form/Input/Addon/Addon.tsx
> +export type AddonStringType = 'icon' | 'text';
E quindi anche questo si può omettere.

2022-03-14 09:55 UTC, alessiosantangelo commented on packages/pyxis-react/src/components/Form/Input/Input.tsx
> +const getClasses = (
Per semplificare qui potremmo ricevere tutte le `props` invece che questa lunga lista di argomenti.

2022-03-14 09:55 UTC, alessiosantangelo commented on packages/pyxis-react/src/components/Form/Input/Input.tsx
> +  size?: InputSize;
Renderei questo argomento obbligatorio.

2022-03-14 09:55 UTC, alessiosantangelo commented on packages/pyxis-react/src/components/Form/Item/Item.test.tsx
> +        <Input />
Anche qui forse si può aggiungere qualche test extra.

2022-03-14 09:55 UTC, alessiosantangelo commented on packages/pyxis-react/src/components/Form/Item/Item.tsx
> +  hintId: `${id}-hint`,
```suggestion
  label: `${id}-label`,
  field: `${id}-field`,
  error: `${id}-error`,
  hint: `${id}-hint`,
```

2022-03-14 09:55 UTC, alessiosantangelo commented on packages/pyxis-react/src/components/Form/Item/Item.tsx
> +  id,
Sarebbe molto utile inserire una regola di formattazione per la quale le props e le chiavi che definiscono un `type` siano in ordine alfabetico così da ridurre al minimo i changes sulle PR

2022-03-14 09:55 UTC, alessiosantangelo commented on packages/pyxis-react/src/components/Form/Item/Item.tsx
> +);
Non mi è chiarissimo perchè viene fatto tutto ciò...

2022-03-14 09:55 UTC, alessiosantangelo commented on packages/pyxis-react/src/components/Form/Item/Item.tsx
> +  id: string;
Il `FormItem` deve avere un id?

2022-03-14 09:55 UTC, alessiosantangelo commented on packages/pyxis-react/src/components/Form/Label/Label.tsx
> +const Label: FC<LabelProps> = (props) => {
Di solito le props le destrutturiamo direttamente qui.

2022-03-14 09:55 UTC, alessiosantangelo commented on packages/pyxis-react/src/components/Form/Label/Label.tsx
> +Label.displayName = 'PyxisLabel';
??

2022-03-14 09:55 UTC, alessiosantangelo commented on packages/pyxis-react/src/components/Form/Input/Addon/Addon.tsx
> +  addon: AddonType;
Possiamo risparmiare la definizione di alcuni tipi facendo come segue: 
```suggestion
  addon: FC<IconProps> | string;
```

2022-03-14 09:57 UTC, emanuelemacri commented on packages/pyxis-react/src/App.tsx
> +import { IconCar } from './components/Icon/Icons';
App è solo un esempio di sviluppo, priama di mergiare levo tutto

2022-03-14 10:09 UTC, emanuelemacri commented on packages/pyxis-react/src/components/Form/Input/Addon/Addon.tsx
> +export const getAddonStringType = (addon:AddonType):AddonStringType => {
Lo usiamo, ma dentro Input

2022-03-14 10:10 UTC, emanuelemacri commented on packages/pyxis-react/src/components/Form/Item/Item.tsx
> +  hintId: `${id}-hint`,
Abbiamo già sia `label` che `field`, quindi lascerei così

2022-03-15 08:34 UTC, ascandone commented on packages/pyxis-react/src/components/Form/Form.tsx
> +const Form: FC<FormProps> & FormChildren = ({ className = '', children }) => (
Questo attualmente è praticamente inutilizzabile perché mancano i callback ma immagino sia voluto, per questa versione

2022-03-15 08:34 UTC, ascandone approved these changes

2022-03-15 10:27 UTC, alessiosantangelo approved these changes

2022-03-15 10:28 UTC, Gsciarra approved these changes

2022-03-15 10:34 UTC, merged