[DS-71]: [Pyxis Elm] Component fixes
primait/pyxis pull request #106
Opened 2022-03-15 16:27 UTC by Gsciarra

https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/DS-71

2022-03-15 17:08 UTC, ascandone commented on packages/pyxis-elm/src/Components/Field/CheckboxGroup.elm
> +option : { label : Html (Msg value), value : value } -> Option value
Non fa niente, basta fare `Html.map never`, dove never è una funzione `Never -> a` nella libreria standard

2022-03-16 08:59 UTC, emanuelemacri requested changes
Ti scrivo giusto una cosa qui:
- Non so se devi ancora rebasare da master ma c'è un bug che era già stato risolto sui RadioCardGroup che vengono renderizzati sempre con una checkbox,questa era la vecchia soluzione,mo non ho visto bene il codice:

Si dovrebbe risolvere facilmente dal file `RadioCardGroup.elm`, nella funzione `render` va sostituito:
`CardGroup.renderCheckbox` con `CardGroup.renderRadio`

2022-03-16 09:15 UTC, Gsciarra commented
> 

Dal diff si vede che su master non c'è, comunque lo metto io.

2022-03-16 10:44 UTC, lauratrapani reviewed
Magari negli esempi o nelle storie mettiamo anche un esempio con additional content?

2022-03-16 10:44 UTC, lauratrapani commented on packages/pyxis-elm/src/Examples/Form/Views/BaseInformation.elm
> +                            )
Magari mettiamo l'esempio con il link? O qua o nelle stories

2022-03-16 16:11 UTC, lauratrapani commented
Se non sbaglio manca anche l'API degli additionalContent nei vari componenti.

2022-03-17 09:52 UTC, alessiosantangelo requested changes

2022-03-17 09:52 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/CardGroup.elm
> +        |> FormItem.render validationResult
```suggestion
        options 
           |> List.indexedMap (renderCard type_ validationResult configData)
           |> FormItem.config configData
           |> FormItem.withLabel configData.label
           |> FormItem.render validationResult
```

2022-03-17 09:52 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Field/CheckboxGroup.elm
> +@docs withDisabledOption
Questo solitamente lo abbiamo messo nella sezione `Generics` però in effetti qui è più sensato. 
Riesci ad aggiornare i docs degli altri componenti per fare in modo che tutte le funzioni `withDisabledOption` stiano sotto la sezione `Options`?

2022-03-17 09:52 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Field/CheckboxGroup.elm
>  #### Options
Occhio che i docs sono strutturati in maniera un po' diversa per gli altri componenti

2022-03-17 09:52 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Field/CheckboxGroup.elm
> +    , isOnCheck
Manca questa funzione nei docs di esportazione

2022-03-17 09:52 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Field/CheckboxGroup.elm
> +    { r | ariaLabelledBy : Maybe String, layout : Layout, classList : List ( String, Bool ), id : String }
Qui possiamo usare `Config` o `ConfigData` per favore? Mi fa piangere sangue dagli occhi questa firma

2022-03-17 09:52 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Field/FormItem.elm
> +withLabel : Maybe Label.Config -> Config a msg -> Config a msg
Mancano i docs

2022-03-17 09:52 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Field/FormItem.elm
> +module Components.Field.FormItem exposing (PartialFieldConfig, config, render, withAdditionalContent, withLabel)
In generale mancano tutti i docs qui dentro

2022-03-17 09:52 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Field/Select.elm
> +            Maybe.map (customizeLabel configData) configData.label
Viso che è un oneliner possiamo usare il `Maybe.map` direttamente alla riga 627 evitando questa dichiarazione

2022-03-17 09:52 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Field/Textarea.elm
> +            Maybe.map (customizeLabel configData) configData.label
Idem

2022-03-17 09:57 UTC, Gsciarra commented on packages/pyxis-elm/src/Components/CardGroup.elm
> +        |> FormItem.render validationResult
`(List.indexedMap (renderCard type_ validationResult configData) options)` è il content del `div` precedente. Diventerebbe 
```Elm
(options |> List.indexedMap (renderCard type_ validationResult configData))
        |> FormItem.config configData
        |> FormItem.withLabel configData.label
        |> FormItem.withAdditionalContent configData.additionalContent
        |> FormItem.render validationResult
```

2022-03-17 09:59 UTC, Gsciarra commented on packages/pyxis-elm/src/Components/Field/CheckboxGroup.elm
> +@docs withDisabledOption
Spostando quello ho notato che le varie documentazioni differiscono per struttura. Ma farei una card a parte per dare una forma comune a tutto.

2022-03-17 16:43 UTC, ascandone requested changes

2022-03-17 16:43 UTC, ascandone commented on packages/pyxis-elm/src/Components/Field/CheckboxCardGroup.elm
> +        (List.map (mapOption tagger modelData.checkedValues) configData.options)
Come mai hai composto manualmente invece di usare `Html.map`?

2022-03-17 16:43 UTC, ascandone commented on packages/pyxis-elm/src/Components/Field/CheckboxCardGroup.elm
> +                (modelData.validation ctx modelData.checkedValues)
Come mai hai levato il `() ->` ?
Serviva per fare in modo di non calcolare inutilmente la validazione anche quando non la si stia mostrando (probabilmente avrei dovuto scriverlo)
Probabilmente ottimizzazione inutile nel 99% dei casi, ma non vedo perché levarla

2022-03-17 16:43 UTC, ascandone commented on packages/pyxis-elm/src/Components/Field/CheckboxGroup.elm
> +        { label : Html (Msg value)
Io metterei `Html Never` per far capire che è statico
Internamente, lo puoi trasformare di nuovo a `Html quelloCheTiPare` così: `Html.map never label`

2022-03-17 16:43 UTC, ascandone commented on packages/pyxis-elm/src/Components/Field/CheckboxGroup.elm
> +                (modelData.validation ctx modelData.checkedValues)
Come sopra, non vedo perché levare questa (piccola) ottimizzazione

2022-03-17 16:43 UTC, ascandone commented on packages/pyxis-elm/src/Components/Field/Select.elm
> +renderField : Result String () -> Model unknown value -> Config msg -> Html Msg
Credo che sia rimasto `unknown` dalla autogenerazione della segnatura dell'IDE

2022-03-17 16:46 UTC, Gsciarra commented on packages/pyxis-elm/src/Components/Field/CheckboxCardGroup.elm
> +        (List.map (mapOption tagger modelData.checkedValues) configData.options)
C'era un problema con i tipi

2022-03-17 16:46 UTC, Gsciarra commented on packages/pyxis-elm/src/Components/Field/CheckboxCardGroup.elm
> +                (modelData.validation ctx modelData.checkedValues)
Le ragioni servono per aggiungere codice in più, non per rimuoverlo. Questo vale in generale.

2022-03-17 16:47 UTC, Gsciarra commented on packages/pyxis-elm/src/Components/Field/CheckboxGroup.elm
> +        { label : Html (Msg value)
Come sopra, servono buone ragioni per aggiungere codice, non per toglierlo.

2022-03-17 16:55 UTC, ascandone commented on packages/pyxis-elm/src/Components/Field/CheckboxCardGroup.elm
> +                (modelData.validation ctx modelData.checkedValues)
La ragione è che scritto così c'è computazione inutile ogni volta che immetti un carattere nonostante non venga mostrata nella UI... Se hai un singolo form che fa solo `not String.empty` è irrilevante, se ce ne sono 10 che fanno cose più pesanti come il parsing di una targa, magari è un piccolo aiuto su device meno potenti

Niente di che, ma non capisco che male fanno 5 caratteri in più

2022-03-17 16:57 UTC, ascandone commented on packages/pyxis-elm/src/Components/Field/CheckboxGroup.elm
> +        { label : Html (Msg value)
Vabbè qui però si tratta di API esterna, non credo conti tanto avere una manciata di caratteri in più.
Non è più chiaro `Html Never` come api esterna, che significa esattamente che è statico?

2022-03-17 17:17 UTC, lauratrapani approved these changes

2022-03-18 08:29 UTC, alessiosantangelo approved these changes

2022-03-18 08:32 UTC, alessiosantangelo commented
@ascandone la review non deve essere il momento di "litigare" sul codice bensì di collaborare, in ogni caso al momento non ci sono particolari motivazioni per le quali serve tenere d'occhio le performance e comunque parliamo di una chiamata a funzione molto semplice. 

Ricordatevi che il repo e la review sono pubbliche e non si fanno belle figure a rispondersi in questi termini. Prossima volta meglio parlarne 5 minuti a voce in via preventiva.

2022-03-18 10:29 UTC, merged

2022-03-21 08:40 UTC, ascandone commented
> @ascandone la review non deve essere il momento di "litigare" sul codice bensì di collaborare, in ogni caso al momento non ci sono particolari motivazioni per le quali serve tenere d'occhio le performance e comunque parliamo di una chiamata a funzione molto semplice.
> 
> Ricordatevi che il repo e la review sono pubbliche e non si fanno belle figure a rispondersi in questi termini. Prossima volta meglio parlarne 5 minuti a voce in via preventiva.

Ah scusate! In effetti ho dato un po' per scontato di come funzionassero le review e avevo assunto che fosse la sede giusta per eventuali discussioni, però allora la prossima volta aggiusto il tiro
Grazie per avermelo segnalato 👍