[DS-69]: [Pyxis Elm] Implement the Autocomplete
primait/pyxis pull request #118
Opened 2022-03-22 13:50 UTC by alessiosantangelo

https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/DS-69

Adds Autocomplete component

2022-03-30 07:59 UTC, Gsciarra approved these changes

2022-03-30 08:48 UTC, lauratrapani commented on packages/pyxis-scss/src/scss/components/icons.scss
> +.icon--spinner {
Giusto una cosa, come mai è stata aggiunta questa classe e non uno degli spinner che ci sono già? (al massimo se serviva un comportamento diverso rispetto a quelli già previsti lo aggiungerei comunque tra gli altri spinner per questioni di ordine)

2022-03-30 09:54 UTC, emanuelemacri requested changes
Provando l'esempio ho visto un po' di comportamenti strani con il debouncer, che scattava molto e il reset che non funzionava. Inoltre alcuni elementi sono un po' diversi da quelli su [storybook](https://react-staging.prima.design/?path=/docs/components-autocomplete-%F0%9F%9A%A7-overview--page). Se non mi son spiegato bene nei commenti sentiamoci pure

2022-03-30 09:54 UTC, emanuelemacri commented on packages/pyxis-elm/src/Components/Field/Autocomplete.elm
> +    Suggestion { icon = icon, title = title, description = description }
Non era chiaro effettivamente dai mockup ma la description è un maybe, potrebbe non esserci.

2022-03-30 09:54 UTC, emanuelemacri commented on packages/pyxis-elm/src/Components/Field/Autocomplete.elm
> +            |> Icon.withSpinner True
Son d'accordo con laura, "icon" non è mi sembra il posto migliore per mettere questo withSpinner,  per ora lascialo così poi lo cambiamo

2022-03-30 09:54 UTC, emanuelemacri commented on packages/pyxis-elm/src/Components/Field/Autocomplete.elm
> +            |> Icon.withStyle Icon.neutral
Questa non dovrebbe essere un'icona boxata ma ha un suo div intorno `form-field__addon__reset`

2022-03-30 09:54 UTC, emanuelemacri commented on packages/pyxis-elm/src/Components/Field/Autocomplete.elm
> +        )
Manca l'addon [header](https://react-staging.prima.design/?path=/story/components-autocomplete-%F0%9F%9A%A7-all-stories--with-header), in più dalle prove che ho fatto l'addon [suggestion](https://react-staging.prima.design/?path=/story/components-autocomplete-%F0%9F%9A%A7-all-stories--with-suggestion) non va via quando escono i risultati

2022-03-30 09:54 UTC, emanuelemacri commented on packages/pyxis-elm/src/Components/Field/Autocomplete.elm
> +        ]
Questo l'avevo messo separato da un `item`, in quanto potrebbe contenere un bottone con un action, come in [questo](https://react-staging.prima.design/?path=/story/components-autocomplete-%F0%9F%9A%A7-all-stories--no-result-action) caso

2022-03-30 09:56 UTC, emanuelemacri requested changes

2022-03-30 09:56 UTC, emanuelemacri commented on packages/pyxis-scss/src/scss/components/forms/fields/autocomplete.scss
> +}
Non mi aveva messo questo commento:

Questo codice c'era già, ma nel file `dropdown.scss`, per l'esempio di implementazione vedi pure []([storybook](https://react-staging.prima.design/?path=/docs/components-autocomplete-%F0%9F%9A%A7-all-stories--with-suggestion))

2022-03-30 13:51 UTC, Gsciarra commented on packages/pyxis-elm/src/Components/Field/Autocomplete.elm
> +update : Msg value -> Model ctx value -> Effect ctx value (Msg value)
Non mi è chiaro il vantaggio di usare `Effect`. Mi sembra che sia assimilabile a quello che fa `FieldStatus`, che però è salvato direttamente nel model.

2022-04-01 12:23 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Field/Autocomplete.elm
> +update : Msg value -> Model ctx value -> Effect ctx value (Msg value)
Da parte dell'utilizzatore non c'è modo di sapere se la query che ottiene i risultati da mostrare debba essere nuovamente eseguita o meno. 

Se si lascia che la query venga eseguita ad ogni `type Msg = AutocompleteFieldChanged Autocomplete.Msg` allora significa che viene lanciata anche a `Autocomplete.OnFocus/OnBlur/OnSelect`. 

Esponendo questo modulo in pratica sto introducendo un valore di ritorno che indica se è necessario eseguire la query o meno. In pratica se l'autocomplete effect è `Idle` significa che non c'è nulla da fare, al pari di `Selecting` ma quando  viene invece risposto `Filtering` si capisce che si possa eseguire di nuovo la query.

Si potrebbe ottenere lo stesso comportamento, forse facendo un controllo sul fatto che il valore di `filter` sia cambiato o meno ma non è bellissimo. 
Che ne pensi?

2022-04-04 08:59 UTC, Gsciarra approved these changes

2022-04-04 09:26 UTC, merged