[DS-97]: [Pyxis Elm] Remove Text/Date/Number/Email modules
primait/pyxis pull request #119
Opened 2022-03-22 14:39 UTC by Gsciarra

https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/DS-97

2022-03-25 13:48 UTC, emanuelemacri requested changes

2022-03-25 13:48 UTC, emanuelemacri commented on packages/pyxis-elm/src/Stories/Book.elm
> +    --, date : DateFieldChapter.Model
puliamo? :D

2022-03-25 13:48 UTC, emanuelemacri commented on packages/pyxis-elm/src/Stories/Chapters/Fields/Input.elm
> +module Stories.Chapters.Fields.Input exposing (Model, docs, init)
Se leviamo le altre storie su date / number ecc dobbiamo aggiungere qui gli esempi

2022-03-25 13:51 UTC, Gsciarra commented on packages/pyxis-elm/src/Components/Field/Input.elm
> +@docs TextConstraints
Non sono essenziali, a me va bene anche rimuoverle.

2022-03-25 13:52 UTC, Gsciarra commented on packages/pyxis-elm/src/Components/Field/Input.elm
> +        , withValueMapper : API.Allowed
Anche su questo non ho particolari preferenze, ma è più comodo allineare i file di questa PR.

2022-03-25 13:53 UTC, Gsciarra commented on packages/pyxis-elm/src/Stories/Chapters/Fields/Input.elm
> +module Stories.Chapters.Fields.Input exposing (Model, docs, init)
Eh, di questo dovremmo parlarne per capire cosa ha senso inserire e cose invece sarebbe solo un doppione.

2022-03-25 15:01 UTC, emanuelemacri approved these changes
Per me ok 👍

2022-03-28 12:11 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Field/CheckboxCardGroup.elm
> +import Components.Field.Status as FieldState
Non sarebbe più corretto usare l'alias `Status`?

2022-03-29 07:46 UTC, emanuelemacri approved these changes
👍

2022-03-29 07:55 UTC, merged