[DS-79]: [Pyxis Scss] Accordion component
primait/pyxis pull request #135
Opened 2022-04-04 15:28 UTC by lauratrapani

https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/DS-79
SCSS accordion component
\

2022-04-06 09:05 UTC, alessiosantangelo requested changes

2022-04-06 09:05 UTC, alessiosantangelo commented on packages/pyxis-scss/src/scss/components/accordion.scss
> +.accordion {
Questo mi pare un po' misleading, di solito con `accordion` ci si riferisce al singolo elemento (`accordion-item`). 

Proverei a modificare come segue: 
- `accordion` diventa `accordion-group`
- `accordion-item` diventa `accordion`

2022-04-06 09:05 UTC, alessiosantangelo commented on packages/pyxis-scss/src/scss/components/accordion.scss
> +.accordion-item--white {
Meglio non usare il nome del colore di sfondo come modificatore. 
`accordion--light` andrà benissimo.

2022-04-06 09:50 UTC, lauratrapani commented on packages/pyxis-scss/src/scss/components/accordion.scss
> +.accordion {
In realtà molti Design System che ho consultato, tra cui Carbon, Audi e librerie come Bootstrap utilizzano Accordion per il gruppo e Accordion Item per il singolo item e io stessa avevo questa convenzione di riferimento, mentre non ho trovato esempi contrari in cui la parola "accordion" indichi l'elemento singolo.

2022-04-06 14:35 UTC, emanuelemacri commented on packages/pyxis-scss/src/scss/components/accordion.scss
> +.accordion {
Ho fatto lo stesso pensiero, ma in effetti tutti gli altri lo usano in questo modo, forse è stato un errore `storico` nostro

2022-04-06 15:04 UTC, emanuelemacri requested changes

2022-04-06 15:04 UTC, emanuelemacri commented on packages/pyxis-scss/src/scss/components/accordion.scss
> +  visibility: visible;
aggiungiamo anche una max-height, così se per un qualsiasi motivo non abbiamo l'altezza dell'accordion comunque si apre
```suggestion
  visibility: visible;
  max-height: fit-content;
 
```

2022-04-06 15:04 UTC, emanuelemacri commented on packages/pyxis-scss/src/scss/components/accordion.scss
> +}
Ma riusciamo ad aggiungere una piccolissima transizione/animazione in opacità o spostamento all'apertura? 👀

2022-04-07 09:12 UTC, emanuelemacri requested changes
Ultima cosina, poi mi sembra ok

2022-04-07 09:12 UTC, emanuelemacri commented on packages/pyxis-scss/src/scss/components/accordion.scss
> +  transition-timing-function: foundations.timing(base);
Sorry ci ho pensato solo ora, aggiungiamo sia qui che sotto un `will-change`

2022-04-07 10:01 UTC, emanuelemacri commented on packages/pyxis-scss/src/scss/components/accordion.scss
> +  transition-timing-function: foundations.timing(base);
Vero ma lo stiamo usando davvero molto poco e in questo caso mi sembra utile avendo transizioni più "pesanti"

2022-04-08 08:17 UTC, emanuelemacri approved these changes
👍

2022-04-08 08:18 UTC, merged