[DS-29]: [Pyxis Scss] Tooltip component
primait/pyxis pull request #143
Opened 2022-04-14 08:22 UTC by lauratrapani

https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/DS-29

Tooltip SCSS

2022-04-15 11:38 UTC, alessiosantangelo commented on packages/pyxis-scss/src/scss/foundations/layout.scss
> +.scroll-locked {
Aggiungerei una sezione nelle foundations per parlare di come lockare la pagina, altrimenti questa classe non verrà utilizzata

2022-04-15 11:38 UTC, alessiosantangelo commented on packages/pyxis-scss/src/scss/components/tooltip.scss
> +$_tooltipInitialOffset: lib.rem(4px);
Questo non corrisponde ad uno space di pyxis?

2022-04-15 11:38 UTC, alessiosantangelo commented on packages/pyxis-scss/src/scss/components/tooltip.scss
> +$_arrowWidth: lib.rem(16px);
Questo non corrisponde ad un'icon size di pyxis?

2022-04-15 12:12 UTC, emanuelemacri commented on packages/pyxis-scss/src/scss/components/tooltip.scss
> +$_tooltipInitialOffset: lib.rem(4px);
Yes, possiamo usare `foundations.spacing(3xs);`

2022-04-15 12:13 UTC, emanuelemacri commented on packages/pyxis-scss/src/scss/components/tooltip.scss
> +$_arrowWidth: lib.rem(16px);
In questo caso invece è una `width`, quindi ci sta avere una variabile

2022-04-15 12:42 UTC, emanuelemacri requested changes
Un paio di cosette, più quelle di UX già segnalate

2022-04-15 12:42 UTC, emanuelemacri commented on packages/pyxis-scss/src/scss/components/tooltip.scss
> +    transform: rotate(0deg)
Metti pure `rotate(0)`, dovrebbe segnalarcelo già stylelint 🤔

2022-04-15 12:42 UTC, emanuelemacri commented on packages/pyxis-scss/src/scss/components/tooltip.scss
> +    }
Ma questa è l'arrow? In ogni caso variabilizziamo questi numeri

2022-04-15 13:52 UTC, emanuelemacri approved these changes
👍

2022-04-20 08:03 UTC, alessiosantangelo approved these changes

2022-04-20 08:04 UTC, merged