[DS-117]: [Pyxis Elm] Autocomplete accessibility and full stories
primait/pyxis pull request #146
Opened 2022-04-20 13:47 UTC by Gsciarra

https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/DS-117

2022-04-20 14:17 UTC, alessiosantangelo approved these changes

2022-04-21 09:07 UTC, lauratrapani approved these changes
A me sembra ok, ho rilevato solo un piccolo errore CSS che aggiungo alla card dei fix

2022-04-22 11:01 UTC, lauratrapani requested changes

2022-04-22 11:01 UTC, lauratrapani commented on packages/pyxis-elm/src/Components/Form/Dropdown.elm
>          [ Attributes.class "form-dropdown-wrapper"
Se l'autocomplete è `small` allora bisogna aggiungere la classe `form-dropdown-wrapper--small`

2022-04-26 10:39 UTC, emanuelemacri requested changes

2022-04-26 10:39 UTC, emanuelemacri commented on packages/pyxis-elm/src/Components/Field/Autocomplete.elm
> +withAddonSuggestion : FormDropdown.SuggestionData -> Config value msg -> Config value msg
Segnalato in card un problema sulla visibilità delle suggestion (di dovrebbe vedere quando l'input è vuoto). Ho segnalato in [card](https://prima-assicurazioni-spa.myjetbrains.com/youtrack/agiles/95-223/96-2862?issue=DS-117) anche altri 2 problemi dell'autocomplete che non riguardano strettamente questa card, vedi tu se sistemarli qui o separatamente

2022-04-26 10:39 UTC, emanuelemacri commented on packages/pyxis-elm/src/Components/Field/Autocomplete.elm
> +withAddonSuggestion : FormDropdown.SuggestionData -> Config value msg -> Config value msg
Segnalato in card un problema sulla visibilità delle suggestion (di dovrebbe vedere quando l'input è vuoto). Ho segnalato in [card](https://prima-assicurazioni-spa.myjetbrains.com/youtrack/agiles/95-223/96-2862?issue=DS-117) anche altri 2 problemi dell'autocomplete che non riguardano strettamente questa card, vedi tu se sistemarli qui o separatamente

2022-04-27 08:26 UTC, lauratrapani approved these changes

2022-04-27 09:26 UTC, emanuelemacri approved these changes
Per me lato funzionalità è ok

2022-04-28 08:35 UTC, merged