[DS-161]: [Pyxis Scss] Some fix and improvements
primait/pyxis pull request #148
Opened 2022-04-26 10:08 UTC by lauratrapani

https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/DS-161

Fix on various CSS issues

2022-04-26 13:56 UTC, emanuelemacri requested changes

2022-04-26 13:56 UTC, emanuelemacri commented on packages/pyxis-scss/src/scss/foundations/typography.scss
> +@mixin text($size, $weight, $color:null) {
```suggestion
@mixin text($size, $weight, $color: null) {
```

2022-04-26 13:56 UTC, emanuelemacri commented on packages/pyxis-scss/src/scss/components/link.scss
> +  @include foundations.fontWeight(bold);
I link non dovrebbero essere sempre bold però o sbaglio? 🤔

2022-04-26 13:56 UTC, emanuelemacri commented on packages/pyxis-scss/src/scss/components/link.scss
> +  $color: actionBase;
Così si rompe il mixin `_underlineGradient`

2022-04-27 07:03 UTC, alessiosantangelo approved these changes

2022-04-27 08:04 UTC, emanuelemacri requested changes
ultima cosetta

2022-04-27 08:04 UTC, emanuelemacri commented on packages/pyxis-scss/src/scss/components/link.scss
>  }
Non è `$colorName` ma `$color`

2022-04-27 08:17 UTC, emanuelemacri approved these changes

2022-04-27 08:19 UTC, merged