[DS-81]: [Pyxis Elm] Implement the Accordion component
primait/pyxis pull request #152
Opened 2022-05-02 15:56 UTC by emanuelemacri

Accordion component

https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/DS-81

2022-05-04 13:54 UTC, lauratrapani commented on packages/pyxis-elm/src/Components/Accordion.elm
> +    Multiple []
Sbaglio o così com'è non si può inizializzare l'accordion con un item aperto? Forse è meglio prevedere questa opportunità

2022-05-04 13:54 UTC, lauratrapani commented on packages/pyxis-elm/src/Components/Accordion.elm
> +withLightVariant : Config msg -> Config msg
Per uniformità con gli altri elementi non è meglio mettere `withVariant` che come primo paramento ha una `Variant`? Così se si aggiunge una variant non abbiamo nemmeno problemi

2022-05-06 07:39 UTC, lauratrapani approved these changes

2022-05-06 07:44 UTC, alessiosantangelo requested changes

2022-05-06 07:44 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Accordion.elm
> +{-| Init Light variant.
Manca il costruttore della variante `neutral`

2022-05-06 07:44 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Accordion.elm
> +            ( Model { model | openingType = updateOpeningType id model.openingType }
Usa `withCmd` qui invece che la tupla

2022-05-06 07:44 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Accordion/Item.elm
> +render : (String -> msg) -> (String -> msg) -> List ( String, Bool ) -> (String -> Bool) -> Dict String Float -> Config msg -> Html.Html msg
Un po' troppi parametri, utilizza un record qui

2022-05-06 07:44 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Accordion.elm
> +                    itemData
Meglio passare un record invece che sei parametri ad una funzione, ad ogni modo potresti evitare la closure visto che `itemData` è l'ultimo parametro di `render`

2022-05-06 07:44 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Accordion/Item.elm
> +    (id ++ "-header")
Useless pipe

2022-05-06 07:44 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Accordion/Item.elm
> +    (id ++ "-section")
Idem

2022-05-06 07:44 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Accordion/Item.elm
> +    (id ++ "-content")
Idem

2022-05-06 09:04 UTC, alessiosantangelo requested changes

2022-05-06 09:04 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Accordion.elm
> +                    (Task.attempt (GotElement id) (Browser.Dom.getElement (Item.setContentId id)))
Scusami, mi ero perso questo pipe
```suggestion
                    (id 
                    |> Item.setContentId 
                    |> Browser.Dom.getElement 
                    |> Task.attempt (GotElement id) )
```

2022-05-06 09:04 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Accordion.elm
> +                    (Task.attempt (GotElement id) (Browser.Dom.getElement (Item.setContentId id)))
Anche qui si può fare la stessa cosa

2022-05-06 09:33 UTC, alessiosantangelo approved these changes
LGTM

2022-05-09 08:29 UTC, merged