[DS-165]: [Pyxis Storybook] Documentation for Tooltip
primait/pyxis pull request #165
Opened 2022-05-17 13:33 UTC by lauratrapani

https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/DS-165

Added documentation and stories for Tooltip HTML-CSS

2022-05-18 08:37 UTC, emanuelemacri requested changes
Tutto ok, ma controlliamo con i designer se mettere i comportamenti "non corretti" del bottomsheet in documentazione

2022-05-18 08:37 UTC, emanuelemacri commented on packages/pyxis-react/src/stories/components/Tooltip/Overview.tsx
> +    </span>
Questi due esempi idealmente non dovrebbero mai succedere o sbaglio? Magari facciamo un check lato design

2022-05-23 07:55 UTC, alessiosantangelo approved these changes

2022-05-23 13:44 UTC, emanuelemacri approved these changes

2022-05-23 13:45 UTC, merged