[DS-196]: [Pyxis SCSS] Improve Readme
primait/pyxis pull request #174
Opened 2022-05-27 08:47 UTC by lauratrapani

https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/DS-196

Update of Pyxis SCSS readme. Inclusion of Pyxis Tokens and Pyxis Icons readme.

2022-05-27 13:15 UTC, alessiosantangelo requested changes

2022-05-27 13:15 UTC, alessiosantangelo commented on packages/pyxis-scss/README.md
> +## ⚙️ Install Pyxis SCSS with Pyxis React or Pyxis Elm
```suggestion
## ⚙️ Usage with React or Elm
```

2022-05-27 13:15 UTC, alessiosantangelo commented on packages/pyxis-scss/README.md
> +## ⚙️ Install Pyxis SCSS standalone version
```suggestion
## ⚙️ Standalone usage
```

2022-05-27 13:15 UTC, alessiosantangelo commented on packages/pyxis-scss/README.md
> +### Install Pyxis SCSS
```suggestion
### Npm module usage
```

2022-05-27 13:15 UTC, alessiosantangelo commented on packages/pyxis-scss/README.md
> +To install `@pyxis/scss` you will need to follow the instructions for installing through [JFrog Artifactory](https://www.jfrog.com/confluence/display/RTF/Npm+Registry) described in the [Setup](https:
```suggestion
**Prerequisite**: [had configured Jfrog Artifactory cli](https://github.com/primait/pyxis#-setup) chapter of the monorepo.

To install `@pyxis/scss` via _npm_ simply run: 
```sh
$ npm i @pyxis/scss
```
```

2022-05-27 13:15 UTC, alessiosantangelo commented on packages/pyxis-scss/README.md
>  As seen in the previous section `@pyxis/scss` is built with the sass modules, we can use them in several ways.
Qui proverei a spiegare un po' di più nel dettaglio cosa significa "usare tutto pyxis", e in quali casi conviene utilizzare solo `base & foundations` oppure `components & atoms`.

Aggiungerei anche una sezione "usare Pyxis CSS" cioè la versione full precompilata.

2022-05-30 08:31 UTC, emanuelemacri requested changes

2022-05-30 12:59 UTC, emanuelemacri commented on packages/pyxis-scss/README.md
>  As seen in the previous section `@pyxis/scss` is built with the sass modules, we can use them in several ways.
> Qui proverei a spiegare un po' di più nel dettaglio cosa significa "usare tutto pyxis", e in quali casi conviene utilizzare solo base & foundations oppure components & atoms.

@alessiosantangelo queste cose sono già scritte sotto in ogni capitolo, non sarebbe una ripetizione?

Ok invece per aggiungere la sezione "usare Pyxis CSS" anche se scriverei che è comunque sconsigliato

2022-05-31 07:19 UTC, lauratrapani commented on packages/pyxis-scss/README.md
>  As seen in the previous section `@pyxis/scss` is built with the sass modules, we can use them in several ways.
Anche a me sembra già spiegato bene nei capitoli sottostanti, ok invece per Pyxis CSS

2022-05-31 08:08 UTC, alessiosantangelo approved these changes

2022-05-31 08:20 UTC, emanuelemacri approved these changes
LGTM

2022-05-31 08:45 UTC, merged