[DS-166]: [Pyxis Storybook] Documentation for Modal
primait/pyxis pull request #176
Opened 2022-05-31 09:52 UTC by emanuelemacri

Add storybook documentation for Modal component

https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/DS-166

2022-05-31 11:03 UTC, Cooryd commented
👋 Hi! I've raised a draft PR for the `Modal` component [here](https://github.com/primait/pyxis/pull/177). I've been working against the spec described in [DS-204](https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/DS-204). 

It looks like the config options detailed in these storybook docs differ quite significantly to the way I've built the component. I think we need a discussion on which way we would like to see the component configured so the two PRs can be aligned.

2022-05-31 12:15 UTC, emanuelemacri commented
> 👋 Hi! I've raised a draft PR for the `Modal` component [here](https://github.com/primait/pyxis/pull/177). I've been working against the spec described in [DS-204](https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/DS-204).
> 
> It looks like the config options detailed in these storybook docs differ quite significantly to the way I've built the component. I think we need a discussion on which way we would like to see the component configured so the two PRs can be aligned.

Hi @Cooryd ! We'll catch up in the meeting later, but in the meantime: this PR is usefull only to add the basic modal documentation on Storybook.

The "Modal" component you see inside is just an example to show the examples correctly (all the other Stories also use this method, but the components inside are just drafts waiting for the real components).

Regarding the API and the structuring of the component, the approach we saw together in the last meeting is the correct one.

As a first step in your PR I would just do the component and later we can update this documentation with the real component.

Thanks, see you later!

2022-05-31 13:47 UTC, lauratrapani requested changes

2022-06-01 07:31 UTC, lauratrapani reviewed
L'ultima cosa poi per me ok

2022-06-01 07:31 UTC, lauratrapani commented on packages/pyxis-react/src/stories/components/Modal/Modal.stories.tsx
> +  ...mobileFirstViewport,
A sto punto potremmo uniformare anche sui tooltip così abbiamo le storie coerenti tra loro

2022-06-01 09:05 UTC, merged