[DS-204]: [Pyxis React] Modal Component
primait/pyxis pull request #177
Opened 2022-05-31 10:52 UTC by Cooryd

https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/DS-204

TODO: 
- [ ] Unit tests
- [ ] Storybook docs

2022-05-31 11:28 UTC, Cooryd commented on packages/pyxis-react/src/components/Modal/Content/Content.tsx
> +  <div className="modal__content">
Should this component be removed and the styled `div` wrap any `children` components other than `Footer` & `Header` within `Modal`?

2022-05-31 11:28 UTC, Cooryd commented on packages/pyxis-react/src/components/Modal/Modal.tsx
> +          childType === 'content' ? [...(acc[childType] || []), child] : child,
We do this to account for multiple child content elements which aren't a `Header` or `Footer`. Is this necessary? If we were to do away with the `Content` component I would say yes, but with it, it seems like maybe not.

2022-06-03 10:54 UTC, lauratrapani commented on packages/pyxis-react/src/components/Modal/Modal.tsx
> +          childType === 'content' ? [...(acc[childType] || []), child] : child,
Yes, I think that all the `reduce` method is unnecessary in this case.

2022-06-06 12:50 UTC, lauratrapani requested changes

2022-06-06 12:50 UTC, lauratrapani commented on packages/pyxis-react/src/components/Modal/Header/Header.tsx
> +  badge?: ReactNode;
```suggestion
  badge?: FC<BadgeProps>;
```

2022-06-06 12:50 UTC, lauratrapani commented on packages/pyxis-react/src/components/Modal/Modal.tsx
> +  centered?: boolean;
Better `isCentered`

2022-06-06 12:50 UTC, lauratrapani commented on packages/pyxis-react/src/components/Modal/Modal.tsx
> +  children?: ReactNode;
```suggestion
  children: ReactElement<HeaderProps | FooterProps | typeof Content>[];
```

2022-06-06 12:50 UTC, lauratrapani commented on packages/pyxis-react/src/components/Modal/Modal.tsx
> +  id?: string;
```suggestion
  id: string;
```

2022-06-06 12:50 UTC, lauratrapani commented on packages/pyxis-react/src/components/Modal/Modal.tsx
> +    )
```suggestion
    ? Object.fromEntries(children)
```

2022-06-06 12:50 UTC, lauratrapani commented on packages/pyxis-react/src/components/Modal/Modal.tsx
> +    : ({} as ChildrenMap);
If `children` is mandatory, the ternary operation is unneccesary

2022-06-06 12:50 UTC, lauratrapani commented on packages/pyxis-react/src/components/Modal/Modal.tsx
> +        aria-describedby={accessibilityDescription && `${id}_modal-description`}
By convention, we don't use the underscore but a normal minus `-`

2022-06-06 12:50 UTC, lauratrapani commented on packages/pyxis-react/src/components/Modal/Modal.tsx
> +        aria-labelledby={id ? `${id}_header` : undefined}
Better to have a constant 
```
const headerId = `${id}-header`
```

2022-06-06 12:50 UTC, lauratrapani commented on packages/pyxis-react/src/components/Modal/Modal.tsx
> +        <div className={classNames('modal', `modal--${size}`)} role="document">
Why role document?

2022-06-06 12:50 UTC, lauratrapani commented on packages/pyxis-react/src/components/Modal/Modal.tsx
> +        />
```suggestion
        {onClose && <button
          aria-label="close"
          className="modal-close"
          onClick={onClose}
        />}
```

2022-06-06 12:50 UTC, lauratrapani commented on packages/pyxis-react/src/components/Modal/Modal.tsx
> +            })}
```suggestion
            && cloneElement(header, {
              id: headerId,
              onClose,
            })}
```

2022-06-06 12:50 UTC, lauratrapani commented on packages/pyxis-react/src/components/Modal/Modal.tsx
> +          {footer && cloneElement(footer)}
```suggestion
          {footer}
```

2022-06-06 12:50 UTC, lauratrapani commented on packages/pyxis-react/src/components/Modal/Modal.tsx
> +  Header: FC<HeaderProps>;
```suggestion
  Header: FC<Omit<HeaderProps, 'id' | 'onClose'>>;
```

2022-06-06 14:32 UTC, Cooryd commented on packages/pyxis-react/src/components/Modal/Modal.tsx
> +        <div className={classNames('modal', `modal--${size}`)} role="document">
I think I've left this is when working off some outdated accessibility documentation, I'll remove and add a `data-testid`   instead.

2022-06-07 07:49 UTC, lauratrapani commented on packages/pyxis-react/src/components/Modal/Modal.tsx
> +    | ReactElement<typeof Content>;
I think that for design a Modal should always have a Header

2022-06-07 08:08 UTC, Cooryd commented on packages/pyxis-react/src/components/Modal/Modal.tsx
> +    | ReactElement<typeof Content>;
Currently the styling requires all three sub-components to exist to have the correct top and bottom padding of content. Is this correct if we just want content to show in a modal (maybe for a loading overlay?)

2022-06-07 09:24 UTC, emanuelemacri requested changes
everything is pretty good 🚀 , just a few small tricks

2022-06-07 09:24 UTC, emanuelemacri commented on packages/pyxis-react/src/components/Modal/Footer/Footer.tsx
> +  text,
When possible (especially for booleans) we put default values, so we can avoid `undefined` in the functions that generate the classes

```suggestion
  alt = false,
  buttons,
  children,
  hasFullWidthButtons = false,
  id,
  isSticky = false,
  text,
```

2022-06-07 09:24 UTC, emanuelemacri commented on packages/pyxis-react/src/components/Modal/Footer/Footer.tsx
> +});
```suggestion
const getClasses = (isSticky: boolean, alt: boolean): string => classNames('modal__footer', {
  'modal__footer--alt': alt,
  'modal__footer--sticky': isSticky,
});

const getButtonClasses = (hasFullWidthButtons: boolean) => classNames('modal__footer__buttons', {
  'modal__footer__buttons--full-width': hasFullWidthButtons,
});
```

2022-06-07 09:24 UTC, emanuelemacri commented on packages/pyxis-react/src/components/Modal/Header/Header.tsx
> +  icon?: ReactElement<IconProps>;
Maybe is better define this with FC (like components `Button.tsx`)
```suggestion
  icon?: FC<IconProps>;
```

2022-06-07 09:42 UTC, lauratrapani commented on packages/pyxis-react/src/components/Modal/Header/Header.tsx
> +  icon?: ReactElement<IconProps>;
As Cory explained [here](https://github.com/primait/pyxis/pull/177#discussion_r890212372), the ReactElement is necessary if we want the user to customize the Icon

2022-06-07 10:15 UTC, Cooryd commented on packages/pyxis-react/src/components/Modal/Header/Header.tsx
> +  icon?: ReactElement<IconProps>;
This works for `Button` as the `Icon` props are determined from other `Button` props.
https://github.com/primait/pyxis/blob/66f60710d1c35188a2de161fbbd2582eafa07207/packages/pyxis-react/src/components/Button/Button.tsx#L27-L30
Changing this to a `FC` would mean the `Icon` could only ever be its default state unless another `iconProps` prop was added to `Modal.Header`, at which point we are just achieving `ReactElement` but with more steps. The only benefit I can see from this would be better typing which I mentioned in my reply to Laura's feedback.
 
> Icon should be a `ReactElement` so that it can be configured externally. An example may be that you want to pass the `alt` prop to the `Icon` used, this can be done with `<Modal.Header ... icon={<IconCar alt/>}>`. Although `ReactElement` has some generic options for `props` and `type`, they don't seem to work. I've looked this up and it seems like a [known issue](https://stackoverflow.com/a/59381632).

2022-06-07 10:16 UTC, Cooryd commented on packages/pyxis-react/src/components/Modal/Modal.tsx
> +    | ReactElement<typeof Content>;
I'll go with this and update the tests 👍

2022-06-07 15:36 UTC, lauratrapani requested changes
One more thing, then for me is ok

2022-06-07 15:36 UTC, lauratrapani commented on packages/pyxis-react/src/components/Modal/Modal.tsx
> +    mapChildren(Array.isArray(children) ? children : [children]),
```suggestion
    mapChildren(children),
```
If children is an array than the ternary is unnecessary

2022-06-08 07:29 UTC, lauratrapani approved these changes

2022-06-08 07:39 UTC, emanuelemacri approved these changes
The PR is ok for me, but you should do a rebase for resolve some conflict before merge.

I also add @alessiosantangelo  for a final check, I can't merge today 😄

2022-06-08 09:13 UTC, alessiosantangelo approved these changes

2022-06-08 09:14 UTC, merged