[DS-63]: [Pyxis React] Add badge component
primait/pyxis pull request #179
Opened 2022-06-01 10:07 UTC by lauratrapani

https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/DS-63

Implementation of React Badge component

2022-06-01 15:03 UTC, emanuelemacri requested changes
Una piccolezza, il resto è ok

2022-06-01 15:03 UTC, emanuelemacri commented on packages/pyxis-react/src/components/Badge/Badge.tsx
> +  children,
anche il `children` mettiamo in ordine alfabetico e cominciamo ad aggiungerlo anche nell'interface (dalla prossima versione di React sarà obbligatorio tanto)

2022-06-06 08:17 UTC, alessiosantangelo reviewed
A parte questo dubbio il resto mi sembra ok

2022-06-06 08:17 UTC, alessiosantangelo commented on packages/pyxis-react/src/components/Badge/Badge.tsx
> +export type BadgeVariant = 'brand' | 'action' | 'error' | 'success' | 'alert' | 'neutralGradient' | 'brandGradient' | 'ghost';
Non mi ricordo se avessimo già affrontato il discorso o meno, ma qui non sarebbe più pulito chiamare il tipo semplicemente `Variant`? 

Nel caso qualcuno dovesse utilizzarlo (per qualche strano motivo) potrebbe fare: 
`import {Variant as BadgeVariant} from 'Badge'` 

In questo modo sappiamo che ogni componente, o quasi,  avrà un suo tipo `Variant` rafforzando perciò la convenzione sulla nomenclatura.

2022-06-06 10:47 UTC, merged