[PRIMA-7577]: [Pyxis] Implementazione sezione `Components/Actions`
primait/pyxis pull request #192
Opened 2021-01-22 14:34 UTC by eFFeeMMe

https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/PRIMA-7577 

 WIP

2021-01-22 15:30 UTC, alessiosantangelo commented on src/Pyxis/Pages/Button.elm
> +
Così è un po' troppo meccanico. Per ogni combinazione `button/background` devi aggiungere una chiave sul model che rappresenti quell'oggeto. 

Suggerirei una cosa del tipo: 

Farei una cosa del tipo: 
```
type alias Model =  {
    buttonPreviews: List ButtonPreview
 }
 
initialModel : Model 
initialModel = {
    buttonPreviews :  [
        calloutOnLightBg,
        calloutOnDarkBg 
    ]
    |> List.map toButtonPreview
   }  

type alias ButtonPreview = {
  button: Button ButtonType Background
  tabbedContainer : TabbedContainer.State
}

toButtonPreview : Button ButtonType Background -> ButtonPreview
toButtonPreview btn = 
   { button: btn, tabbedContainer = TabbedContainer.init }

type Background =  Light | Dark

type ButtonType = Callout | Primary | Secondary | Tertiary

type Button = 
   Button ButtonType Background 
   
calloutOnDarkBg :  Button Callout Dark
calloutOnDarkBg = 
   Button Callout Dark
   
calloutOnLightBg :  Button Callout Light 
calloutOnLightBg = 
   Button Callout Light
   
primaryOnDarkBg : Button Primary Dark
primaryOnDarkBg = 
   Button Primary Dark
  .....

```

2021-01-22 15:30 UTC, alessiosantangelo commented on src/Pyxis/Pages/Button.elm
> +
Importante è esporre solo le firme degli union types, senza (..). 

Inoltre direi di rinominare da `TabbedContainer` a `Previewer` (o simile).

2021-01-22 15:37 UTC, alessiosantangelo commented on src/Pyxis/Pages/Button.elm
> +
Mentre per il `Msg` puoi fare

```
type Msg = 
  TabbedContainerUpdate String TabbedContainer.State -- Es.  TabbedContainerUpdate "callout_on_bg_dark" "Preview"


```
 update : Msg -> Model -> (Model, Cmd Msg)
 update msg model =  
      case msg of 
         TabbedContainerUpdate btnSlug tabbedContainerState ->
             model 
               |> updateButtonPreview btnSlug tabbedContainerState
               |> withoutCmds
        
 
 updateButtonPreview : String -> TabbedContainerState -> Model -> Model 
 updateButtonPreview .... 
 
 
 ```

2021-01-22 15:39 UTC, alessiosantangelo commented on src/Pyxis/Pages/Button.elm
> +
La cosa interessante di questo approccio è che il tuo tipo `Button Callout Dark` è estremamente significativo già nelle firme.

2021-01-27 08:18 UTC, alessiosantangelo requested changes
Un po' di cose di stile...

Aggiungi il linter SCSS (https://github.com/primait/pyxis-npm/blob/master/.stylelintrc) su Pyxis e un comando sul `package.json` per lanciarlo, `yarn lint`.

Aggiungi `elm-review` (https://github.com/primait/prima-elm/blob/master/elm-analyse.json)
e un comando sul `package.json` per lanciarlo, `yarn review`.

2021-01-27 08:18 UTC, alessiosantangelo commented on src/Pyxis/Pages/Button.elm
> +        Dict String String
Prova a definire un alias un po' più parlante per questo `Dict String String` (es. `Dict TabContainerId HtmlSource`

2021-01-27 08:18 UTC, alessiosantangelo commented on src/Pyxis/Pages/Button.elm
> +            ( model, Cmd.none )
Bisogna usare i `withCmds, withoutCmds` e scrivere le funzioni di update in pipe.

2021-01-27 08:18 UTC, alessiosantangelo commented on src/Pyxis/Pages/Button.elm
> +            in
```
ReceivedInnerHTML {target, innerHTML} ->
```

2021-01-27 08:18 UTC, alessiosantangelo commented on src/Pyxis/Pages/Button.elm
> +        )
```
(sectionIntro :: (List.map
                (renderSampleSection model)
                [ sectionCallout
                , sectionPrimary
                , sectionSecondary
                , sectionTertiary
                ])
```

2021-01-27 08:18 UTC, alessiosantangelo commented on src/Pyxis/Pages/Button.elm
> +        (Dict.get slug model.tabbedContainerStates |> Maybe.withDefault TabbedContainer.init)
Quando usi il pipe fallo per tutti gli argomenti
```
model.tabbedContainerStates
|>Dict.get slug
|>Maybe.withDefault TabbedContainer.init
```

2021-01-27 08:18 UTC, alessiosantangelo commented on src/Pyxis/Pages/Button.elm
> +    Dict.get slug model.receivedInnerHTMLs
Pipe

2021-01-27 08:18 UTC, alessiosantangelo commented on src/Pyxis/Ports.elm
> +port askInnerHTML : String -> Cmd msg
`requestInnerHtml`

2021-01-27 08:18 UTC, alessiosantangelo commented on src/public/scss/pages/components/_button.scss
> +  color: #e74c3c;
mancano gli spazi tra una regola e l'altra. I colori da usare dovrebbero essere quelli di Pyxis se ci sono (abbiamo un verde e un rosso).

2021-01-27 08:18 UTC, alessiosantangelo commented on src/public/scss/pages/components/_button.scss
> +  > li {
No tag puri nè selettori di profondità

2021-01-27 09:03 UTC, kioan000 requested changes

2021-01-27 09:03 UTC, kioan000 commented on src/public/scss/pages/components/_button.scss
> +.pyxis__page-button__section-intro,
non mi convince molto la nomenclatura bem rispetto allo sviluppo dei componenti e delle cartelle sass.
A leggere fin qua mi sembra che la root dovrebbe essere `page-button` però vedo che sta in una cartella components dentro page (il che mi fa pensare a un bottone condiviso tra le pagine)

2021-01-27 09:03 UTC, kioan000 commented on src/public/scss/pages/components/_button.scss
> +.dos-and-donts__dos__header,
se è bem non dovrebbe stare qua dentro

2021-01-28 15:19 UTC, kioan000 approved these changes

2021-02-01 09:28 UTC, merged