[PRIMA-11996]: [Pyxis] Implementazione dei design token
primait/pyxis pull request #20
Opened 2021-12-17 16:55 UTC by lauratrapani

https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/PRIMA-11996

Implementation of design tokens

2021-12-22 15:28 UTC, emanuelemacri requested changes
Una sola cosetta rimasta appesa

2021-12-22 15:28 UTC, emanuelemacri commented on packages/pyxis-tokens/sd.config.js
> +})
Questo può andare via

2021-12-22 17:13 UTC, emanuelemacri approved these changes

2021-12-23 08:33 UTC, Gsciarra approved these changes

2021-12-23 10:26 UTC, alessiosantangelo requested changes

2021-12-23 10:26 UTC, alessiosantangelo commented on packages/pyxis-tokens/tokens/breakpoints.json
> +  "breakpoint": {
Qui `value` si può rimuovere direttamente in favore del valore. Inoltre eviterei di avere il valore in `px` se possibile ma lo lascerei come integer.

2021-12-23 10:26 UTC, alessiosantangelo commented on packages/pyxis-tokens/sd.config.js
> +                {
Qui c'è un sacco di boilerplate ripetuto. Si può usare un `map` invece di avere tutta questa struttura.

2021-12-23 10:26 UTC, alessiosantangelo commented on packages/pyxis-tokens/package.json
> +{
Sicuri che fare un package `pyxis-tokens` sia la scelta corretta? Non ci vedo granchè valore. I tokens dovrebbero essere uno step di `prebuild` dell'ambiente di sviluppo.

2021-12-23 10:26 UTC, alessiosantangelo commented on packages/pyxis-tokens/tokens/colors.json
> +  "color": {
Anche qui non vedo il valore di avere una chiave `value`. Sicuri che non si possa intervenire nella config di `style-dictionary`?

2021-12-23 10:26 UTC, alessiosantangelo commented on packages/pyxis-react/src/stories/foundations/Color/common.tsx
> +export const solid:ColorRow[] = Object.values(tokens.color.solid)
Qui si vede chiaramente che la struttura in input non è il massimo della vita.

2021-12-23 10:26 UTC, alessiosantangelo commented on packages/pyxis-react/src/stories/foundations/Elevation/common.tsx
> +  .sort((a, b) => (Number(b.slice(-2)) - Number(a.slice(-2)) )) as Color[];
Doppio sort

2021-12-23 11:51 UTC, emanuelemacri commented on packages/pyxis-tokens/tokens/colors.json
> +  "color": {
Da quello che vedo è obbligatorio, in quanto potresti avere anche altri parametri nel token (commenti, nomi o custom attribute): https://amzn.github.io/style-dictionary/#/tokens?id=design-token-attributes

2021-12-23 15:39 UTC, emanuelemacri commented on packages/pyxis-tokens/tokens/breakpoints.json
> +  "breakpoint": {
Come scritto sotto il value non si può rimuovere, se è utile invece si può fare una funzione per tornare il valore in px solo nelle variabili, ma lasciarlo pulito nel json

2021-12-23 16:26 UTC, emanuelemacri commented on packages/pyxis-react/src/stories/foundations/Elevation/common.tsx
> +  .sort((a, b) => (Number(b.slice(-2)) - Number(a.slice(-2)) )) as Color[];
Era voluto in realtà, in quanto ci serve sortare prima in ordine alfabetico e poi per ultimi due caratteri, trovi una versione nuova pushata con un solo sort (ma più bruttina all'interno)

2021-12-28 13:26 UTC, emanuelemacri commented on packages/pyxis-scss/package.json
> +    "prettify:token": "prettier --write \"src/scss/tokens/*.scss\"",
Al momento ho messo prettier solo sui file dei token, in una prossima PR lo configuriamo e lanciamo su tutto magari

2021-12-28 15:39 UTC, alessiosantangelo approved these changes

2021-12-28 16:47 UTC, merged