[PRIMA-12050]: [Pyxis React] Implementazione del componente Button
primait/pyxis pull request #23
Opened 2021-12-28 19:39 UTC by emanuelemacri

Implement Button in pyxis-react

https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/PRIMA-12050

2021-12-30 10:36 UTC, alessiosantangelo requested changes
Questo è il tipico caso in cui gli unit test tornano utilissimi. 

Possiamo mettere sotto test la combinazione di props come facciamo nella libreria Elm e controllare che altre condizioni mutualmente esclusive non si verifichino.

2021-12-30 10:36 UTC, alessiosantangelo commented on packages/pyxis-react/src/components/Button/Button.tsx
> +      'button--only-icon': Icon && iconPlacement === 'only',
Cogliamo l'occasione per modificare questo `only-icon` in `icon-only` che è corretto anche in inglese?

2021-12-30 10:36 UTC, alessiosantangelo commented on packages/pyxis-react/src/components/Button/types.ts
> +import { FC, HTMLAttributeAnchorTarget } from 'react';
Ottima soluzione, mi sembra anche chiara :) A questo punto provo anche a replicarla su Elm per avere le stesse costraints :)

2021-12-30 10:36 UTC, alessiosantangelo commented on packages/pyxis-react/src/components/Button/Button.tsx
> +  return (
Qui secondo me fai prima a fare due diversi _functional components_, uno che renderizza un `<button>` e uno che renderizza un `<a>` così da avere le giuste props dove servono. 
Anche perchè se mettiamo `href` non ha senso poter mettere anche `onClick` ecc.

Manca come mandatory la label per l'accessibilità

2021-12-30 10:36 UTC, alessiosantangelo commented on packages/pyxis-react/src/components/Icon/Icon.tsx
> +  alt = false,
Qui è il caso di stabilire una convenzione sul nome delle props boolean:
- hanno tutte un prefisso `is/has/can/should`
- niente prefisso

In React la convenzione sulle props è spesso quella di avere l'attributo senza prefisso ma non ho particolari preferenze. 

Però dovremmo avere qui e altrove `isBoxed & isAlt | boxed & alt`

2021-12-30 10:52 UTC, emanuelemacri commented on packages/pyxis-react/src/components/Icon/Icon.tsx
> +  alt = false,
Anche io non ho una particolare preferenza, il prefisso delle volte le rende un pochino più parlanti, però avremmo anche tanti casi diversi come dicevi tu (`is/has/can/should`).

Forse eviterei per lasciare tutto un po' più pulito, tanto mi sembra comunque molto comprensibile, che dici?

2021-12-30 10:58 UTC, emanuelemacri commented on packages/pyxis-react/src/components/Button/Button.tsx
> +  return (
Ok sui diversi FC, così evitiamo props bruttine (come type).
Ma dici che un `onClick` non serve mai su una `a`? Nel caso in cui volessimo tracciare le analytics o altro non sarebbe meglio lasciarlo?

Riguardo la label per l'accessibilità non serve in quanto il bottone è già un componente di tipo testuale, serve solo nel caso in cui il bottone sia `icon-only`, ma in quel caso ci pensa il componente `Icon` a renderizzare l'`aria-label`.

2021-12-30 11:01 UTC, emanuelemacri commented on packages/pyxis-react/src/components/Button/Button.tsx
> +  return (
Ah shit, per l'accessibilità serve anche `onKeyDown` per gli eventi da tastiera

2022-01-05 15:49 UTC, alessiosantangelo requested changes

2022-01-05 15:49 UTC, alessiosantangelo commented on packages/pyxis-react/src/components/Button/Button.test.tsx
> +      expect(primary).toHaveClass('button--primary');
```suggestion
      expect(screen.getByTestId('variant-primary')).toHaveClass('button--primary');
```

2022-01-05 15:49 UTC, alessiosantangelo commented on packages/pyxis-react/src/components/Button/Button.test.tsx
> +      const secondary = screen.getByTestId('variant-secondary');
Farei la modifica suggerita nel commento di cui sopra per evitare di avere tutte queste assegnazioni di costanti che poi non si usano.

2022-01-05 15:49 UTC, alessiosantangelo commented on packages/pyxis-react/src/components/Button/Button.test.tsx
> +  describe('boolean props', () => {
```suggestion
  describe('generics', () => {
```

2022-01-05 15:49 UTC, alessiosantangelo commented on packages/pyxis-react/src/components/Button/Button.test.tsx
> +describe('the button component', () => {
```suggestion
describe('Button component', () => {
```

2022-01-05 15:49 UTC, alessiosantangelo commented on packages/pyxis-react/src/components/Button/Button.test.tsx
> +    test('should render the given child string and default props', () => {
```suggestion
    test('should render a primary variant with type submit and textual content', () => {
```

2022-01-05 15:49 UTC, alessiosantangelo commented on packages/pyxis-react/src/components/Button/Button.test.tsx
> +  describe('variant props', () => {
```suggestion
  describe('variant option', () => {
```

2022-01-05 15:49 UTC, alessiosantangelo commented on packages/pyxis-react/src/components/Button/Button.test.tsx
> +    test('should render the primary variant', () => {
```suggestion
    test('should be primary, () => {
```

2022-01-05 15:49 UTC, alessiosantangelo commented on packages/pyxis-react/src/components/Button/Button.test.tsx
> +    test('should render the secondary variant', () => {
```suggestion
    test('should be secondary', () => {
```

2022-01-05 15:49 UTC, alessiosantangelo commented on packages/pyxis-react/src/components/Button/Button.test.tsx
> +    test('should render the tertiary variant', () => {
```suggestion
    test('should be tertiary', () => {
```

2022-01-05 15:49 UTC, alessiosantangelo commented on packages/pyxis-react/src/components/Button/Button.test.tsx
> +    test('should render the brand variant', () => {
```suggestion
    test('should be brand', () => {
```

2022-01-05 15:49 UTC, alessiosantangelo commented on packages/pyxis-react/src/components/Button/Button.test.tsx
> +    test('should render the ghost variant', () => {
```suggestion
    test('should be ghost', () => {
```

2022-01-05 15:49 UTC, alessiosantangelo commented on packages/pyxis-react/src/components/Button/Button.test.tsx
> +  describe('size props', () => {
```suggestion
  describe('has a size option', () => {
```

2022-01-05 15:49 UTC, alessiosantangelo commented on packages/pyxis-react/src/components/Button/Button.test.tsx
> +  describe('default props', () => {
```suggestion
  describe('with default options', () => {
```

2022-01-05 15:49 UTC, alessiosantangelo commented on packages/pyxis-react/src/components/Button/Button.test.tsx
> +    test('should render the huge size', () => {
```suggestion
    test('should be huge', () => {
```

2022-01-05 15:49 UTC, alessiosantangelo commented on packages/pyxis-react/src/components/Button/Button.test.tsx
> +    test('should render the large size', () => {
E via di seguito per tutti i `test(...)`

2022-01-05 15:49 UTC, alessiosantangelo commented on packages/pyxis-react/src/components/Button/Button.tsx
> +    size = 'large',
Mettiamo `medium` come default

2022-01-05 15:49 UTC, alessiosantangelo commented on packages/pyxis-react/src/components/Button/Button.tsx
> +    dataTestId,
Facciamoci passare solo l'`id` e mettiamolo uguale al `data-test-id`

2022-01-05 15:49 UTC, alessiosantangelo commented on packages/pyxis-react/src/components/Button/Button.tsx
> +  );
Questa funzione sarebbe da estrapolare da qui dentro così da: 
- poterla firmare 
- poter risolvere a priori l'esistenza o meno di `Icon`

2022-01-05 16:58 UTC, emanuelemacri commented on packages/pyxis-react/src/components/Button/Button.tsx
> +  );
@alessiosantangelo pushato le modifiche, è diventato un bel po' più prolisso 🥲

2022-01-10 08:10 UTC, alessiosantangelo approved these changes

2022-01-10 08:34 UTC, merged