[DS-269]: [Pyxis React] RadioCard + Checkbox Card component
primait/pyxis pull request #235
Opened 2022-08-04 12:21 UTC by lauratrapani

https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/DS-269

2022-08-05 12:45 UTC, emanuelemacri requested changes

2022-08-05 12:45 UTC, emanuelemacri commented on packages/pyxis-react/src/components/Form/CheckboxCardGroup/CheckboxCardGroup.tsx
> +export type CheckboxCardGroupProps = (Omit<CardGroupProps, 'type'>);
```suggestion
export type CheckboxCardGroupProps = Omit<CardGroupProps, 'type'>;
```

2022-08-05 12:45 UTC, emanuelemacri commented on packages/pyxis-react/src/internalComponents/CardGroup/Control.tsx
> +  className?: string,
Dobbiamo sistemare il linter, ma intanto sistema l'ordine e gli spazi please (sia qui che nelle varie Interface)

2022-08-05 12:45 UTC, emanuelemacri commented on packages/pyxis-react/src/internalComponents/CardGroup/Control.tsx
> +          {isIconAddon ? addon({}) : <img alt="" height={70} src={addon} width={70} />}
Passiamolo l'alt, meglio che lasciarlo sempre vuoto

```suggestion
          {isIconAddon ? addon({}) : <img alt={restProps.alt} height={70} src={addon} width={70} />}
```

2022-08-05 12:45 UTC, emanuelemacri commented on packages/pyxis-react/src/components/Form/RadioCardGroup/RadioCardGroup.tsx
> +RadioCardGroup.Radio = Control;
Che dici se questi li chiamiamo solo `Item`?
Così invece di:
```
<RadioCardGroup>
  <RadioCardGroup.Radio />
  <RadioCardGroup.Radio />
</RadioCardGroup>
```
viene fuori:

```
<RadioCardGroup>
  <RadioCardGroup.Item />
  <RadioCardGroup.Item />
</RadioCardGroup>
```

item per le `Checkbox`.

Così sarebbero sempre `Item` ma mi sembra più snello

2022-08-05 15:41 UTC, Gsciarra commented on packages/pyxis-react/src/components/Form/RadioCardGroup/RadioCardGroup.tsx
> +  initialValue?: [string];
```suggestion
  initialValue?: string;
```

2022-08-08 09:22 UTC, lauratrapani commented on packages/pyxis-react/src/internalComponents/CardGroup/Control.tsx
> +          {isIconAddon ? addon({}) : <img alt="" height={70} src={addon} width={70} />}
Essendo un'immagine decorativa, l'alt può essere vuoto

2022-08-08 09:25 UTC, Gsciarra approved these changes

2022-08-08 10:24 UTC, emanuelemacri approved these changes
👍

2022-08-08 12:03 UTC, alessiosantangelo approved these changes

2022-08-08 12:04 UTC, merged