[DS-299]: [Pyxis React, Pyxis Elm, Pyxis SCSS] Change Html in Select component
primait/pyxis pull request #236
Opened 2022-08-05 10:50 UTC by lauratrapani

https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/DS-299

2022-08-09 14:16 UTC, emanuelemacri requested changes
one little thing

2022-08-09 14:16 UTC, emanuelemacri commented on packages/pyxis-react/src/components/Form/Select/Select.tsx
> +import Dropdown, { Item } from 'internalComponents/Dropdown/Dropdown';
```suggestion
import Dropdown, { Item } from 'internalComponents/Dropdown';
```

2022-08-10 08:08 UTC, alessiosantangelo requested changes
Due cavolatine, il resto LGTM

2022-08-10 08:08 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Pyxis/Components/Field/Select.elm
> +    | OnMouseEnter Option
Metterei in ordine alfabetico

2022-08-10 08:08 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Pyxis/Components/Field/Select.elm
> +        _ ->
Meglio usare `Nothing`qui

2022-08-10 08:08 UTC, alessiosantangelo commented on packages/pyxis-react/src/stories/components/Select/Select.stories.tsx
> +  {
Magari questo array autogeneriamolo invece che scriverlo a mano

2022-08-10 13:15 UTC, Gsciarra approved these changes

2022-08-10 14:13 UTC, alessiosantangelo submitted a review, later dismissed

2022-08-11 07:50 UTC, emanuelemacri approved these changes

2022-08-12 09:15 UTC, emanuelemacri approved these changes

2022-08-12 09:16 UTC, merged