[DS-312]: [Pyxis React] Refactor of react form components
primait/pyxis pull request #237
Opened 2022-08-05 15:22 UTC by emanuelemacri

Refactor FormItem and FormField inside Form component

https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/DS-312

2022-08-09 13:27 UTC, lauratrapani submitted a review, later dismissed

2022-08-09 13:27 UTC, lauratrapani commented on packages/pyxis-react/src/hoc/withFormItem/withFormItem.tsx
> +import React, { FC, ReactElement, ReactNode } from 'react';
Da qualche parte dovremmo testare che le props di passate attraverso `withFormItem` vengano renderizzate correttamente, no?

2022-08-09 13:27 UTC, lauratrapani commented on packages/pyxis-react/src/components/Form/Input/Input.tsx
> +          aria-describedby={getAriaDescribedBy(hint && hintId, addon && addonId)}
Ma visto che questo `&&` doppio è su più componenti, non ha senso portarlo nella funzione o cambiare il modo in cui sono generati gli id?

2022-08-09 13:27 UTC, lauratrapani commented on packages/pyxis-react/src/components/Form/Select/Select.test.tsx
> +import { generateIds } from '../../../commons/utils/form';
```suggestion
import { generateIds } from 'commons/utils/form';
```

2022-08-09 13:27 UTC, lauratrapani commented on packages/pyxis-react/src/internalComponents/CardGroup/Option.tsx
> +import { generateIds } from '../../commons/utils/form';
```suggestion
import { generateIds } from 'commons/utils/form';
```

2022-08-09 13:27 UTC, lauratrapani commented on packages/pyxis-react/src/stories/components/Input/Input.stories.tsx
> +import GlobalInput, {InputProps} from "components/Form/Input";
Nelle ArgTables delle varie storie io vedo solo due o tre props ed è davvero misleading

2022-08-09 13:27 UTC, lauratrapani commented on packages/pyxis-react/src/stories/components/Label/Label.stories.tsx
> +  <Input name="input" label="Label" />
Forse questa storia dovrebbe chiamarsi diversamente ora

2022-08-09 13:27 UTC, lauratrapani commented on packages/pyxis-react/src/stories/components/Select/Select.stories.tsx
> +import {WithFormItem} from "../../../hoc/withFormItem/withFormItem";
```suggestion
import {WithFormItem} from "hoc/withFormItem/withFormItem";
```

2022-08-10 07:57 UTC, emanuelemacri commented on packages/pyxis-react/src/components/Form/Input/Input.tsx
> +          aria-describedby={getAriaDescribedBy(hint && hintId, addon && addonId)}
Mi sembra più chiaro così, almeno si capisce dal componente che c'è una condizione, oltre quello preferirei avere una funzione "semplice" che genera solo gli id, altrimenti bisognerebbe passargli anche i vari `addon`, `error` o `hint`

2022-08-10 08:03 UTC, emanuelemacri commented on packages/pyxis-react/src/stories/components/Input/Input.stories.tsx
> +import GlobalInput, {InputProps} from "components/Form/Input";
io le vedo tutte 🤔

2022-08-10 10:39 UTC, emanuelemacri commented on packages/pyxis-react/src/hoc/withFormItem/withFormItem.tsx
> +import React, { FC, ReactElement, ReactNode } from 'react';
Giusto, aggiunti i test sia su `withFormItem` che su `FormField`

2022-08-10 13:00 UTC, alessiosantangelo requested changes
LGTM 
Forse si potrebbe pulire un po' la parte dei tests evitando le tante chiamate a `generateIds` e usando una variabile

2022-08-10 13:01 UTC, alessiosantangelo approved these changes

2022-08-11 07:57 UTC, alessiosantangelo approved these changes

2022-08-11 08:24 UTC, Gsciarra commented on packages/pyxis-react/src/components/Form/Input/Input.tsx
> +          aria-describedby={getAriaDescribedBy(hint && hintId, addon && addonId)}
Per questo ho dato una soluzione sopra

2022-08-11 08:24 UTC, Gsciarra commented on packages/pyxis-react/src/stories/components/Input/Overview.tsx
> +import {Input as InputArgs} from "components/Form/Input/Input";
```suggestion
import {Input as BaseInput} from "components/Form/Input/Input";
```

2022-08-11 11:37 UTC, Gsciarra commented on packages/pyxis-react/src/components/Form/DateInput/DateInput.test.tsx
> +      expect(input).toHaveAttribute('aria-errormessage', errorId(name, 'Error Message'));
`errorId(` Non sarebbe meglio se iniziassero con get/generate?

2022-08-11 12:39 UTC, Gsciarra approved these changes

2022-08-11 12:47 UTC, merged