[DS-241]: [Pyxis React] Checkbox + Radio component
primait/pyxis pull request #239
Opened 2022-08-10 10:46 UTC by lauratrapani

https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/DS-241

2022-08-18 12:36 UTC, alessiosantangelo approved these changes
LGTM

2022-08-18 13:36 UTC, emanuelemacri requested changes
un paio di cosette

2022-08-18 13:36 UTC, emanuelemacri commented on packages/pyxis-react/src/stories/components/Radio/Overview.tsx
> +      <p className="title-s-bold c-neutral-base">Checkbox</p>
```suggestion
      <p className="title-s-bold c-neutral-base">Radio</p>
```

2022-08-19 07:34 UTC, emanuelemacri requested changes
ultimissima cosettina

2022-08-19 07:34 UTC, emanuelemacri commented on packages/pyxis-react/src/components/Form/CheckboxGroup/CheckboxGroup.tsx
> +import { OptionLayout } from '../../../internalComponents/ControlGroup/ControlGroup';
```suggestion
import { OptionLayout } from 'internalComponents/ControlGroup/ControlGroup';
```

2022-08-22 08:07 UTC, merged