[DS-244]: [Pyxis React] Form Grid component
primait/pyxis pull request #240
Opened 2022-08-12 15:18 UTC by emanuelemacri

Create FormGrid component with Row and Col.
Create Fieldset component

https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/DS-244

2022-08-18 14:31 UTC, lauratrapani commented on packages/pyxis-react/src/components/Form/Legend/Legend.test.tsx
> +  describe('with default options', () => {
`describe` non andrebbe utilizzato per raggruppare test per "tematica"? in alcuni casi lo vedo un po' forzato qui dentro.

2022-08-18 14:54 UTC, emanuelemacri commented on packages/pyxis-react/src/components/Form/Legend/Legend.test.tsx
> +  describe('with default options', () => {
giusto

2022-08-18 15:04 UTC, lauratrapani requested changes

2022-08-18 15:04 UTC, lauratrapani commented on packages/pyxis-react/src/stories/components/Form/Overview.tsx
>        </Canvas>
Manterrei le info riguardo `form` e `fieldset` dentro il paragrafo sull'accessibilità visto che non sono molto pertinenti con il resto. Forse sarebbe meglio riorganizzare la struttura e mettere questo file e relative storie dentro `FormGrid`

2022-08-22 08:20 UTC, alessiosantangelo requested changes
Giusto una cavolata, il resto mi sembra ok al netto dei commenti di @lauratrapani

2022-08-23 12:45 UTC, emanuelemacri commented on packages/pyxis-react/src/stories/components/Legend/Overview.tsx
>        <Table
Per ora l'ho lasciata, poi aggiungo `legend`, `form` e `formGrid` su zeroheight e sostituiamo le tabelle con il link

2022-08-23 13:13 UTC, lauratrapani requested changes

2022-08-23 13:13 UTC, lauratrapani commented on packages/pyxis-react/src/components/FormGrid/Row/Row.tsx
> +   */
Per questioni di pulizia forse questi commenti è meglio metterli nella doc di storybook per ora, visto che anche in altri casi stanno là (tipo il Button).

2022-08-23 13:13 UTC, lauratrapani commented on packages/pyxis-scss/src/scss/components/forms/grid.scss
> +  //}
Questo commento credo sia di troppo

2022-08-23 13:13 UTC, lauratrapani commented on packages/pyxis-react/src/stories/components/Form/Overview.tsx
> +import OverviewTemplate from 'stories/utils/OverviewTemplate';
Due cose: 
- di solito quando il componente è implementato in React non mettiamo la lista di classi ma le prop del componente e anche in questo caso farei così, mettendo anche il link a zeroheight alla pagina dei form.
- Questa pagina la farei diventare con le storie integrate, non ha molto senso che ci sia questa overview con le storie in fondo dopo tutti i componenti

2022-08-23 13:13 UTC, lauratrapani commented on packages/pyxis-react/src/stories/components/FormGrid/Overview.tsx
> +    </OverviewTemplate>
Qua aggiungerei la sezione delle classi CSS con il link a zeroheight che tra l'altro per questo componente è sotto Layout.

2022-08-24 07:29 UTC, alessiosantangelo approved these changes

2022-08-24 08:48 UTC, lauratrapani approved these changes

2022-08-24 08:50 UTC, merged