Feature/eslint on storybook stories
primait/pyxis pull request #241
Opened 2022-08-17 10:05 UTC by alessiosantangelo

2022-08-19 15:29 UTC, lauratrapani requested changes

2022-08-19 15:29 UTC, lauratrapani commented on packages/pyxis-react/src/stories/components/Accordion/Overview.stories.mdx
> +---
Questo divider aggiunge effettivamente una linea all'inizio di ogni pagina, è necessario metterlo?

2022-08-19 15:29 UTC, lauratrapani commented on packages/pyxis-react/src/stories/components/DateInput/Overview.tsx
> +        <Story id="components-form-DateInput-all-stories--inside-form-item" />
```suggestion
        <Story id="components-form-dateinput-all-stories--default" />
```
La storia "inside-form-item" non esiste più

2022-08-19 15:29 UTC, lauratrapani commented on packages/pyxis-react/src/stories/components/Input/Overview.tsx
> +        <Story id="components-form-input-all-stories--inside-form-item" />
```suggestion
        <Story id="components-form-input-all-stories--default" />
```

2022-08-19 15:29 UTC, lauratrapani commented on packages/pyxis-react/src/stories/components/Label/Overview.tsx
> +        <Story id="components-form-label-all-stories--inside-form-item" />
```suggestion
        <Story id="components-form-label-all-stories--with-input" />
```

2022-08-19 15:29 UTC, lauratrapani commented on packages/pyxis-react/src/stories/components/Select/Overview.tsx
> +        <Story height="275px" id="components-form-select-all-stories--inside-form-item" />
```suggestion
        <Story height="275px" id="components-form-select-all-stories--with-label" />
```

2022-08-22 06:59 UTC, alessiosantangelo commented on packages/pyxis-react/src/stories/components/Accordion/Overview.stories.mdx
> +---
Purtroppo sì per evitare che il file `mdx` venga interpretato male. 
Il compiler vorrebbe che tutti i tag _siblings_ fossero racchiusi all'interno di un _parent_ ma purtroppo il file `mdx` si rompe se si inseriscono i `React.Fragment`

2022-08-22 07:43 UTC, lauratrapani submitted a review, later dismissed

2022-08-22 07:43 UTC, emanuelemacri commented on packages/pyxis-react/src/stories/components/Accordion/Overview.stories.mdx
> +---
Ok, puoi aggiungere però un:
```
.sbdocs.sbdocs-hr {
    display: none;
}
```
dentro il file `.storybook/manger-head.html`

2022-08-22 07:58 UTC, emanuelemacri requested changes
Ci sono molti casi in cui i testi rimossi sono quelli giusti, probabilmente è andato male qualcosa nel rebase, magari ci do un occhio direttamente io

2022-08-22 07:58 UTC, emanuelemacri commented on packages/pyxis-react/src/stories/components/Button/Overview.tsx
> +        href="https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L2059"
Come mai questi link sono cambiati?
Dovrebbe essere:
```suggestion
       href="https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L2075"
```

2022-08-22 07:58 UTC, emanuelemacri commented on packages/pyxis-react/src/stories/components/Button/Overview.tsx
> +        href="https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L2023"
```suggestion
        href="https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L2039"
```

2022-08-22 07:58 UTC, emanuelemacri commented on packages/pyxis-react/src/stories/components/CheckboxCard/Overview.tsx
> +        <Story id="components-control-checkboxcard-all-stories--default" />
Questo continua a essere
```suggestion
        <Story id="components-control-checkboxcardgroup-all-stories--default" />
```
altrimenti la pagina si rompe non trovando il file

2022-08-22 07:58 UTC, emanuelemacri commented on packages/pyxis-react/src/stories/components/CheckboxCard/Overview.tsx
> +    <OverviewTemplate category="Component" description={overviewDescription} isMain title="Checkbox Card">
```suggestion
    <OverviewTemplate category="Component" description={overviewDescription} isMain title="Checkbox Card Group">
```

2022-08-22 07:58 UTC, emanuelemacri commented on packages/pyxis-react/src/stories/components/Input/Overview.tsx
> +      .
Tutta questa parte è sbagliata, è corretta la versione rimossa (probabilmente nel rebase qualcosa è andato male)

2022-08-22 15:05 UTC, lauratrapani approved these changes

2022-08-22 15:09 UTC, merged