[DS-243]: [Pyxis React] Toggle component
primait/pyxis pull request #247
Opened 2022-08-25 13:07 UTC by alessiosantangelo

https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/DS-243

Add Toggle component.

2022-08-26 13:34 UTC, Gsciarra commented on packages/pyxis-react/src/components/Toggle/Toggle.tsx
> +import { LabelProps } from 'components/Form/Label';
```suggestion
import { LabelProps } from 'components/Form/Label';
```

2022-08-26 13:37 UTC, emanuelemacri requested changes
Alcune cosette

2022-08-26 13:37 UTC, emanuelemacri commented on packages/pyxis-react/src/components/Toggle/Toggle.test.tsx
> +    render(<Toggle id={id} />);
Ora che abbiamo messo il `name` e `value` come obbligatorio si dovrebbe rompere

2022-08-26 13:37 UTC, emanuelemacri commented on packages/pyxis-react/src/components/Toggle/Toggle.tsx
> +);
Aggiungiamo anche la `className` custom
```suggestion
const getClasses = (disabled?: boolean, className?: string) => classNames(
  'toggle',
  {
    'toggle--disabled': disabled,
  },
  className
);
```

2022-08-26 13:37 UTC, emanuelemacri commented on packages/pyxis-react/src/components/Toggle/Toggle.tsx
> +  SyntheticEvent,
Questo mi sa che non lo usiamo più

2022-08-26 13:37 UTC, emanuelemacri commented on packages/pyxis-react/src/components/Toggle/Toggle.tsx
> +        data-testid={id}
```suggestion
        data-testid={inputId}
```

2022-08-26 13:37 UTC, emanuelemacri commented on packages/pyxis-react/src/stories/components/Toggle/Overview.tsx
> +    &nbsp;tag.
Forse qua è meglio scrivere `checkbox` element, invece di tag

2022-08-26 13:37 UTC, emanuelemacri commented on packages/pyxis-react/src/stories/components/Toggle/Toggle.stories.tsx
> +const noArgsTable = { table: { disabled: true } };
Questo può andare via non essendo più un componente di Test, altrimenti viene fuori nel codice di esempio
`Toggle.displayName = 'ToggleTest';`

2022-08-26 13:37 UTC, emanuelemacri commented
Ah @alessiosantangelo va anche esportato il componente in `index.ts`

2022-08-26 13:43 UTC, lauratrapani requested changes

2022-08-26 13:43 UTC, lauratrapani commented on packages/pyxis-react/src/components/Toggle/Toggle.tsx
> +  SyntheticEvent,
Questo non è utilizzato nel file

2022-08-26 13:43 UTC, lauratrapani commented on packages/pyxis-react/src/components/Toggle/Toggle.tsx
> +      {label && React.cloneElement(label, { htmlFor: id })}
La label in questo caso dovrebbe essere sempre size medium e non avere una sublabel, forse è meglio farsi passare direttamente la stringa in questo caso

2022-08-26 13:43 UTC, lauratrapani commented on packages/pyxis-react/src/components/Toggle/Toggle.tsx
> +        aria-label={label ? undefined : 'description'}
`aria-label` dovrebbe essere già nelle default props di Input, e quindi in `restProps`. In ogni caso non deve essere una stringa definita ma deve poter essere passata dallo sviluppatore

2022-08-26 13:43 UTC, lauratrapani commented on packages/pyxis-react/src/components/Toggle/Toggle.tsx
> +  value: string;
perché value è obbligatorio?

2022-08-26 13:43 UTC, lauratrapani commented on packages/pyxis-react/src/stories/components/Toggle/Overview.tsx
>        <Table
La tabella delle classi CSS andrebbe cancellata da qui e messo il link alla doc di Zeroheight

2022-08-26 13:47 UTC, emanuelemacri commented on packages/pyxis-react/src/stories/components/Toggle/Overview.tsx
>        <Table
Si questo lo facciamo in seguito (ci sono anche altri componenti che ancora non ce l'hanno). Facciamoci una card apposita

2022-08-29 08:27 UTC, alessiosantangelo commented
Credo di aver fatto tutti i punti tranne quello delle classi CSS

2022-08-29 08:34 UTC, emanuelemacri approved these changes
LGTM

2022-08-29 08:44 UTC, lauratrapani approved these changes
LGTM

2022-08-29 09:41 UTC, merged