[DS-297]: [Pyxis Elm] Implement Progress Indicator component
primait/pyxis pull request #251
Opened 2022-08-26 16:08 UTC by lauratrapani

https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/DS-297

2022-08-29 13:27 UTC, alessiosantangelo requested changes

2022-08-29 13:27 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Pyxis/Components/ProgressIndicator.elm
> +    Int
Dal momento che non vengono esposti, questi puoi evitarli utilizzando direttamente `Int`

2022-08-29 13:27 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Pyxis/Components/ProgressIndicator.elm
> +withCounterTextTemplate text (Config configuration) =
Eviterei la desinenza `template` visto che trattiamo delle semplici stringhe.

```suggestion
withCounterText : String -> Config -> Config
withCounterText text (Config configuration) =
```

In alternativa anche un più classico `withText` può andare bene così come si fa in altri componenti se non sbaglio

2022-08-29 13:27 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Pyxis/Components/ProgressIndicator.elm
> +            , ( "progress-indicator--left-aligned", alignment == Left )
Credo manchi il caso `alignment == Right`

2022-08-29 13:27 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Pyxis/Components/ProgressIndicator.elm
> +        >> String.replace "$total" (String.fromInt total)
Siamo sicuri che vogliamo fare inserire una qualunque frase? Io sarei più per limitare le possibilità di personalizzazione in questo caso...

2022-08-30 08:29 UTC, emanuelemacri approved these changes
Al netto dei commenti di ale per me è ok

2022-08-30 12:58 UTC, lauratrapani commented on packages/pyxis-elm/src/Pyxis/Components/ProgressIndicator.elm
> +            , ( "progress-indicator--left-aligned", alignment == Left )
non c'è una classe corrispettiva per il `right`

2022-08-30 12:59 UTC, lauratrapani commented on packages/pyxis-elm/src/Pyxis/Components/ProgressIndicator.elm
> +    Int
Forse è meglio che li espongo, così usando `config` esce il suggerimento corretto?

2022-08-30 13:01 UTC, lauratrapani commented on packages/pyxis-elm/src/Pyxis/Components/ProgressIndicator.elm
> +        >> String.replace "$total" (String.fromInt total)
Purtroppo però non mi sono venute altre idee su come gestire il fattore multilingua: dubito che `Step ... of ...` vada bene per tutte le country. Tu avevi in mente qualcosa di preciso?

2022-08-30 14:18 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Pyxis/Components/ProgressIndicator.elm
> +        >> String.replace "$total" (String.fromInt total)
Se dal design non ci sono indicazioni riguardo l'utilizzo dei testi allora lasciamo pure così

2022-08-30 15:16 UTC, alessiosantangelo approved these changes

2022-08-31 08:05 UTC, merged