[DS-239]: [Pyxis React] Autocomplete component
primait/pyxis pull request #253
Opened 2022-08-31 09:48 UTC by lauratrapani

https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/DS-239

2022-09-08 08:37 UTC, alessiosantangelo requested changes

2022-09-08 08:37 UTC, alessiosantangelo commented on packages/pyxis-react/src/commons/hooks/useDropdown.ts
> +    if (mousePosition && x === mousePosition.x && y === mousePosition.y) return;
I think you could write

```suggestion
    if (x === mousePosition?.x && y === mousePosition?.y) return;
```

2022-09-08 08:37 UTC, alessiosantangelo commented on packages/pyxis-react/src/components/Form/Autocomplete/Autocomplete.tsx
> +  onChangeFilteringValue,
We should try to keep consistency between those two attributes.

```suggestion 
onValueChange, 
onFilterValueChange,
```

2022-09-08 08:37 UTC, alessiosantangelo commented on packages/pyxis-react/src/components/Form/Autocomplete/Autocomplete.tsx
> +      );
```suggestion
      setFilteredItems(
         items 
         ? filterItems(filteringValue, filteringFunction, items, isCaseSensitive),
         : undefined
      );
```

2022-09-08 08:37 UTC, alessiosantangelo commented on packages/pyxis-react/src/components/Form/Autocomplete/Autocomplete.tsx
> +      activeDescendant: filteredItems && filteredItems[0] ? filteredItems[0].value : undefined,
This should do the trick:
```suggestion
      activeDescendant: filteredItems && filteredItems[0]?.value
```

2022-09-08 08:37 UTC, alessiosantangelo commented on packages/pyxis-react/src/components/Form/Autocomplete/Autocomplete.tsx
> +  items: Item[] | null | undefined;
Why having an empty array is not enough? I think `null/undefined` can be removed

2022-09-08 09:56 UTC, lauratrapani commented on packages/pyxis-react/src/components/Form/Autocomplete/Autocomplete.tsx
> +  items: Item[] | null | undefined;
The empty array is for when there is no result actually. I also added `null | undefined` for dynamically-loaded items

2022-09-08 13:48 UTC, Gsciarra submitted a review, later dismissed

2022-09-08 13:51 UTC, Gsciarra commented
After Alessio's suggestion, I think the PR is ready to be merged.

2022-09-08 15:50 UTC, brianvanburken commented on packages/pyxis-react/src/commons/hooks/useDropdown.ts
> +        { ...dropdownOld, activeDescendant: items[0] ? items[0].value : undefined }
```suggestion
        { ...dropdownOld, activeDescendant: items[0]?.value }
```

2022-09-08 15:50 UTC, brianvanburken commented on packages/pyxis-react/src/components/Form/Autocomplete/Autocomplete.tsx
> +      );
If `undefined` is allowed you can just write `items && filterItems(filteringValue, filteringFunction, items, isCaseSensitive)`. Since JS statements return the first value if not completed. So if `items` is `undefined` it will return `undefined` :)

2022-09-08 15:50 UTC, brianvanburken commented on packages/pyxis-react/src/components/Form/Autocomplete/Autocomplete.tsx
> +      activeDescendant: filteredItems && filteredItems[0] ? filteredItems[0].value : undefined,
You can shorten it further to `activeDescendant: filteredItems?.[0]?.value`

2022-09-08 15:50 UTC, brianvanburken commented on packages/pyxis-react/src/internalComponents/Dropdown/items.ts
> +  items ? items.find((item) => item.value === value) : undefined
```suggestion
  items?.find((item) => item.value === value)
```

2022-09-08 15:50 UTC, brianvanburken commented on packages/pyxis-react/src/internalComponents/Dropdown/keyDownHandler.ts
> +    activeDescendant: selectedValue || (items && items[0] && items[0].value) || undefined,
```suggestion
    activeDescendant: selectedValue || items?.[0]?.value,
```

2022-09-09 08:51 UTC, emanuelemacri requested changes
some strange behaviour

2022-09-09 08:51 UTC, emanuelemacri commented on packages/pyxis-react/src/components/Form/Select/Select.tsx
> +  const handleKeyDown = keyDownHandler(
when the custom dropdown is open, the 'space' key should select the item (now closes the dropdown)

2022-09-09 08:51 UTC, emanuelemacri commented on packages/pyxis-react/src/components/Form/Select/Select.tsx
> +    value: selectedValue || 'placeholder',
Maybe is better to have an `initialValue` as a props.
In addition, when the component have the `initialValue` the element is not selected in dropdown

2022-09-09 08:51 UTC, emanuelemacri commented on packages/pyxis-react/src/components/Form/Autocomplete/Autocomplete.tsx
> +  suggestion,
Strange behaviour: while there is a suggestion set, if while typing I find `no results` the focus disappears from the input.

2022-09-12 07:28 UTC, alessiosantangelo submitted a review, later dismissed

2022-09-12 07:49 UTC, brianvanburken submitted a review, later dismissed

2022-09-12 13:00 UTC, Gsciarra approved these changes

2022-09-12 13:04 UTC, emanuelemacri approved these changes

2022-09-12 13:23 UTC, merged