[DS-173]: [Pyxis-elm] Implement ButtonCard component
primait/pyxis pull request #258
Opened 2022-09-07 13:43 UTC by brianvanburken

With this PR, I also want to start a discussion: 
The `ButtonCard` now has two "variants", button and anchor. As for now, as with our `Button` component, the user can set "wrong" attributes. For example, the "disabled" attribute on a `ButtonCard` which configured as an anchor. Should we prevent such cases using `CommonContraints` or other techniques in `ButtonCard` and later in `Button`?

2022-09-07 14:12 UTC, emanuelemacri requested changes
a small comment

2022-09-07 14:12 UTC, emanuelemacri commented on packages/pyxis-elm/src/Pyxis/Components/ButtonCard.elm
> +             , ( baseClass ++ "--loading", configuration.loading )
we do not use this approach for classes, but write the extended class, this way it is easier to search within the IDE and do refactoring ;)

2022-09-07 14:23 UTC, alessiosantangelo commented
@brianvanburken I'm always a fan of having a strict control over apis use. IMO we should add these safeguard constraints
.

2022-09-07 14:41 UTC, brianvanburken commented
@alessiosantangelo we discussed with the team, sadly we could not reach you. What we decided is to leave it for now since it would add more complexity to this simple component. As was discussed that even with constrains in place, people could override those.

2022-09-08 08:01 UTC, alessiosantangelo requested changes

2022-09-08 08:01 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Pyxis/Components/ButtonCard.elm
> +withType : Type -> Config msg -> Config msg
I think could be better to have the `Type` argument passed directly to the `config` instead of had to call `withType` separately. 

That's mainly because we already defined a default value (`Button`) for the `type` inside the _initial_ config. Thus the user will never call: 
```elm 
ButtonCard.config "My title" IconSet.User
   |> ButtonCard.withType ButtonCard.button

```

2022-09-09 07:59 UTC, lauratrapani submitted a review, later dismissed
Apart from what was commented by Alessio LGTM

2022-09-09 08:26 UTC, brianvanburken commented on packages/pyxis-elm/src/Pyxis/Components/ButtonCard.elm
> +withType : Type -> Config msg -> Config msg
Check. Would it be nice to expose `ButtonCard.button` and `ButtonCard.link` so you can only setup the type once on init? Then we can keep the `Type` internally

2022-09-09 08:47 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Pyxis/Components/ButtonCard.elm
> +withType : Type -> Config msg -> Config msg
@brianvanburken Your solution is even better than mine, go for it! Thx

2022-09-09 10:03 UTC, alessiosantangelo submitted a review, later dismissed

2022-09-12 08:52 UTC, emanuelemacri requested changes
The PR is ok, but you need to add the component inside the `elm.json` to make it usable from dev

2022-09-12 10:44 UTC, emanuelemacri approved these changes
LGTM 🚀

2022-09-12 10:55 UTC, merged