[DS-332]: [Pyxis React] Text Switch component
primait/pyxis pull request #259
Opened 2022-09-07 14:22 UTC by emanuelemacri

https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/DS-332

## 🚀 New Features
Implementation of TextSwitch component in React
## 📝 Docs
The documentation of the TextSwitch has been updated.

2022-09-08 14:15 UTC, lauratrapani requested changes
Just these small things then it's ok for me

2022-09-09 07:49 UTC, lauratrapani commented on packages/pyxis-react/src/stories/components/TextSwitch/Overview.tsx
> +import Toggle from '../../../components/Toggle';
I think that this one shouldn't be imported :(

2022-09-09 07:57 UTC, lauratrapani submitted a review, later dismissed

2022-09-12 07:27 UTC, alessiosantangelo approved these changes

2022-09-12 13:01 UTC, Gsciarra approved these changes

2022-09-12 13:02 UTC, merged