[PRIMA-12213]: [Pyxis Scss] Implementare la Label
primait/pyxis pull request #26
Opened 2021-12-29 16:38 UTC by emanuelemacri

Add label component in `pyxis-scss`

https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/PRIMA-12213

2021-12-30 10:24 UTC, alessiosantangelo requested changes

2021-12-30 10:24 UTC, alessiosantangelo commented on packages/pyxis-scss/src/scss/components/labels.scss
> +/// @example scss - Use only label
```suggestion
/// @example scss - Simple label
```

2021-12-30 10:24 UTC, alessiosantangelo commented on packages/pyxis-scss/src/scss/components/labels.scss
> +/// @example scss - Use only label with small size
```suggestion
/// @example scss - Simple label with small size
```
```

2021-12-30 10:24 UTC, alessiosantangelo commented on packages/pyxis-scss/src/scss/components/labels.scss
> +/// @example scss - Use label with sub label
```suggestion
/// @example scss - Label with subtext
```

2021-12-30 10:24 UTC, alessiosantangelo commented on packages/pyxis-scss/src/scss/components/labels.scss
> +.label__secondary {
La chiamerei `.label__sub` o `__subtext`. `secondary` da più l'idea di un _modificatore_ invece di _microcomponente_

2021-12-30 10:24 UTC, alessiosantangelo commented on packages/pyxis-scss/src/scss/components/labels.scss
> +  display: grid;
Qui è proprio necessario usare `display: grid`? 
Non ci saranno mai casi in cui il subtext starà a fianco della label principale? 
In questo caso sarebbe un problema, mentre potrebbe essere più semplice aver a che fare con un `display: block`.

2021-12-30 10:42 UTC, emanuelemacri commented on packages/pyxis-scss/src/scss/components/labels.scss
> +  display: grid;
Al momento le label sono previste sempre una sotto l'altra, in questo modo evito di mettere un'altro `display: block` alla `.label__sub`. Nel caso in cui dovranno essere affiancate ci basta aggiungere un modificatore (o classe esterna) che mette la griglia in columns

2021-12-31 08:36 UTC, alessiosantangelo approved these changes

2021-12-31 08:36 UTC, merged