[DS-343]: [Documentation] Update Contribution Page on prima.design
primait/pyxis pull request #263
Opened 2022-09-12 08:57 UTC by pdjota

https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/DS-343

This updates contribution guides after team discussion on scope of contribution

See also the related info in the getting started guide:
https://prima.zeroheight.com/styleguide/s/79372/p/0885af--collaborating-and-contributing/b/22aae3

2022-09-12 09:35 UTC, brianvanburken commented on CONTRIBUTING.md
> +*Pyxis* is a living design system. As such it is in the process of continuous improvement,
```suggestion
*Pyxis* is a living design system. As such, it is in the process of continuous improvement, 
```

2022-09-12 09:35 UTC, brianvanburken commented on CONTRIBUTING.md
> +In all cases team Pyxis is here to help.
```suggestion
In all cases, team Pyxis is here to help.
```

2022-09-12 09:39 UTC, brianvanburken commented on CONTRIBUTING.md
> +Mockups _can be validated with designers_ The _foundations, components and design tokens_ are the basic bricks for building everything.
```suggestion
Mockups _can be validated with designers_ The _foundations, components, and design tokens_ are the basic bricks for building everything.
```

2022-09-12 09:39 UTC, brianvanburken commented on CONTRIBUTING.md
> +Please check our [design site](https://prima.design/3794e337c/p/87a3b6-pyxis) where our documentation lives.
```suggestion
Please check our [design site](https://prima.design/3794e337c/p/87a3b6-pyxis), where our documentation lives.
```

2022-09-12 09:41 UTC, brianvanburken commented on CONTRIBUTING.md
> +Drop by in our slack channel [#team-pyxis](https://prima.slack.com/archives/C02GWSGR14Y) we are always keen to share time with you understanding you point of view, doing pairing.
```suggestion
Drop by our slack channel [#team-pyxis](https://prima.slack.com/archives/C02GWSGR14Y). We always try to share time with you, understand your perspectives, and pair.
```

2022-09-12 09:42 UTC, brianvanburken commented on CONTRIBUTING.md
> +We are happy to discuss the problem/solution and see how it fits it our design system guidelines and if it benefits other Pyxis users we are keen to include it.
```suggestion
We are happy to discuss the problem/solution and see how it fits our design system guidelines, and if it benefits other Pyxis users, we are keen to include it.
```

2022-09-12 09:44 UTC, brianvanburken commented on CONTRIBUTING.md
> +This can happen. When you find a bug in Pyxis please [open an issue in Github](https://github.com/primait/pyxis/issues/new?assignees=&labels=bug%2Ctriage&template=bug_report.yml&title=%5BBug%5D%3A+)
```suggestion
Bugs can happen. When you find a bug in Pyxis, please [open an issue in Github](https://github.com/primait/pyxis/issues/new?assignees=&labels=bug%2Ctriage&template=bug_report.yml&title=%5BBug%5D%3A+) detailing:
```

2022-09-12 09:55 UTC, brianvanburken commented on CONTRIBUTING.md
> +- Device(s) affected: which _browsers, resolutions or devices_ suffer from the bug
```suggestion
- Device(s) affected: which _browsers, resolutions, or devices_ suffer from the bug
```

2022-09-12 09:56 UTC, brianvanburken commented on CONTRIBUTING.md
> +Once you're doing feel free to ping us in our slack channel. We review the bugs periodically.
```suggestion
When done, feel free to ping us on our slack channel. We review the bugs periodically.
```

2022-09-12 09:57 UTC, brianvanburken commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +        If applicable, add screenshots or video to help explain your problem.
```suggestion
        If applicable, add screenshots or a video to help explain your problem.
```

2022-09-12 11:22 UTC, pdjota commented on CONTRIBUTING.md
> +Mockups _can be validated with designers_ The _foundations, components and design tokens_ are the basic bricks for building everything.
that comma is not needed

2022-09-12 11:25 UTC, pdjota commented on CONTRIBUTING.md
> +We are happy to discuss the problem/solution and see how it fits it our design system guidelines and if it benefits other Pyxis users we are keen to include it.
it is not a secondary phrase

2022-09-13 07:38 UTC, brianvanburken submitted a review, later dismissed

2022-09-13 09:04 UTC, emanuelemacri requested changes
A minimal fix (only one period missing)

I do not agree much with the total elimination of the template for 'feature requests. Maybe we can simplify it, but it could be helpful in case of _, for example,_ an API is missing within a component or any DX enhancement is suggested.

What do you say, would you like to bring all these discussions on slack into #team-pyxis?

2022-09-14 08:34 UTC, alessiosantangelo commented on .github/ISSUE_TEMPLATE/feature_request.yml
> -    attributes:
When we'll merge this PR we should also remember to remove the `request a feature` bullet point from [our Notion page](https://www.notion.so/Team-Pyxis-c36a2304069246cd89f8499030340a6e) (yellow box)

2022-09-14 08:36 UTC, alessiosantangelo commented on .github/ISSUE_TEMPLATE/feature_request.yml
> -    attributes:
@pdjota how do you think we should deal with requests about missing api(s)? 
We should ask devs to write only on our public channel or something similar?

2022-09-14 09:28 UTC, pdjota commented on .github/ISSUE_TEMPLATE/feature_request.yml
> -    attributes:
we will reintroduce it with `enhancement_request`

2022-09-14 09:29 UTC, pdjota commented on .github/ISSUE_TEMPLATE/feature_request.yml
> -    attributes:
discussed with @emanuelemacri we decided to use the term enhancement and make the form simpler

2022-09-14 09:51 UTC, emanuelemacri approved these changes

2022-09-14 10:52 UTC, merged