[DS-318]: [Pyxis React] Implement Counter component
primait/pyxis pull request #265
Opened 2022-09-13 09:50 UTC by brianvanburken

https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/DS-318

2022-09-13 11:02 UTC, emanuelemacri requested changes

2022-09-13 12:13 UTC, brianvanburken commented on packages/pyxis-react/src/components/Counter/Counter.tsx
> +  step: number;
I would agree! But, the design states that the step must be given: https://prima.design/3794e337c/p/2407fd-counter/b/87fbdf. I, originally, had set it to 1.

2022-09-13 12:44 UTC, Gsciarra commented on packages/pyxis-react/src/components/Counter/Counter.tsx
> +  step: number;
On the code side, maybe it has more sense to have the default value to 1, with the param as optional.

2022-09-13 13:41 UTC, brianvanburken commented on packages/pyxis-react/src/components/Counter/Counter.tsx
> +  subText?: string;
Would creating a separate type for label not be enough? I see that using `LabelProps` a lot more API is exposed than we would want. Right now I see that it's best for the end-user to only input `text` and `subText` and not more things like size, children etc.

2022-09-13 15:24 UTC, emanuelemacri commented on packages/pyxis-react/src/components/Counter/Counter.tsx
> +  subText?: string;
Ok for now it's ok, but let's call them `label` and `subLabel` please

2022-09-13 15:26 UTC, emanuelemacri commented on packages/pyxis-react/src/components/Counter/Counter.tsx
> +  step: number;
I agree, maybe change it to prima.design as well, it can certainly be different from 1, but nobody forbids us to put it as default

2022-09-14 06:28 UTC, brianvanburken commented on packages/pyxis-react/src/components/Counter/Counter.tsx
> +  step: number;
I've added the default of 1 along with tests and will change the documentation on prima.design

2022-09-14 12:02 UTC, emanuelemacri approved these changes
LGTM

2022-09-14 14:50 UTC, alessiosantangelo approved these changes

2022-09-15 06:25 UTC, merged