[DS-227]: [Pyxis Elm] Tooltip component
primait/pyxis pull request #269
Opened 2022-09-19 10:43 UTC by emanuelemacri

https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/DS-227

2022-09-19 12:27 UTC, brianvanburken commented on packages/pyxis-elm/src/Pyxis/Components/Tooltip.elm
> +config : Variant -> String -> Bool -> Config msg
```suggestion
config : Variant -> CommonsAlias.Id -> CommonsAlias.IsMobile -> Config msg
```

2022-09-19 12:27 UTC, brianvanburken commented on packages/pyxis-elm/src/Pyxis/Components/Tooltip.elm
> +brand : String -> Bool -> Config msg
```suggestion
brand : CommonsAlias.Id -> CommonsAlias.IsMobile -> Config msg
```

2022-09-19 12:27 UTC, brianvanburken commented on packages/pyxis-elm/src/Pyxis/Components/Tooltip.elm
> +neutral : String -> CommonsAlias.IsMobile -> Config msg
```suggestion
neutral : CommonsAlias.Id -> CommonsAlias.IsMobile -> Config msg
```

2022-09-19 12:27 UTC, brianvanburken commented on packages/pyxis-elm/src/Pyxis/Components/Tooltip.elm
> +                    , ( "tooltip--top-left", position == TopLeft )
Would it be nicer to have a separate function that returns these classes based on position? Then you could use a `case` statement and that makes it more clear to read :)

2022-09-19 12:27 UTC, brianvanburken commented on packages/pyxis-elm/src/Pyxis/Components/Tooltip.elm
> +                , CommonsAttributes.ariaDescribedBy "tooltip-id"
Shouldn't `ariaDescribeBy` always receive a unique ID?

2022-09-19 12:27 UTC, brianvanburken commented on packages/pyxis-elm/src/Pyxis/Components/Tooltip.elm
> +    , isMobile : Bool
```suggestion
    , isMobile : CommonsAlias.IsMobile
```

2022-09-19 12:38 UTC, emanuelemacri commented on packages/pyxis-elm/src/Pyxis/Components/Tooltip.elm
> +                , CommonsAttributes.ariaDescribedBy "tooltip-id"
ops, yes 😄

2022-09-22 14:04 UTC, brianvanburken approved these changes

2022-09-22 14:14 UTC, emanuelemacri commented on packages/pyxis-elm/src/Pyxis/Components/Tooltip.elm
> +    , ( "tooltip--top-left", position == TopLeft )
It seems good! Maybe in other PR we can change also the other components 🚀

2022-09-22 14:24 UTC, emanuelemacri commented on packages/pyxis-elm/src/Pyxis/Components/Tooltip.elm
> +    , ( "tooltip--top-left", position == TopLeft )
@brianvanburken for the `Position` is good, but not for `Variant` I think. We use a variant like an initial configuration, and maybe is better to define it manually.
In any case, you can check your tips in this [commit](https://github.com/primait/pyxis/pull/269/commits/c2bfd44c112c362410188aa3a5955a0cd9185000).

2022-09-23 08:23 UTC, brianvanburken approved these changes

2022-09-23 08:27 UTC, alessiosantangelo requested changes

2022-09-23 08:27 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Examples/Form/Update.elm
> +        ShowTooltip isOpen ->
```suggestion
        ShowTooltip tooltipMsg ->
```

2022-09-23 08:27 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Examples/Form/View.elm
> +                            |> Button.withAriaDescribedBy "tooltip-id"
What if we define an `onClick` handler on this button?

2022-09-23 08:27 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Stories/Chapters/Tooltip.elm
> +                    (Button.ghost
We can extract this button definition above given that its definition is the same throughout the file

2022-09-23 08:27 UTC, alessiosantangelo commented on packages/pyxis-react/src/components/TextSwitch/Option.tsx
> +export const getOptionId = (name: string, value: string): string => `${name}-${value}-option`;
Is that a missing rebase from master? 🤔

2022-09-23 10:54 UTC, emanuelemacri commented on packages/pyxis-elm/src/Examples/Form/View.elm
> +                            |> Button.withAriaDescribedBy "tooltip-id"
I put a default trigger in the last commit, so as to avoid this problem. But if someone wants to use a `customTrigger` with an `onClick` event inside, two events will be triggered. It is not recommended, but possible

2022-09-23 10:58 UTC, emanuelemacri commented on packages/pyxis-react/src/components/TextSwitch/Option.tsx
> +export const getOptionId = (name: string, value: string): string => `${name}-${value}-option`;
Nope, it is a fix, this function caused a circular dependency warning

2022-09-23 10:59 UTC, emanuelemacri commented on packages/pyxis-elm/src/Stories/Chapters/Tooltip.elm
> +                    (Button.ghost
yes, I did something similar in the last commit.

2022-09-23 13:22 UTC, Gsciarra commented on packages/pyxis-elm/src/Examples/Form/Update.elm
> +            Model.updateTooltip isOpen model
This is no longer a boolean
```suggestion
        TooltipMsg internalMsg ->
            Model.updateTooltip internalMsg model
```

2022-09-23 13:22 UTC, Gsciarra commented on packages/pyxis-elm/src/Pyxis/Components/Tooltip.elm
> +update msg (Model _) =
```suggestion
update msg _ =
```

2022-09-26 07:34 UTC, lauratrapani submitted a review, later dismissed

2022-09-26 09:13 UTC, brianvanburken submitted a review, later dismissed
LGTM

2022-09-26 10:11 UTC, alessiosantangelo approved these changes

2022-09-26 10:14 UTC, merged