[DS-344]: Create a POC about having Elmbook documentation automatically built by using docs.json file
primait/pyxis pull request #271
Opened 2022-09-20 08:33 UTC by alessiosantangelo

https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/DS-344

Tries to autogenerate Elmbook examples by using Elm's docs.json as source of truth.

2022-10-21 07:57 UTC, lauratrapani reviewed
Just a question

2022-10-21 07:57 UTC, lauratrapani commented on packages/pyxis-elm/src/Stories/Api/ProgressIndicator.elm
> +    ProgressIndicator.config 0 0
Why is this configured with 0 instead of 1? Would it be possible for this case to have two different numbers?

2022-10-21 10:27 UTC, emanuelemacri requested changes
I don't have much to say about the parser, but perhaps before merging we should make some changes to bring the currently online documentation somewhat in line with these. Also because there are really two different ways of reading the documentation at the moment)

2022-10-21 10:27 UTC, emanuelemacri commented on packages/pyxis-elm/src/Stories/Api/Badge.elm
> +
Before merging, we should see if we can align this documentation with what is online. For example: is it possible to add a description of the component at the top of the page? We could make an 'intro' function exactly like we do with the final part with the link to the classes

2022-10-21 10:27 UTC, emanuelemacri commented on packages/pyxis-elm/src/Stories/Api/Badge.elm
> +    Badge.action "Lorem ipsum"
Is it possible (not only here, but in all examples) to add rendering as well? Ideally these docs should be copy and paste.

```suggestion
action : Badge.Config
action =
    Badge.action "Lorem ipsum"
      |> Badge.render
```

2022-10-21 10:27 UTC, emanuelemacri commented on packages/pyxis-elm/src/Stories/Api/ProgressIndicator.elm
> +    ProgressIndicator.config 0 0
+1

2022-10-24 08:25 UTC, brianvanburken commented on packages/pyxis-elm/src/Stories/Api/Badge.elm
> +
It doesn't have this option right now. One thing I was thinking of is using the main documentation (the one on top) as a way to build the elmbook. Then each `@docs ...` would be replaced by a generated example. This would require more refactoring and a change of approach. It would allow us to structure the elmbook output more manually. Let me know what you think. Would the missing intro be a dealbreaker?

2022-10-24 08:38 UTC, Gsciarra commented on packages/pyxis-elm/src/Stories/Api/Badge.elm
> +
Unfortunately, it is. If we generate new documentation without the description, it's like a regression. I like the idea of adding a custom part, but I would not change the `@docs` part. If in the future we will release the package, we will be forced to choose between our custom doc or the package one.

2022-10-24 08:45 UTC, emanuelemacri commented on packages/pyxis-elm/src/Stories/Api/Badge.elm
> +
yes but I think it's simple no? We already add custom content with the `Utils.withCssDocToDesignDocumentation` function, we should do the same for the intro right?

2022-10-24 09:09 UTC, brianvanburken commented on packages/pyxis-elm/src/Stories/Api/Badge.elm
> +
Yes, we can add manually to this documentation in our `Chapter`s. It would be nice if we didn't need to add much manually later. This is part of the succeeding tickets

2022-10-24 09:10 UTC, brianvanburken commented on packages/pyxis-elm/src/Stories/Api/Badge.elm
> +    Badge.action "Lorem ipsum"
This generated so I will find a way to add it

2022-10-24 09:11 UTC, brianvanburken commented on packages/pyxis-elm/src/Stories/Api/ProgressIndicator.elm
> +    ProgressIndicator.config 0 0
I'll look into it. For now, it looks like it selected this, as it can't assume anything yet. It just sees `Int` and fill in 0 as it doesn't know context

2022-10-24 14:51 UTC, Gsciarra approved these changes

2022-10-24 14:52 UTC, emanuelemacri approved these changes
LGTM

2022-10-24 14:55 UTC, merged