[DS-350]: [Pyxis Scss/React] Add to component Label the possibility to hold a Tooltip
primait/pyxis pull request #272
Opened 2022-09-20 15:34 UTC by lauratrapani

https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/DS-350

2022-09-21 12:37 UTC, brianvanburken commented
Should we also add a Storybook story where the tooltip is open by default? Our visual regression testing, using Storybook, does not do much now since the tooltip is hidden.

2022-09-21 15:02 UTC, lauratrapani commented
> Should we also add a Storybook story where the tooltip is open by default? Our visual regression testing, using Storybook, does not do much now since the tooltip is hidden.

Added a test with the tooltip open in desktop view. For the moment the mobile unfortunately can't be tested.

2022-09-22 13:40 UTC, emanuelemacri requested changes
Just a small change for me

2022-09-22 13:40 UTC, emanuelemacri commented on packages/pyxis-react/src/components/Tooltip/Tooltip.tsx
> +  customTrigger?: ReactElement;
only `trigger` is better for me

2022-09-23 08:23 UTC, alessiosantangelo requested changes

2022-09-23 08:23 UTC, alessiosantangelo commented on packages/pyxis-react/.eslintrc.js
> +        extensions: ['.js', '.jsx', '.ts', '.tsx'],
Is it correct to have also `ts, tsx` here?

2022-09-23 08:23 UTC, alessiosantangelo commented on packages/pyxis-react/package.json
> +    "pretest": "yarn storybook:build",
Defining this command will cause the CI to build our application twice!

2022-09-23 08:23 UTC, alessiosantangelo commented on packages/pyxis-react/src/components/Tooltip/Tooltip.test.tsx
> +  test.each(positions)(
Better to not use cycles in testing

2022-09-23 08:23 UTC, alessiosantangelo commented on packages/pyxis-react/src/components/Tooltip/Tooltip.tsx
> +          onClick: () => isMobile && setIsVisible(true),
We can move these check before the return instruction. They're defined twice

2022-09-23 08:23 UTC, alessiosantangelo commented on packages/pyxis-react/src/components/Tooltip/Tooltip.tsx
> +  customTrigger?: ReactElement;
```suggestion
  trigger?: ReactElement;
```

2022-09-23 15:48 UTC, lauratrapani commented on packages/pyxis-react/src/components/Tooltip/Tooltip.test.tsx
> +  test.each(positions)(
[This card ](https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/DS-378/Pyxis-React)has been created to solve the same problem in all components at once.

2022-09-26 06:02 UTC, brianvanburken approved these changes

2022-09-26 07:28 UTC, brianvanburken approved these changes

2022-09-26 07:33 UTC, emanuelemacri approved these changes
LGTM

2022-09-26 08:32 UTC, merged