[DS-360]: [Pyxis Documentation] Add Autocomplete code documentation on Zeroheight
primait/pyxis pull request #274
Opened 2022-09-22 07:08 UTC by brianvanburken

https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/DS-360

2022-09-22 07:26 UTC, lauratrapani commented on packages/pyxis-react/src/stories/components/Autocomplete/Overview.tsx
> +    The list of Texts CSS classes is available&nbsp;
```suggestion
    The list of Autocomplete CSS classes is available&nbsp;
```

2022-09-22 07:29 UTC, lauratrapani commented
Also, the label and description of the PR are missed

2022-09-22 07:42 UTC, emanuelemacri requested changes
in addition to laura's comments: before merging PR you have to finish the documentation on zeroheight. ;)

2022-09-22 07:42 UTC, emanuelemacri commented on packages/pyxis-react/src/stories/components/Autocomplete/Overview.tsx
> +      href="https://prima.design/3794e337c/p/26b9e3-autocomplete"
we generally use the direct link to the 'code' tab
```suggestion
      href="https://prima.design/3794e337c/p/26b9e3-autocomplete/b/54df21"
```

2022-09-26 07:29 UTC, lauratrapani approved these changes

2022-09-26 07:34 UTC, emanuelemacri approved these changes
LGTM

2022-09-26 07:34 UTC, merged