[DS-354]: [Pyxis React] Split FormGrid in Grid and FormGrid
primait/pyxis pull request #276
Opened 2022-09-22 15:44 UTC by lauratrapani

https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/DS-354

2022-09-23 07:46 UTC, emanuelemacri requested changes

2022-09-23 07:46 UTC, emanuelemacri commented on packages/pyxis-react/src/components/FormGrid/FormGrid.tsx
> +      <Grid>
The rowgap for fields is missing
```suggestion
      <Grid rowGap='medium'>
```

2022-09-23 08:18 UTC, alessiosantangelo requested changes
Some tips: 
- always start tests with `should` instead of `with/when`. Test descriptions should define what response we expect
- do not test cycles, be imperative

2022-09-23 08:18 UTC, alessiosantangelo commented on packages/pyxis-react/src/components/FormGrid/FormGrid.test.tsx
> +  test('can have a `Header` with the correct structure', () => {
```suggestion
  test('should contain an `Header` with the correct markup', () => {
```

2022-09-23 08:18 UTC, alessiosantangelo commented on packages/pyxis-react/src/components/FormGrid/FormGrid.test.tsx
> +  test('can have a `Content` with the correct structure', () => {
```suggestion
  test('should have a `Content` with the correct markup', () => {
```

2022-09-23 08:18 UTC, alessiosantangelo commented on packages/pyxis-react/src/components/FormGrid/FormGrid.test.tsx
> +  test('can have a `Footer` with the correct structure', () => {
```suggestion
  test('should have a `Footer` with the correct markup', () => {
```

2022-09-23 08:18 UTC, alessiosantangelo commented on packages/pyxis-react/src/components/Grid/Col/Col.test.tsx
> +  );
Testing a cycle is often an anti-pattern.

2022-09-23 08:18 UTC, alessiosantangelo commented on packages/pyxis-react/src/components/Grid/Col/Col.test.tsx
> +  test('with default configuration it should mount with default classes', () => {
Test should start with `should`

2022-09-23 08:18 UTC, alessiosantangelo commented on packages/pyxis-react/src/components/Grid/Grid.test.tsx
> +  test('with default configuration it should mount with default classes', () => {
```suggestion
  test('should have the correct markup when used with default configuration', () => {
```

2022-09-23 08:18 UTC, alessiosantangelo commented on packages/pyxis-react/src/components/Grid/Grid.test.tsx
> +  test('with large gap', () => {
```suggestion
  test('should have a large Gap', () => {
```

2022-09-23 09:09 UTC, emanuelemacri commented on packages/pyxis-react/src/components/Grid/Col/Col.test.tsx
> +  );
how? We do this in many cases where there are many variants to check

2022-09-23 10:37 UTC, Gsciarra commented on packages/pyxis-react/src/index.ts
> +export { default as FormGrid } from './components/Grid';
Add `export { default as Grid } from './components/Grid';`

2022-09-23 13:24 UTC, Gsciarra approved these changes

2022-09-23 15:47 UTC, lauratrapani commented on packages/pyxis-react/src/components/Grid/Col/Col.test.tsx
> +  );
[This card ](https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/DS-378/Pyxis-React) has been created to solve the same problem in all components at once.

2022-09-26 07:41 UTC, emanuelemacri approved these changes
LGTM

2022-09-26 09:06 UTC, alessiosantangelo approved these changes

2022-09-26 09:08 UTC, brianvanburken approved these changes
LGTM :rocket:

2022-09-26 09:08 UTC, merged