[DS-361]: [Pyxis Documentation] Add Counter code documentation on Zeroheight
primait/pyxis pull request #277
Opened 2022-09-23 14:49 UTC by brianvanburken

https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/DS-361

2022-09-23 15:37 UTC, lauratrapani requested changes

2022-09-23 15:37 UTC, lauratrapani commented on packages/pyxis-react/src/stories/components/Counter/Overview.tsx
> +    The list of Autocomplete CSS classes is available&nbsp;
```suggestion
    The list of Counter CSS classes is available&nbsp;
```

2022-09-26 05:46 UTC, brianvanburken commented on packages/pyxis-react/src/stories/components/Counter/Overview.tsx
> +    The list of Autocomplete CSS classes is available&nbsp;
I'm sorry for making such a dumb copy-paste error :man_facepalming:

2022-09-26 07:28 UTC, lauratrapani approved these changes

2022-09-26 07:35 UTC, emanuelemacri approved these changes
LGTM

2022-09-26 07:35 UTC, merged