[PRIMA-12214]: [Pyxis Elm] Implementare la Label
primait/pyxis pull request #28
Opened 2022-01-05 08:25 UTC by lauratrapani

https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/PRIMA-12214

Label module (pyxis-elm)

2022-01-05 09:53 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Label.elm
> +configurationToHtmlAttributes : Configuration -> List (Html.Attribute msg)
Lascerei `CommonsAttributes.compose` direttamente dentro il render così da avere tutto assieme.

2022-01-05 09:53 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Label.elm
> +withClass class (Model configuration) =
Direi che `withClass` ce lo possiamo risparmiare avendo già `withClassList`. Inoltre non vogliamo incoraggiare il passaggio di classi extra sui nostri componenti

2022-01-05 09:53 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Label.elm
> +@docs withClass, withClassList, withFor, withId, withSizeSmall, withSubText
Teniamo gli exposings in verticale visto che avevamo avuto problemi di leggibilità sul vecchio Pyxis.
```suggestion
@docs withClassList
@docs withFor
@docs withSizeSmall
@docs withSubText
```

2022-01-05 09:53 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Label.elm
> +        , id = Nothing
L'`id` sulla labe non ha molto senso. Sarebbe invece meglio rendere obbligatorio il `for`.

2022-01-05 09:53 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Label.elm
> +        , small = False
Gestirlo come un `type Size` è più coerente rispetto agli altri componenti e più elegante. Inoltre ci permette di tenere in ordine gli exposings con una cosa di questo tipo: 
```
## MyUnionType 
@docs MyUnionType
@docs withMyUnionTypeValue1
@docs withMyUnionTypeValue2
@docs withMyUnionTypeValue3
```

2022-01-05 09:53 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Label.elm
> +import Commons.Render as CommonsRender
```suggestion
import Commons.Attributes as CA
import Commons.Render as CR
```

2022-01-05 09:53 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Button.elm
> +    , withTypeSubmit
Prossima volta meglio fare questo tipo di modifiche in un branch a parte, non è necessario usare suite-py se rompe le scatole :)

2022-01-05 10:17 UTC, Gsciarra commented on packages/pyxis-elm/src/Components/Label.elm
> +        , id = Nothing
L'`id` l'abbiamo messo più che altro per generare il `data-test-id`

2022-01-05 15:26 UTC, Gsciarra requested changes

2022-01-05 15:26 UTC, Gsciarra commented on packages/pyxis-elm/src/Components/Label.elm
> +@docs render
Manca `create`

2022-01-05 15:26 UTC, Gsciarra commented on packages/pyxis-elm/src/Components/Label.elm
> +    Model { configuration | classList = configuration.classList ++ classList }
Ora che abbiamo un solo modo per aggiungere le classi, ha meno senso fare la concatenazione. Allineiamo l'implementazione alle altre:

```suggestion
withClassList : List ( String, Bool ) -> Model -> Model
withClassList classList (Model configuration) =
    Model { configuration | classList = classList }
```

2022-01-05 15:44 UTC, Gsciarra approved these changes

2022-01-10 08:09 UTC, alessiosantangelo requested changes

2022-01-10 08:09 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Label.elm
> +create : { text : String, for : String } -> Model
Usiamo questa firma invece che il record:
```suggestion
create : String -> String -> Model
create lbl for = 
```

Così manteniamo coerenza con il builder pattern.

2022-01-10 08:09 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Label.elm
> +            |> Label.withClassList [("my-label-class": True), ("another-class": True)]
```suggestion
            |> Label.withClassList [("my-label-class", True), ("another-class", True)]
```

2022-01-10 08:09 UTC, alessiosantangelo commented on packages/pyxis-elm/tests/Components/LabelTest.elm
> +        , describe "Size small"
```suggestion
        , describe "Size"
```

2022-01-10 08:09 UTC, alessiosantangelo commented on packages/pyxis-elm/tests/Components/LabelTest.elm
> +            [ test "has correct class" <|
```suggestion
            [ test "is small" <|
```

2022-01-10 08:09 UTC, alessiosantangelo commented on packages/pyxis-elm/tests/Components/LabelTest.elm
> +        [ describe "Base"
```suggestion
        [ describe "Default"
```

2022-01-10 08:09 UTC, alessiosantangelo commented on packages/pyxis-elm/tests/Components/LabelTest.elm
> +            [ test "has correct label and for attributes" <|
```suggestion
            [ test "has a textual content and a for attribute" <|
```

2022-01-10 08:09 UTC, alessiosantangelo commented on packages/pyxis-elm/tests/Components/LabelTest.elm
> +                        |> Query.has [ classes [ "label" ] ]
Questo è un po' ridondante, si può testare nella riga sopra

2022-01-10 08:09 UTC, alessiosantangelo commented on packages/pyxis-elm/tests/Components/LabelTest.elm
> +                            ]
```suggestion
                            [ text "My label"
                            , attribute (Html.Attributes.for "inputId")
                            , classes [ "label" ]
                            ]
```

2022-01-10 08:09 UTC, alessiosantangelo commented on packages/pyxis-elm/tests/Components/LabelTest.elm
> +            [ test "has a small tag with correct class" <|
```suggestion
            [ test "creates a 'small' tag" <|
```

2022-01-10 08:09 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Label.elm
> +        , id = Nothing
Visto che però il campo `for` è obbligatorio, possiamo fare in modo che a partire dal valore di `for` venga generato _sempre_ l'attributo `data-test-id` con nomenclatura fissa. 
Es. 
```
label.create { text "Lorem ipsum, for = 'field_id' }
--->
data-test-id="fieldIdLabel"
```
(ovvero in camel case con desinenza fissa `label`).

Questo ci serve per stabilire una convenzione all'interno dello stesso Pyxis così che sia coerente anche sul resto degli applicativi.

2022-01-10 09:55 UTC, alessiosantangelo requested changes

2022-01-10 09:55 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Commons/Utils/StringUtils.elm
> +module Commons.Utils.StringUtils exposing
```suggestion
module Commons.Utils.String exposing
```

2022-01-10 09:55 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Commons/Utils/StringUtils.elm
> +        |> String.join ""
```elm
kebabToCamelCase : String -> String
kebabToCamelCase str =
    case String.split "-" str of 
       head :: tail -> 
          tail |> List.map capitalize |> (::) head |> String.join ""
       _ -> 
         str
```

2022-01-10 09:55 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Label.elm
> +        Label.create "My custom label" "inputId" }
C'è un `}` di troppo

2022-01-10 09:55 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Label.elm
> +        Label.create "My custom label" "inputId" }
Idem

2022-01-10 09:55 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Label.elm
> +        Label.create "My custom label" "inputId" }
Idem

2022-01-10 09:57 UTC, Gsciarra commented on packages/pyxis-elm/src/Commons/Utils/StringUtils.elm
> +module Commons.Utils.StringUtils exposing
Potremmo rimpiazzarlo con [String Extra](https://package.elm-lang.org/packages/elm-community/string-extra/latest/String-Extra)

2022-01-10 09:57 UTC, Gsciarra commented on packages/pyxis-elm/src/Commons/Utils/StringUtils.elm
> +        |> String.join ""
`StringExtra.camelize`

2022-01-10 09:57 UTC, Gsciarra commented on packages/pyxis-elm/src/Commons/Utils/StringUtils.elm
> +    String.toUpper (String.left 1 string) ++ String.dropLeft 1 string
Se serve per una singola parola, può essere sostituita con `StringExtra.toTitleCase`

2022-01-10 10:10 UTC, Gsciarra commented on packages/pyxis-elm/src/Components/Label.elm
> +import Commons.Render as CommonsRender
@alessiosantangelo non sarebbe meglio evitare le sigle? Come regola generale intendo

2022-01-10 10:39 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Commons/Utils/StringUtils.elm
> +module Commons.Utils.StringUtils exposing
Se ci sono tutte le funzioni di cui abbiamo bisogno va bene :)

2022-01-10 16:58 UTC, Gsciarra approved these changes

2022-01-11 09:30 UTC, emanuelemacri approved these changes
LGTM

2022-01-11 11:54 UTC, alessiosantangelo approved these changes

2022-01-11 11:55 UTC, merged