[DS-371]: [Pyxis Elm] Split Grid in Grid and FormGrid
primait/pyxis pull request #286
Opened 2022-10-03 07:23 UTC by brianvanburken

https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/DS-371

2022-10-03 12:24 UTC, emanuelemacri submitted a review, later dismissed
Some questions

2022-10-03 12:24 UTC, emanuelemacri commented on packages/pyxis-elm/src/Pyxis/Components/Grid.elm
> +            ( "grid__row--from-xlarge", True )
Wouldn't it be better to have a function that only returns a string?
And then change where you use it to:
```
( getRowColumnsFromClass configuration.breakpoint, True )
```
seems cleaner to me, what do you think?

2022-10-03 12:24 UTC, emanuelemacri commented on packages/pyxis-elm/src/Pyxis/Components/Form/FormGrid.elm
> +{-| Creates a FormGrid.
It's ok renaming this file, but maybe we can write here and in the documentation that `FormGrid` create a `fieldset` automatically inside.

2022-10-03 12:24 UTC, emanuelemacri commented on packages/pyxis-elm/src/Stories/Book.elm
>                  , Loader.docs
Thanks for ordering 😃

2022-10-03 12:24 UTC, emanuelemacri commented on packages/pyxis-elm/src/Stories/Chapters/Form.elm
> +Grid element is used to group several controls as well as labels within a web form.
I think is better to separate the documentation in `Grid` and `FormGrid`, like [react documentation](https://react-staging.prima.design/?path=/story/components-layout-grid-overview--page)

2022-10-03 12:32 UTC, brianvanburken commented on packages/pyxis-elm/src/Pyxis/Components/Grid.elm
> +            ( "grid__row--from-xlarge", True )
I agree that it is better! Thanks! :)

2022-10-03 13:53 UTC, lauratrapani approved these changes
a part from Emanuele's comments LGTM

2022-10-04 07:30 UTC, lauratrapani requested changes

2022-10-04 07:30 UTC, lauratrapani commented on packages/pyxis-elm/src/Stories/Chapters/Form.elm
> +## Grid
```suggestion
## FormGrid
```

2022-10-04 07:30 UTC, lauratrapani commented on packages/pyxis-elm/src/Stories/Chapters/Form.elm
> +Grid element is used to group several controls as well as labels within a web form.
```suggestion
The FormGrid element is an enabler for building a correct layout for forms as it let the user easily paginate the header, content and footer with the proper gap and space.
```

2022-10-04 07:30 UTC, lauratrapani commented on packages/pyxis-elm/src/Stories/Chapters/Form.elm
> +Every form grid is composed by three (optional) macro area: `header`, `content` and `footer`.
```suggestion
Every FormGrid exposes in fact three (optional) wrappers: `withHeader`, `withContent` and `withFooter`. Inside them, the user could use the Grid component to divide content into rows and columns.
```

2022-10-04 07:30 UTC, lauratrapani commented on packages/pyxis-elm/src/Stories/Chapters/Grid.elm
> +Form Row is used to define the width of grid and to group the columns inside it.
```suggestion
The Row component is used to define the width of the grid and to group the columns inside it.
```

2022-10-04 07:30 UTC, lauratrapani commented on packages/pyxis-elm/src/Stories/Chapters/Grid.elm
> +
I think that you should write something about the Grid itself as it can be customized through different gaps

2022-10-04 07:31 UTC, emanuelemacri requested changes

2022-10-04 07:31 UTC, emanuelemacri commented on packages/pyxis-elm/src/Stories/Chapters/Grid.elm
> +Form Row is used to define the width of grid and to group the columns inside it.
```suggestion
Row is used to define the width of grid and to group the columns inside it.
```

2022-10-04 07:31 UTC, emanuelemacri commented on packages/pyxis-elm/src/Stories/Chapters/Form.elm
> +Grid element is used to group several controls as well as labels within a web form.
This is a FormGrid element
```suggestion
## FormGrid
FormGrid element is used to group several controls as well as labels within a web form.
```

2022-10-04 07:31 UTC, emanuelemacri commented on packages/pyxis-elm/src/Stories/Chapters/Grid.elm
> +        |> ElmBook.Chapter.render """
In this file there is no `Grid` specification if someone wants to make a 'non-form' grid

2022-10-04 07:38 UTC, brianvanburken commented on packages/pyxis-elm/src/Stories/Chapters/Grid.elm
> +        |> ElmBook.Chapter.render """
Can you explain me more precisely? I see only a few references to forms, but in general, it talks about setting up rows and columns

2022-10-04 09:08 UTC, lauratrapani submitted a review, later dismissed

2022-10-04 09:19 UTC, emanuelemacri submitted a review, later dismissed
LGTM

2022-10-04 09:26 UTC, Gsciarra requested changes

2022-10-04 09:26 UTC, Gsciarra commented on packages/pyxis-elm/src/Pyxis/Components/Grid/SpanSize.elm
> +spanSizeToInt spanSize =
```suggestion
toInt : SpanSize -> Int
toInt spanSize =
```
In this way it can be used like this `SpanSize.toInt`. In general, Elm libraries use this approach.

2022-10-04 09:26 UTC, Gsciarra commented on packages/pyxis-elm/src/Pyxis/Components/Grid/SpanSize.elm
> +spanSizeToString =
```suggestion
toString : SpanSize -> String
toString =
```

2022-10-04 09:32 UTC, emanuelemacri approved these changes
LGTM

2022-10-04 09:33 UTC, lauratrapani approved these changes

2022-10-04 09:33 UTC, Gsciarra approved these changes

2022-10-04 09:52 UTC, merged