[PRIMA-12188]: [Pyxis Scss] Implement the Text Field
primait/pyxis pull request #29
Opened 2022-01-11 11:10 UTC by lauratrapani

https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/PRIMA-12188

CSS classes for text input styling.

2022-01-11 11:52 UTC, emanuelemacri approved these changes
Ho ancora un po' di dubbi sui mixin base dei field (in `form/utils.scss`), ma per ora direi che possiamo lasciarli così e nel caso passare a delle classi nell'implementazione dei prossimi componenti, così capiamo meglio i casi.
cc/ @alessiosantangelo

2022-01-11 12:06 UTC, alessiosantangelo requested changes
Modificherei un po' di cose, se vuoi possiamo vedere assieme la review per confrontarci a voce.

2022-01-11 12:06 UTC, alessiosantangelo commented on packages/pyxis-scss/src/scss/components/form/textField.scss
> +///    <div class="text-field">
Alcune cose: 
- l'`input` dovrebbe potersi utilizzare senza `label`, quindi quest'ultima non deve fare parte dell'html necessario per costruire il field
- la classe `text-field` viene assegnata a quello che in realtà è un wrapper dell'input, il che è un po' misleading
- è strettamente necessario avere tutto questo html per produrre un semplice campo di testo?

2022-01-11 12:06 UTC, alessiosantangelo commented on packages/pyxis-scss/src/scss/components/form/textField.scss
> +.text-field {
Sarebbe ottimale trovare per _tutti i componenti di `form/fields`_ una struttura comune che riguardi i wrapper e il posizionamento dei campi. 

In questo modo si può stabilire che: 
- tutti i campi hanno bisogno di un wrapper (TBD)
- il wrapper si comporta allo stesso modo per tutti i fields
- ogni fields conosce solo le sue logiche di rendering e posizionamento all'interno del parent

2022-01-11 12:06 UTC, alessiosantangelo commented on packages/pyxis-scss/src/scss/components/form/textField.scss
> +  }
Queste due classi dovrebbero voler indicare che il `text-field` HA un'icona, invece sembra che queste classi abbiano effetto direttamente sull'icona stessa. 
Forse `text-field--has-trailing-icon` è più parlante

2022-01-11 12:06 UTC, alessiosantangelo commented on packages/pyxis-scss/src/scss/components/form/utils.scss
> +  &__error-message {
Ha senso che `error-message` non sia un componente globale ma abbia una forma potenzialmente diversa per ogni field? 
Secondo me dovrebbe essere un'entità a parte.

2022-01-12 10:52 UTC, emanuelemacri approved these changes

2022-01-12 15:01 UTC, merged