[DS-424]: [Pyxis React] Expose all the interfaces used to type props
primait/pyxis pull request #310
Opened 2022-10-20 13:48 UTC by emanuelemacri

https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/DS-424

# ✨ Enhancements
Export internal component types

2022-10-21 13:14 UTC, Gsciarra submitted a review, later dismissed

2022-10-21 13:18 UTC, lauratrapani requested changes
Just small things

2022-10-21 13:18 UTC, lauratrapani commented on packages/pyxis-react/src/components/Button/index.ts
> +  ButtonProps, ButtonSize, ButtonVariant, ButtonContentProps, ButtonIconPlacement,
Is necessary to export `ButtonContentProp`? It should be used only in an non-exposed component

2022-10-21 13:18 UTC, lauratrapani commented on packages/pyxis-react/src/components/Grid/Col/index.ts
> +export type { ColProps, GridColSpan } from './Col';
If the first is `ColProps` I think that also the second should be just `ColSpan`

2022-10-21 13:18 UTC, lauratrapani commented on packages/pyxis-react/src/components/Grid/Row/Row.tsx
> +  columnsFrom?: GridRowBreakpoint,
The same as the `Col`

2022-10-21 13:18 UTC, lauratrapani commented on packages/pyxis-react/src/components/TextSwitch/TextSwitch.tsx
> +export interface TextSwitchSliderPosition {
This is just used in the `useState`, so it should be internal

2022-10-21 13:18 UTC, lauratrapani commented on packages/pyxis-react/src/internalComponents/ControlGroup/index.ts
> +export type {
Maybe it's better to export them with a proper alias from `RadioGroup`, `RadioCardGroup` and so on

2022-10-24 13:40 UTC, Gsciarra approved these changes

2022-10-24 13:49 UTC, lauratrapani approved these changes

2022-10-24 13:53 UTC, merged