[DS-426]: [Pyxis React] Make the label required for field components
primait/pyxis pull request #311
Opened 2022-10-21 10:37 UTC by lauratrapani

https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/DS-426

2022-10-24 07:31 UTC, lauratrapani commented on packages/pyxis-scss/src/scss/base/_a11y.scss
> +.sr-only:not(:focus):not(:active) {
Not to save bites but just because it's a conventional name for that class. And then yes, it's shorter.

2022-10-24 08:13 UTC, brianvanburken submitted a review, later dismissed

2022-10-24 08:23 UTC, Gsciarra approved these changes

2022-10-24 10:18 UTC, brianvanburken approved these changes

2022-10-24 12:25 UTC, emanuelemacri requested changes

2022-10-24 12:25 UTC, emanuelemacri commented on packages/pyxis-react/src/hoc/withFormItem/withFormItem.tsx
> +  hideLabel?: boolean;
Maybe is better to use directly `isLabelHidden` ?

2022-10-24 12:25 UTC, emanuelemacri commented on packages/pyxis-react/src/components/Toggle/Toggle.tsx
> +  hideLabel?: boolean;
same

2022-10-24 13:28 UTC, lauratrapani commented on packages/pyxis-react/src/hoc/withFormItem/withFormItem.tsx
> +  hideLabel?: boolean;
`isLabelHidden` has the syntax of a question, maybe it's better `isHiddenLabel`?

2022-10-24 14:53 UTC, emanuelemacri submitted a review, later dismissed
LGTM

2022-10-24 15:50 UTC, 70el approved these changes
Thanks for making this change!

2022-10-24 15:50 UTC, 70el commented on packages/pyxis-react/src/components/Toggle/Toggle.test.tsx
> +    const label = screen.getByTestId(`${name}-label-wrapper`);
An alternative here would be to use accessible role queries to test the hidden presentation, for example:
```jsx
const input = screen.getByLabelText(/label/i);
expect(input).toBeVisible(); // verifies the label is associated with the input
const label = screen.getByText(/label/i);
expect(label).not.toBeVisible(); // verifies the text is present, but not visible
```

This more closely resembles the way the user interacts with the components, and means if the underlying implementation changes (e.g. we change the `sr-only` class name), the tests continue to pass.

2022-10-24 15:50 UTC, 70el commented on packages/pyxis-react/src/hoc/withFormItem/ItemLabel.tsx
> +  isHidden?: boolean;
👍

There's a third scenario - where a visible label exists on the page, and we want to provide its `id` to a Pyxis component via `aria-labelledby`. This will probably be most applicable to inline Inputs, Checkboxes and Switches that are embedded within larger components (e.g. a table.) Happy for us to defer this until it's needed.

2022-10-25 07:36 UTC, lauratrapani commented on packages/pyxis-react/src/hoc/withFormItem/ItemLabel.tsx
> +  isHidden?: boolean;
Do you mean to remove the label when an `aria-labelledby` is passed to the component? Because at the moment is already possible to add the `aria-labelledby` prop to each component that has an input inside

2022-10-25 12:54 UTC, 70el commented on packages/pyxis-react/src/hoc/withFormItem/ItemLabel.tsx
> +  isHidden?: boolean;
> Do you mean to remove the label when an `aria-labelledby` is passed to the component? 

Yes - `aria-labelledby` takes precedence over `aria-label` and `<label />`, but we can avoid rendering the `<label />` tag to clean up the DOM a little.

This could also be a union type if it isn't already - for example, something like:

```
type LabelOrLabelledBy =
  | {
      label: string;
      isHidden?: boolean;
    }
  | { "aria-labelledby": string };
```
at the component level would enforce the consumer to always provide a `label`, or an `id` of an element that contains the label text.

2022-10-26 10:55 UTC, lauratrapani commented on packages/pyxis-react/src/hoc/withFormItem/ItemLabel.tsx
> +  isHidden?: boolean;
For an internal type issue in applying this suggestion, we postpone it to another card

2022-10-26 12:10 UTC, emanuelemacri approved these changes

2022-10-27 06:33 UTC, brianvanburken approved these changes

2022-10-27 07:27 UTC, merged