[DS-439]: [Pyxis React] Add tests for the Icon component
primait/pyxis pull request #312
Opened 2022-10-24 13:18 UTC by lauratrapani

https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/DS-439

2022-10-24 13:48 UTC, Gsciarra approved these changes

2022-10-24 14:47 UTC, brianvanburken approved these changes

2022-10-24 15:23 UTC, emanuelemacri requested changes

2022-10-24 15:23 UTC, emanuelemacri commented on packages/pyxis-react/scripts/generateIcons.ts
> +import { Icon, IconProps} from './Icon';
re-run the generate command
```suggestion
import { Icon, IconProps } from './Icon';
```

2022-10-24 15:23 UTC, emanuelemacri commented on packages/pyxis-react/src/components/Icons/Icon.tsx
> +}
for me we can put `name` inside `IconProps` and avoid the double type

2022-10-24 15:23 UTC, emanuelemacri commented on packages/pyxis-react/src/components/Tooltip/Tooltip.test.tsx
> +    expect(iconCar).toHaveAttribute('data-name', pascalToKebab('icon-car'));
or
```suggestion
    expect(iconCar).toHaveAttribute('data-name', pascalToKebab('iconCar'));
```
or just
```suggestion
    expect(iconCar).toHaveAttribute('data-name', 'icon-car');
```

2022-10-24 15:23 UTC, emanuelemacri commented on yarn.lock
> +"@ampproject/remapping@^2.1.0":
Why there is a new lock if you don't update the `package.json`? 👀

2022-10-24 15:23 UTC, emanuelemacri commented on packages/pyxis-react/scripts/generateIcons.ts
> +import { Icon, IconProps} from './Icon';
re-run the generate commands please 😄 
```suggestion
import { Icon, IconProps } from './Icon';
```

2022-10-24 15:31 UTC, lauratrapani commented on packages/pyxis-react/src/components/Icons/Icon.tsx
> +}
But then when you insert an icon the prop `name` would be available even if it would have any effect since the name is given by the script.

2022-10-25 12:18 UTC, emanuelemacri approved these changes
LGTM

2022-10-25 12:33 UTC, Gsciarra approved these changes

2022-10-25 12:51 UTC, merged