[DS-427]: [Pyxis] Standardise the name of sizes in SCSS, React and Elm
primait/pyxis pull request #317
Opened 2022-10-27 06:34 UTC by brianvanburken

https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/DS-427

2022-10-28 13:37 UTC, brianvanburken commented on packages/pyxis-react/src/commons/types/tokens.ts
> +// Generated on 28/10/2022, 08:44:43
https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/DS-461/Pyxis-Tokens-Remove-timestamp-from-generated-files

2022-10-31 14:19 UTC, brianvanburken commented on packages/pyxis-tokens/json/typography/text/sizes.json
> +    "s": 16
We discussed it in our call together. This would require more work as we need to change the token generation script, which is also copied to the react package. I want to suggest doing it in another ticket. Do you agree?

2022-11-02 09:05 UTC, emanuelemacri commented on packages/pyxis-elm/src/Pyxis/Commons/Breakpoint.elm
> +pointBase : Breakpoint
Maybe is better `size`? `Breakpoint.sizeXL`?

2022-11-02 09:10 UTC, alessiosantangelo approved these changes
Huge refactoring but it LGTM :) Hope I didn't miss anything

2022-11-02 09:40 UTC, brianvanburken commented on packages/pyxis-tokens/json/typography/text/sizes.json
> +    "s": 16
I've created [DS-474](https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/DS-474) for this

2022-11-02 09:54 UTC, lauratrapani reviewed
It's ok for me, but what about the style edits (the new breaklines)?

2022-11-02 09:55 UTC, emanuelemacri commented on packages/pyxis-elm/src/Pyxis/Components/Icon.elm
> +getIconSizeClass size =
I think is unuseful the `Icon` in this name, but is not a problem for now, we can fix all these new functions in another PR.

2022-11-02 10:04 UTC, brianvanburken commented on packages/pyxis-elm/src/Pyxis/Components/Icon.elm
> +getIconSizeClass size =
I'll quickly update it. What do you think about Laura's comments regarding styling? My editor seems to consistently style it the same way with only ESlint

2022-11-02 11:20 UTC, emanuelemacri requested changes
Some little fix

2022-11-02 11:20 UTC, emanuelemacri commented on packages/pyxis-scss/src/scss/components/buttons.scss
> +    &:where(.button--h):before {
```suggestion
    &:where(.button--xl):before {
```

2022-11-02 12:06 UTC, brianvanburken commented on packages/pyxis-react/src/commons/types/tokens.ts
> +export default {};
It is generated, so maybe we should create a ticket to correct this?

2022-11-02 12:07 UTC, brianvanburken commented on packages/pyxis-react/src/components/Autocomplete/Autocomplete.test.tsx
> +        searchIcon,
Should be fixed now on my side ;)

2022-11-02 13:07 UTC, emanuelemacri requested changes
last little fix

2022-11-02 13:07 UTC, emanuelemacri commented on packages/pyxis-react/src/commons/types/tokens.ts
> +export default {};
mh strange, maybe I fix it manually after the script 🤔 anyway, is better to remove the default now also in the `generateTokens.ts` (line 164) for avoiding problems.

2022-11-02 13:15 UTC, emanuelemacri approved these changes
LGTM 🚀

2022-11-02 13:26 UTC, merged