[DS-387]: [Pyxis Scss] Implement Toast component
primait/pyxis pull request #318
Opened 2022-10-31 17:09 UTC by lauratrapani

https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/DS-387

2022-11-04 14:56 UTC, alessiosantangelo approved these changes

2022-11-07 08:50 UTC, emanuelemacri requested changes
Some little issues, especially on mobile

2022-11-07 08:50 UTC, emanuelemacri commented on packages/pyxis-react/src/stories/components/Toast/Overview.tsx
> +        <Story id="components-display-toast-all-stories--default" />
```suggestion
        <Story id="components-display-toast-🚧-all-stories--default" />
```

2022-11-07 08:50 UTC, emanuelemacri commented on packages/pyxis-scss/src/scss/components/mixins.scss
> +@mixin closeButton ($bg-color: foundations.color(neutralLight), $focus-color: actionBase) {
```suggestion
@mixin closeButton ($bgColor: foundations.color(neutralLight), $focusColor: actionBase) {
```

2022-11-07 08:50 UTC, emanuelemacri commented on packages/pyxis-scss/src/scss/components/mixins.scss
> +  @include focus($focus-color, $radiusSize: m);
```suggestion
  @include focus($focusColor, $radiusSize: m);
```

2022-11-07 08:50 UTC, emanuelemacri commented on packages/pyxis-scss/src/scss/components/mixins.scss
> +    background-color: $bg-color;
```suggestion
    background-color: $bgColor;
```

2022-11-07 08:50 UTC, emanuelemacri commented on packages/pyxis-scss/src/scss/components/toast.scss
> +  width: calc(100vw - #{2 * foundations.spacing(m)});
would it not be better to use `spacing(2xl)` instead `spacing(m)`?
Anyway, is this container not centred on the page now, is correct?

2022-11-07 08:50 UTC, emanuelemacri commented on packages/pyxis-scss/src/scss/components/toast.scss
> +  width: max-content;
If you use `max-content`, breaks on mobile

2022-11-07 08:50 UTC, emanuelemacri commented on packages/pyxis-scss/src/scss/components/toast.scss
> +    &.toast--light {
```suggestion

    &.toast--light {
```

2022-11-07 08:50 UTC, emanuelemacri commented on packages/pyxis-scss/src/scss/components/toast.scss
> +      .toast__icon {
```suggestion

      .toast__icon {
```

2022-11-07 09:52 UTC, lauratrapani commented on packages/pyxis-scss/src/scss/components/toast.scss
> +  width: calc(100vw - #{2 * foundations.spacing(m)});
No, because on mobile the correct space is `m`. The position of the container has been fixed.

2022-11-07 10:06 UTC, brianvanburken commented on packages/pyxis-react/src/stories/components/Toast/Toast.tsx
> +    () => JSON.stringify(getChildrenIds(children)),
Why the stringify? I think you can just keep the list as it is. Then we do not need to parse it every time.

2022-11-07 12:10 UTC, lauratrapani commented on packages/pyxis-react/src/stories/components/Toast/Toast.tsx
> +    () => JSON.stringify(getChildrenIds(children)),
The stringify because `useEffect` can't accurately compare an array, so it provokes an infinite loop in the application. When doing the real component in React I guess that the entire component will be different so this wouldn't be needed anymore

2022-11-07 13:36 UTC, emanuelemacri approved these changes
LGTM

2022-11-07 14:38 UTC, Gsciarra approved these changes

2022-11-07 16:49 UTC, brianvanburken approved these changes

2022-11-08 08:08 UTC, merged