[PRIMA-12254]: [Pyxis Scss] Implement the textarea
primait/pyxis pull request #32
Opened 2022-01-12 15:50 UTC by lauratrapani

https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/PRIMA-12254

Style for textarea element

2022-01-13 08:37 UTC, alessiosantangelo requested changes

2022-01-13 08:37 UTC, alessiosantangelo commented on packages/pyxis-scss/src/scss/components/forms/fields/text.scss
> +  }
Qui il `disabled` andrebbe gestito come attributo dell' `input` o della `textarea`.

2022-01-13 08:37 UTC, alessiosantangelo commented on packages/pyxis-scss/src/scss/components/forms/fields/textarea.scss
> +  .form-field--disabled & {
Idem

2022-01-13 08:37 UTC, alessiosantangelo commented on packages/pyxis-scss/src/scss/components/forms/fields/field.scss
> +}
Non mi convince molto questo blocco. L'altezza del `form-field` dovrebbe dipendere esclusivamente dal suo contenuto. 
Il `text` field dovrebbe avere la `height` definita alla riga 100, stessa cosa per la `textarea`. Quando vogliamo una textarea con altezza `small` dovremmo applicare la classe a lei e non al suo parent.

2022-01-14 08:04 UTC, alessiosantangelo commented on packages/pyxis-scss/src/scss/components/forms/fields/field.scss
> +    min-width: utils.$heightSmall - $_borderWidth * 2;
Più che delle `utils` queste sono delle `variables/config`. Troviamo un nome che sia comodo mantenere anche in altri casi simili.

2022-01-14 08:04 UTC, alessiosantangelo commented on packages/pyxis-scss/src/scss/components/forms/fields/field.scss
> +    min-width: utils.$heightSmall - $_borderWidth * 2;
Continua a non tornarmi il perchè il `form-field` debba avere una `min-width`. Non basterebbe fare in modo che siano l'`input` o la `textarea` a definirne le dimensioni?

2022-01-14 08:17 UTC, lauratrapani commented on packages/pyxis-scss/src/scss/components/forms/fields/field.scss
> +    min-width: utils.$heightSmall - $_borderWidth * 2;
Non è il `form-field` ad avere una `min-width` ma l'addon (testuale o con l'icona)

2022-01-14 09:11 UTC, alessiosantangelo approved these changes

2022-01-14 09:11 UTC, merged