[PRIMA-12255]: [Pyxis Scss] Implement the input date
primait/pyxis pull request #34
Opened 2022-01-13 10:50 UTC by lauratrapani

https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/PRIMA-12255

Custom style for input of type date.

2022-01-14 16:43 UTC, emanuelemacri requested changes

2022-01-14 16:43 UTC, emanuelemacri commented on packages/pyxis-scss/src/scss/components/forms/fields/text.scss
> +}
Facciamolo diventare un file e una classe separata: `.form-field__date`

2022-01-17 08:23 UTC, emanuelemacri commented on packages/pyxis-scss/src/scss/components/forms/fields/text.scss
>    }
Questo andrà rimosso essendo sempre "with-leading-icon" sistema anche gli esempi poi 🤟

2022-01-17 08:56 UTC, emanuelemacri approved these changes
LGTM

2022-01-17 09:11 UTC, alessiosantangelo commented on packages/pyxis-scss/src/scss/components/forms/fields/field.scss
> +///      <textarea className="form-field__date" />
Nei commenti è rimasto `textarea`

2022-01-17 09:11 UTC, alessiosantangelo requested changes

2022-01-17 09:11 UTC, alessiosantangelo commented on packages/pyxis-scss/src/scss/components/forms/fields/field.scss
> +///      <textarea
Idem

2022-01-17 13:24 UTC, alessiosantangelo approved these changes

2022-01-17 13:25 UTC, merged