[PRIMA-12266]: [Pyxis Scss] Implement radio button
primait/pyxis pull request #36
Opened 2022-01-17 11:32 UTC by lauratrapani

https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/PRIMA-12266

Implementig classes for radio button styling

2022-01-17 16:17 UTC, emanuelemacri commented on packages/pyxis-react/src/stories/components/Form/RadioButton/Radio.tsx
> +        <div className="form-control__group">
Se usato qui si deve chiamare `form-control-group` o `form-control-wrapper` altrimenti abbiamo sempre il problema che sembra un BEM inverso

2022-01-17 16:44 UTC, alessiosantangelo requested changes

2022-01-17 16:44 UTC, alessiosantangelo commented on packages/pyxis-scss/src/scss/components/forms/controls/radio.scss
> +    box-shadow:inset 0 0 0 lib.rem(3px) foundations.color(neutralLight);
Questo potrebbe diventare un `mixin` privato con il valore di `color` passato come parametro

2022-01-17 16:44 UTC, alessiosantangelo commented on packages/pyxis-scss/src/scss/components/forms/controls/control.scss
> +///    <div className="form-control__group">
`form-control__group` in questo caso è sbagliato in quanto parent di `form-control` e non child come ci si aspetterebbe. 
Possiamo usare il solito `form-control-wrapper` che nella nostra convenzione BEM è concesso

2022-01-17 16:44 UTC, alessiosantangelo commented on packages/pyxis-scss/src/scss/components/forms/controls/control.scss
> +///    <label className="form-control">
Qui non si riesce ad utilizzare `form-field`?

2022-01-17 16:44 UTC, alessiosantangelo commented on packages/pyxis-scss/src/scss/components/forms/controls/control.scss
> +  top: calc(100% + #{lib.rem(2px)});
Questo dovrebbe essere uguale a `bottom: -2px`. 
Occhio a mettere sotto variabile quel `2px` così da non avere magic numbers in giro per il codice.

2022-01-17 16:44 UTC, alessiosantangelo commented on packages/pyxis-scss/src/scss/components/forms/controls/control.scss
> +///        <span>Radio</span>
Questo `span` credo sia di troppo. Si potrebbe trattare come un semplice contenuto di `label`

2022-01-17 16:44 UTC, alessiosantangelo commented on packages/pyxis-scss/src/scss/components/forms/controls/control.scss
> +///      <label className="form-control form-control--disabled">
Per quanto possibile eviterei di mettere classi di stato sugli elementi che hanno una controparte html. 
In questo caso il `disabled` va sul radio button, quindi potremmo provare a pensare ad una soluzione che si basi sulla presenza di quest'attributo nel campo `input` invece che doverlo duplicare. 

Esempio, cosa succede se mi dimentico di mettere la classe `form-control--disabled` quando ho un `<input type="radio" disabled>`.
E viceversa?

2022-01-17 16:44 UTC, alessiosantangelo commented on packages/pyxis-scss/src/scss/components/forms/controls/control.scss
> +  @include mixins.fieldErrorMessage;
In generale non riusciamo a fare a meno dei posizionamenti assoluti?

2022-01-17 16:47 UTC, emanuelemacri commented on packages/pyxis-scss/src/scss/components/forms/mixins.scss
> +  &:disabled, &[disabled] {
a capo

2022-01-17 16:53 UTC, emanuelemacri commented on packages/pyxis-scss/src/scss/components/forms/controls/control.scss
> +///        <span>Radio</span>
L'ho fatto mettere io, in quanto ci verrà utile nel checkbox (che dovrà avere delle pseudo classi), così almeno abbiamo sempre la stessa struttura, l'unica cosa da fare in più è classarlo da subito

2022-01-17 16:54 UTC, emanuelemacri commented on packages/pyxis-scss/src/scss/components/forms/controls/control.scss
> +  @include mixins.fieldErrorMessage;
Non per l'errore in quanto non deve occupare spazio nella griglia (così da evitare spostamenti del field quando esce un errore)

2022-01-17 17:09 UTC, lauratrapani commented on packages/pyxis-scss/src/scss/components/forms/controls/control.scss
> +///      <label className="form-control form-control--disabled">
Ho cercato di essere più coerente possibile con il quello che abbiamo fatto con il `text-field` dove c'è la stessa logica. La classe di per se cambia solo il cursore, mentre la gestione del campo è fatta gestita con le apposite pseudo-class

2022-01-17 17:10 UTC, lauratrapani commented on packages/pyxis-react/src/stories/components/Form/RadioButton/Radio.tsx
> +        <span className="label">Label</span>
La label in elm va cambiata comunque in quanto il `for` è stato impostato come obbligatorio.

2022-01-17 17:17 UTC, lauratrapani commented on packages/pyxis-scss/src/scss/components/forms/controls/control.scss
> +///    <label className="form-control">
No, sono due classi completamente diverse, `form-field` applica tutte le logiche degli stati, mentre `form-control` gestisce la disposizione tra input e label.

2022-01-18 09:20 UTC, lauratrapani commented on packages/pyxis-scss/src/scss/components/forms/controls/control.scss
> +  top: calc(100% + #{lib.rem(2px)});
No, non è la stessa cosa perché a `-2px`, che è l'effettivo gap tra il form e l'errore, andrebbe aggiunta l'altezza dell'errore che però sarebbe un altro magic number non esprimibile in modo semplice con una variabile dato che l'interlinea è definita con una variabile privata. Per questo è stato messo `top` invece di `bottom`. Ok invece per mettere il valore in una variabile.

2022-01-18 10:19 UTC, emanuelemacri commented on packages/pyxis-react/src/stories/components/Form/RadioButton/Radio.tsx
> +        <span className="label">Label</span>
Ho fatto alcune prove:
- possiamo comunque lasciare il tag label, comunque è coerente e non da problemi
- se mettiamo il for che punta al primo radio abbiamo comunque l stesso effetto degli altri cambi (anche se non ho trovato esempi in cui lo usano così)

2022-01-18 10:21 UTC, emanuelemacri commented on packages/pyxis-scss/src/scss/components/forms/controls/control.scss
> +///        <span>Radio</span>
@lauratrapani errore mio, in realtà ho appena scoperto che sia i radio che i checkbox accettano `:before` e `:after`, quindi possiamo evitare questo tag `span` e la relativa classe 🚀

2022-01-18 10:33 UTC, lauratrapani commented on packages/pyxis-react/src/stories/components/Form/RadioButton/Radio.tsx
> +        <span className="label">Label</span>
Onestamente non lo trovo così coerente lato HTML, di fatto chiamiamo con `label` quello che dovrebbe essere un `p` o un `div` generico, quindi mi sembra un po' una forzatura.

2022-01-18 11:38 UTC, emanuelemacri requested changes
Un paio di sciocchezze, ma per me è 👍

2022-01-18 11:38 UTC, emanuelemacri commented on packages/pyxis-scss/src/scss/components/forms/controls/control.scss
> +///      <label className="form-control form-control">
`form-control` c'è due volte

2022-01-18 11:38 UTC, emanuelemacri commented on packages/pyxis-scss/src/scss/components/forms/controls/control.scss
> +///      <label className="form-control form-control--disabled">
Anche se per poche regole servono entrambi, nel caso dei `form-control` servono solo per il `cursor` invece nel `form-field` servono anche a dare tutto lo stile `disabled` agli elementi aggiuntivi. Possiamo dire che è mandatorio per il giusto comportamento usare sia la classe sul parent che l'attributo sull'input.

2022-01-18 11:38 UTC, emanuelemacri commented on packages/pyxis-scss/src/scss/components/forms/mixins.scss
> +
Leviamo questo spazietto

2022-01-18 11:56 UTC, emanuelemacri approved these changes
LGTM

2022-01-18 15:11 UTC, alessiosantangelo approved these changes

2022-01-18 15:12 UTC, alessiosantangelo commented
Mi sembra che i dubbi principali siano stati smarcati, poi quando andiamo a montare il componente in Elm e React possiamo accorgerci se ci sono dei problemi o meno :)

2022-01-18 15:12 UTC, merged