[PRIMA-12253]: [Pyxis Scss] Implement the Select
primait/pyxis pull request #37
Opened 2022-01-17 11:33 UTC by emanuelemacri

Style select

https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/PRIMA-12253

2022-01-17 16:04 UTC, lauratrapani commented on packages/pyxis-scss/src/scss/components/forms/dropdown.scss
> +  visibility: hidden;
Come mai c'è sia `opacity: 0` che `visibility: hidden`?

2022-01-19 11:02 UTC, alessiosantangelo requested changes

2022-01-19 11:02 UTC, alessiosantangelo commented on packages/pyxis-scss/src/scss/components/forms/dropdown.scss
> +  .form-field--has-opened-dropdown & {
Forse avevamo detto di non usare `has` ma di usare `--with`

2022-01-19 11:47 UTC, lauratrapani approved these changes

2022-01-19 16:05 UTC, alessiosantangelo approved these changes

2022-01-19 16:05 UTC, merged