[PRIMA-12269]: [Pyxis Scss] [Pyxis Elm] Label fix
primait/pyxis pull request #40
Opened 2022-01-20 08:59 UTC by lauratrapani

https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/PRIMA-12269

Transforming `label` to `form-label`, setting `for` attribute as non-mandatory

2022-01-20 09:17 UTC, emanuelemacri approved these changes
A me sembra tuto ok, lascio la parola agli altri 👍

2022-01-20 13:36 UTC, alessiosantangelo requested changes

2022-01-20 13:36 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Label.elm
> +Please note: without a `for` the element will be rendered as a span.
Fermi tutti: perchè sta cosa?

2022-01-20 13:46 UTC, lauratrapani commented on packages/pyxis-elm/src/Components/Label.elm
> +Please note: without a `for` the element will be rendered as a span.
Perché ci siamo accorti che in radio e checkbox quello che da design è chiamato "label" in realtà è scorretto che lo sia anche a livello di tag, perchè `label` dovrebbe essere solo l'etichetta vicino all'input e non la frase che presenta la scelta.

2022-01-21 08:57 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Label.elm
> +Please note: without a `for` the element will be rendered as a span.
Ma questo crea dei problemi? Perchè a me sembra peggio avere un componente che cambia tag in output a seconda del parametro che gli si passa. Non funziona ugualmente sostituendo `span` con `label` ed evitando il `for`?

2022-01-21 09:24 UTC, lauratrapani commented on packages/pyxis-elm/src/Components/Label.elm
> +Please note: without a `for` the element will be rendered as a span.
sì esatto, sì può mettere solo il `for` come opzionale, però mi sembrava meno scorretto lato html. Tolgo lo switch del tag.

2022-01-21 09:52 UTC, alessiosantangelo approved these changes

2022-01-21 09:52 UTC, merged