Remove `form-field--small` class
primait/pyxis pull request #42
Opened 2022-01-20 11:14 UTC by emanuelemacri

2022-01-20 13:35 UTC, alessiosantangelo requested changes

2022-01-20 13:35 UTC, alessiosantangelo commented on packages/pyxis-scss/src/scss/components/forms/variables.scss
> +$fieldWidth: calc(100% - #{$fieldHeight});
Non mi è chiaro perchè la larghezza debba essere 100% - 70px (altezza).
Avrebbe più senso fissare una dimensione assoluta, che ne so, `350px`.

2022-01-20 14:09 UTC, emanuelemacri commented on packages/pyxis-scss/src/scss/components/forms/variables.scss
> +$fieldWidth: calc(100% - #{$fieldHeight});
Questo `- fieldHeight` è per non usare la classe `form-size--small`, per quanto riguarda la larghezza standar del campo invece vorrei parlare prima con i designer

2022-01-21 08:58 UTC, alessiosantangelo approved these changes

2022-01-21 08:58 UTC, merged