[PRIMA-12287]: [Pyxis Elm] Add missing API to TextField
primait/pyxis pull request #50
Opened 2022-01-27 17:02 UTC by Gsciarra

https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/PRIMA-12287

2022-01-28 14:20 UTC, alessiosantangelo requested changes
Inizio a lasciare qualche commento non richiesto 😄

2022-01-28 14:20 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Field/Input.elm
> +    , errorMessage : Maybe String
Questo non è corretto, dovremmo permettere di avere un `errorMessage` per ogni validazione. 
Infatti è il tipo `Validation` a contenere il messaggio di errore per ogni check fallito.

2022-01-28 14:20 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Field/Input.elm
> +                        ]
Questo è un `Maybe.map` quindi: 
- usiamo `Maybe.map`
- creiamo una funzione `renderAddOn : Configuration -> AddOn -> Html msg`
- scriviamo `addon |> Maybe.map (renderAddOn configuration) |> Maybe.withDefault (viewInput configuration)`

2022-01-28 14:20 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Field/Input.elm
> +errorMessageId id =
Questo non dovrebbe più servire se si usa la validazione per esprimere qual è il messaggio di errore.

2022-01-28 14:20 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Field/Text.elm
> +@docs textAddon
```suggestion
@docs iconAddon
@docs textAddon
@docs withAddon
```

2022-01-28 14:20 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Stories/Chapters/TextField.elm
> +textField : Html Msg
Manca la firma di `Tagger`

2022-01-28 14:20 UTC, alessiosantangelo commented on packages/pyxis-elm/tests/Components/InputTest.elm
> +import Test.Extra as Test
Se usiamo l'alias `Test` qui facciamolo anche per gli altri tests. 
In caso contrario va benissimo fare `exposing (Test, suite, ecc...)`

2022-01-28 14:20 UTC, alessiosantangelo commented on packages/pyxis-elm/tests/Components/TextFieldTest.elm
> +            [ Test.test "Disabled attribute should be False by default" <|
I `test` devono iniziare con la minuscola. I `describe` con la maiuscola

2022-01-28 14:23 UTC, alessiosantangelo requested changes

2022-01-28 14:23 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Field/Input.elm
> +    , value : Maybe String
Qui sarebbe molto meglio gestire `value` come un generico tipo `value` e farsi passare da fuori (cioè da `Text/Email/Date/Number` le funzioni di conversione. 
Così questo modulo rimane agnostico e non siamo costretti a forzare l'utilizzatore a castare tutto a stringa a "modo nostro"

2022-01-28 14:25 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Field/Input.elm
> +                        ]
Inoltre si possono usare i `Commons.Render.renderIf/renderUnless` per avere una sola funzione di questo tipo: 
```
import Commons.Render as CR

viewAddon : Configuration -> AddOn -> Html msg 
viewAddon configuration addon = 
   Html.label [ Attributes.class "form-field__wrapper" ]
                        [ addon.type_  |> viewAddon  |> CR.renderIf (Placement.isPrepend addon.placement)
                        , viewInput configuration
                        , addon.type_  |> viewAddon  |> CR.renderIf (Placement.isAppend addon.placement)
                        ]
```

2022-01-31 08:56 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Field/Input.elm
> +                (always (Attributes.attribute "aria-describedby" (errorMessageId configuration.id)))
Nel modulo `Commons.Attributes` potete aggiungere `aria-describedby` come fatto per gli altri `aria` e `dataTestId`

2022-01-31 08:56 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Field/Input.elm
> +                [ Html.text str ]
```suggestion
Html.div [ Attributes.class "form-field__addon" ] (
    case type_ of
        IconAddon icon ->
                [ icon |> Icon.create |> Icon.render ]

        TextAddon str ->
                [ Html.text str ]
)
```

2022-01-31 08:56 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Field/Input.elm
> +                "form-field--with-prepend-text"
Possiamo fare due funzioni di appoggio per `addonToAttribute`: 
- una che ritorna la desinenza `prepend/append`
- un'altra che ritorna la desinenza `text/icon`

Così possiamo usarle insieme del tipo: 
```elm
String.join "-" ["form-field--with", "append/prepend", "text/icon"] 
```

2022-01-31 09:45 UTC, ascandone commented on packages/pyxis-elm/src/Components/Field/Input.elm
> +                (always (Attributes.attribute "aria-describedby" (errorMessageId configuration.id)))
Potrebbe essere utile un namespace `Commons.Attributes.Aria`?  Gli attributes aria sono tantissimi, magari potrebbe fare comodo averli insieme (da usare come `Aria.describedBy` )

2022-01-31 10:28 UTC, alessiosantangelo requested changes
Poca roba, il resto mi sembra ok

2022-01-31 10:28 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Field/Input.elm
> +    , Events
Qui c'è il tipo `Events` che però non ha alcuna api associata. Inoltre non ha una sezione della docs a lui dedicata (vedi es. `AddOn`)

2022-01-31 10:28 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Field/Input.elm
> +                configuration.errorMessage
```suggestion
            , Maybe.map
                (always ( configuration.id >> errorMessageId >> CommonsAttributes.ariaDescribedby))
                configuration.errorMessage
```

2022-01-31 16:38 UTC, alessiosantangelo approved these changes
LGTM

2022-01-31 16:39 UTC, merged