[PRIMA-12274]: [Pyxis Scss] Message implementation
primait/pyxis pull request #51
Opened 2022-01-31 08:54 UTC by lauratrapani

https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/PRIMA-12274

Implementi CSS classes for message component.

2022-01-31 09:32 UTC, lauratrapani commented
<img width="1029" alt="Schermata 2022-01-31 alle 10 31 15" src="https://user-images.githubusercontent.com/59093016/151769523-fea69cd9-dd4c-4690-ad69-a5af74d2a925.png">

2022-01-31 09:43 UTC, alessiosantangelo requested changes

2022-01-31 09:43 UTC, alessiosantangelo commented on packages/pyxis-scss/src/scss/components/message.scss
> +    &.message--with-semantic-background {
Non mi convince molto _colore di sfondo semantico_ come nome della classe...
Se quello che intendiamo dire è che: normalmente i messaggi non hanno colore di sfondo, ma con questo modificatore ce l'hanno, allora potremmo chiamare la classe `--alt` o come avevamo fatto per i bottoni.

2022-01-31 10:02 UTC, emanuelemacri requested changes

2022-01-31 10:02 UTC, emanuelemacri commented on packages/pyxis-scss/src/scss/components/message.scss
> +    &.message--with-semantic-background {
Son d'accordo, non userei "alt" perché potremmo avere delle versioni `--alt` su sfondo scuro. Forse meglio semplicemente: `--with-state-color` o `--with-background-color`

2022-01-31 10:42 UTC, lauratrapani commented on packages/pyxis-scss/src/scss/components/message.scss
> +@each $state, $stateList in $_states {
Ma perchè? può essere omesso senza problemi

2022-01-31 11:47 UTC, lauratrapani commented on packages/pyxis-scss/src/scss/components/message.scss
> +@each $state, $stateList in $_states {
ok avevo letto male io :)

2022-01-31 11:49 UTC, emanuelemacri approved these changes
LGTM

2022-02-01 09:13 UTC, alessiosantangelo commented on packages/pyxis-scss/src/scss/components/message.scss
> +.message--unboxed {
Come per i [badge](https://github.com/primait/pyxis/pull/52/files) forse questo message può essere un `ghost`?

2022-02-01 10:02 UTC, lauratrapani commented on packages/pyxis-scss/src/scss/components/message.scss
> +.message--unboxed {
Approvato anche da designer

2022-02-02 08:52 UTC, alessiosantangelo approved these changes

2022-02-02 08:52 UTC, merged