[PRIMA-12283]: [Pyxis Scss] Badge implementation
primait/pyxis pull request #52
Opened 2022-01-31 14:33 UTC by lauratrapani

https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/PRIMA-12283

Implementind badge component CSS

2022-01-31 14:46 UTC, lauratrapani commented
<img width="598" alt="Schermata 2022-01-31 alle 15 46 02" src="https://user-images.githubusercontent.com/59093016/151814427-742cfe28-e30e-42ad-a78c-6eceb09bf66e.png">

2022-01-31 15:09 UTC, emanuelemacri requested changes

2022-01-31 15:09 UTC, emanuelemacri commented on packages/pyxis-scss/src/scss/components/badge.scss
> +$_states: (brand, action, alert, success, error);
In questo caso userei la parola `$_variants` come per i bottoni e inserirei all'interno anche i gradienti, così da evitare [vedi commento successivo]

2022-01-31 15:09 UTC, emanuelemacri commented on packages/pyxis-scss/src/scss/components/badge.scss
> +}
... così evitiamo questa cosa qui, in cui un gradiente ha un colore, ma con un'altra classe ne ha un'altra, è un po' strano. Meglio mettere le varianti con i gradient con un'unica classe:
```
.badge--brand-gradient {}
.badge--neutral-gradient {}
```
direttamente nell'`@each`

2022-02-01 09:04 UTC, emanuelemacri approved these changes
LGTM

2022-02-01 09:12 UTC, alessiosantangelo commented on packages/pyxis-scss/src/scss/components/badge.scss
> +.badge--transparent {
Questo potrebbe essere un `ghost` badge? 
Chiedo per cercare di mantenere coerenza tra i nomi dei vari componenti quando le caratteristiche sono simili o uguali.

2022-02-01 09:56 UTC, lauratrapani commented on packages/pyxis-scss/src/scss/components/badge.scss
> +.badge--transparent {
Nome approvato anche dai designer :)

2022-02-02 08:53 UTC, alessiosantangelo approved these changes

2022-02-02 08:53 UTC, merged