[PRIMA-12282]: [Pyxis Scss] Add common transition
primait/pyxis pull request #53
Opened 2022-02-01 09:31 UTC by emanuelemacri

Add motion foundations

https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/PRIMA-12282

2022-02-01 17:13 UTC, lauratrapani commented on packages/pyxis-scss/src/scss/components/forms/dropdown.scss
> +  @include foundations.motion((opacity, outline-color, padding-top, visibility), faster, exit);
Meglio non aggiungere `visibility` visto che non è animabile?

2022-02-01 17:16 UTC, emanuelemacri commented on packages/pyxis-scss/src/scss/components/forms/dropdown.scss
> +  @include foundations.motion((opacity, outline-color, padding-top, visibility), faster, exit);
Lo so, ma senza quello l'animazione in uscita non funziona 🤷‍♂️

2022-02-01 17:17 UTC, lauratrapani commented on packages/pyxis-scss/src/scss/components/forms/dropdown.scss
> +  @include foundations.motion((opacity, outline-color, padding-top, visibility), faster, exit);
toglierlo dal mixin intendo.

2022-02-02 08:27 UTC, alessiosantangelo requested changes

2022-02-02 08:27 UTC, alessiosantangelo commented on packages/pyxis-scss/src/scss/components/buttons.scss
> +      loadingEntry foundations.timing(fast) foundations.easing(base);
Per cosa starebbe `loadingEntry`? Se si parla dell'_entrata_ di un elemento nell'animazione allora dovremmo chiamarlo `entrance` o qualcosa di più parlante.

2022-02-02 08:27 UTC, alessiosantangelo commented on packages/pyxis-scss/src/scss/tokens/motionTiming.scss
> +  slower: 800ms,
I nomi non sono corretti, dovrebbero essere: 
- `fastest/slowest`
- `fast/slow`
- `default` (oppure `base`)

2022-02-02 08:27 UTC, alessiosantangelo commented on packages/pyxis-scss/src/scss/tokens/motionEasing.scss
> +);
I nomi mi lasciano un po' perplesso... principalmente:
- `base` a volte lo chiamiamo `default`, scegliamo quindi una consistenza in tutti i nomi di tutte le proprietà. 
- l'opposto di `entrance` dovrebbe essere `exitance`
- in generale meglio chiamarli `enter/exit`

2022-02-02 08:27 UTC, alessiosantangelo commented on packages/pyxis-scss/src/scss/tokens/motionEasing.scss
> +);
Inoltre queste sono le uniche animazioni disponibili per Pyxis? Oppure è possibile crearne di custom?

2022-02-02 08:27 UTC, alessiosantangelo commented on packages/pyxis-scss/src/scss/foundations/motion.scss
> +}
Mi sembra decisamente overkill questa gestione. Stiamo riscrivendo un wrapper attorno a `transition` modificandone le api solo per costringere ad usare le variabili di timing e easing che abbiamo definito. 

Inoltre ci si aspetta che `motion` copra anche le regole di `animation/keyframes` ma questo non succede. 

Basterebbe declinare le transitions così: 
```scss
.my-class {
   transition: opacity timing(fastest) motion(enter);
}

.my-class2 {
   transition: opacity timing(fastest) motion(enter) timing(slowest);
}

```

2022-02-02 11:22 UTC, emanuelemacri commented on packages/pyxis-scss/src/scss/components/forms/dropdown.scss
> +  @include foundations.motion((opacity, outline-color, padding-top, visibility), faster, exit);
Eh no serve proprio nel mixin come transizione, altrimenti scatta, anche se è un comportamento strano

2022-02-02 11:22 UTC, emanuelemacri commented on packages/pyxis-scss/src/scss/components/buttons.scss
> +      loadingEntry foundations.timing(fast) foundations.easing(base);
Questa è l'animazione di entrata del loader all'interno del bottone

2022-02-02 11:36 UTC, emanuelemacri commented on packages/pyxis-scss/src/scss/tokens/motionEasing.scss
> +);
Per punti:
- Dovremmo usare sempre `base` ma non vedo `default` nel codice scss, forse lo usiamo in alcune occasioni su elm
- `exitance` ha proprio un altro [significato](https://www.collinsdictionary.com/it/dizionario/inglese/exitance), di base mi sono rifatto ad altri DS come [carbon](https://www.carbondesignsystem.com/guidelines/motion/overview/) e [wanda](https://design.wonderflow.ai/develop/design-tokens) che usano queste terminologie
- Non ho grosse preferenze comunque, possiamo usare semplicemente `enter/exit`

2022-02-02 11:47 UTC, emanuelemacri commented on packages/pyxis-scss/src/scss/foundations/motion.scss
> +}
> Stiamo riscrivendo un wrapper attorno a transition modificandone le api solo per costringere ad usare le variabili di timing e easing che abbiamo definito.
È quello che facciamo con ogni token (come con gli spacing), in modo da avere dei valori fissi per tutto

> Inoltre ci si aspetta che motion copra anche le regole di animation/keyframes ma questo non succede.
Vero anche questo, al momento qui gestirei solo i valori "base" di una animazione o transizione, come i tempi o l'easing, che si sposano bene con le `transition`, Le animazioni con i vari keyframe invece sono molto più custom in base ai componenti e al momento non ne abbiamo di "generiche", in futuro però potremmo aggiungerle qui.

Infine, nell'esempio che hai fatto tu funziona tutto correttamente, ma abbiamo spesso casi in cui abbiamo più regole su cui applicare la transition, il mixin va a risolvere la ripetizione dei valori:

```
.my-class {
   transition: opacity timing(fastest) motion(enter),
     transform timing(fastest) motion(enter),
     background timing(fastest) motion(enter),
     color timing(fastest) motion(enter);
}
```
in questo:
```
.my-class {
  @include motion((opacity, transform, background, color), fastest, enter)
}
```

2022-02-02 13:24 UTC, alessiosantangelo commented on packages/pyxis-scss/src/scss/foundations/motion.scss
> +}
Non sono convintissimo di questa scelta, anche perchè c'è la keyword `all` per le transitions multiple. 
In ogni caso, però se vogliamo mantenere questo mixin almeno chiamiamolo `transition` così che sia chiaro quale regola vada a definire.

2022-02-02 13:26 UTC, alessiosantangelo commented on packages/pyxis-scss/src/scss/tokens/motionEasing.scss
> +);
> Più che animazioni questi sono i timing-function utilizzabili, vanno a sostituire i vari ease, ease-in, ease-out, l'unico che potrebbe effettivamente servire è il linear in alcune situazioni, posso aggiungerlo

Proprio per questo motivo mi sembra molto più lineare esporre solo `timing/easing` customizzati per Pyxis. Il resto è comunque una ripetizione della proprietà `transition` che non aggiunge nulla all'utilizzatore finale. 

Tanto più che comunque sarà possibile creare delle transitions custom (e sarà necessario farlo) bypassando questo mixin.

2022-02-02 13:41 UTC, emanuelemacri commented on packages/pyxis-scss/src/scss/foundations/motion.scss
> +}
La keyword `all` sarebbe da evitare, sia per performance che per problemi derivati (non so se ricordi, su `frontale` avevamo  dovuto levare tutti gli `all` dalle transizioni in quanto creava delle animazioni non volute al loading della pagina).

Comunque in ogni caso, non voglio farne una guerra :D nel caso delle singole transizioni mi rendo conto che è un po' overkill, mi sembrava comodo sopratutto nel caso di transizioni multiple per non ripetere codice.

Possiamo anche non inserirlo e capire come gestire questo foundation meglio in seguito, quando avremo più esempi e magari anche delle animazioni più complesse e generiche

2022-02-02 13:46 UTC, alessiosantangelo commented on packages/pyxis-scss/src/scss/foundations/motion.scss
> +}
> Comunque in ogni caso, non voglio farne una guerra 😄

No no ma figurati, si sta solo discutendo 😄 So di essere un rompicoglioni ma mi hanno messo qui apposta 😄 
Comunque allora per ora rimuoviamolo e se poi abbiamo delle animazioni/transizioni veramente comuni a Pyxis possiamo fare dei mixins per quelle ;)

2022-02-02 13:50 UTC, emanuelemacri commented on packages/pyxis-scss/src/scss/foundations/motion.scss
> +}
> No no ma figurati, si sta solo discutendo 😄

Ma si "guerra" in senso giocoso (se esiste)

> So di essere un rompicoglioni ma mi hanno messo qui apposta 😄

E sei bravissimo ❤️

Comunque a parte gli scherzi, si tranquillo va benissimo, per ora rimuovo e in caso aggiorniamo più in là

2022-02-02 14:41 UTC, emanuelemacri commented on packages/pyxis-scss/src/scss/foundations/motion.scss
> +}
@alessiosantangelo ho rimosso il mixin e sistemato un po' il tutto

2022-02-03 09:03 UTC, alessiosantangelo approved these changes

2022-02-03 09:03 UTC, merged