[PRIMA-12289]: [Pyxis Elm] ElmBook: TextField
primait/pyxis pull request #54
Opened 2022-02-01 09:50 UTC by Gsciarra

https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/PRIMA-12289

2022-02-07 15:33 UTC, alessiosantangelo approved these changes

2022-02-07 15:46 UTC, emanuelemacri requested changes
Un po' di fix per mantenere coerenza con la struttura della doc dei bottoni

2022-02-07 15:46 UTC, emanuelemacri commented on packages/pyxis-elm/src/Stories/Chapters/TextField.elm
> +<component with-label="TextField withAddon prepend text" />
```suggestion
## Addon
Text field can have several addons, such as icons or texts. They are used to make the user understand the purpose of the field better.

**Please Note**: use these addons one at a time.

### Addon: Prepend Text
<component with-label="TextField withAddon prepend text" />
```

2022-02-07 15:46 UTC, emanuelemacri commented on packages/pyxis-elm/src/Stories/Chapters/TextField.elm
> +<component with-label="TextField withAddon append text" />
```suggestion

### Addon: Append Text
<component with-label="TextField withAddon append text" />
```

2022-02-07 15:46 UTC, emanuelemacri commented on packages/pyxis-elm/src/Stories/Chapters/TextField.elm
> +<component with-label="TextField withAddon prepend icon" />
```suggestion

### Addon: Prepend Icon
<component with-label="TextField withAddon prepend icon" />
```

2022-02-07 15:46 UTC, emanuelemacri commented on packages/pyxis-elm/src/Stories/Chapters/TextField.elm
> +<component with-label="TextField withAddon append icon" />
```suggestion

### Addon: Append Icon
<component with-label="TextField withAddon append icon" />
```

2022-02-07 15:46 UTC, emanuelemacri commented on packages/pyxis-elm/src/Stories/Chapters/TextField.elm
> +<component with-label="TextField withSize small" />
```suggestion
## Size

Sizes set the occupied space of the text-field.

You can set your TextField with a _size_ of default or small.

### Size: Small
<component with-label="TextField withSize small" />
```

2022-02-07 16:00 UTC, emanuelemacri commented on packages/pyxis-elm/src/Stories/Chapters/TextField.elm
> +<component with-label="TextField withSize small" />
A scusami @Gsciarra altra cosa, qui non viene renderizzato correttamente il componente small

2022-02-07 16:23 UTC, emanuelemacri approved these changes
👍

2022-02-08 08:34 UTC, alessiosantangelo approved these changes

2022-02-08 08:34 UTC, merged