[PRIMA-12295]: [Pyxis Elm] Implement the NumberField component
primait/pyxis pull request #57
Opened 2022-02-02 11:25 UTC by ascandone

https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/PRIMA-12295

2022-02-02 13:30 UTC, alessiosantangelo requested changes

2022-02-02 13:30 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Field/Number.elm
> +    = OnInput String
Il campo `Number` non deve accettare delle `String`. È stato proprio l'oggetto delle ultime discussioni...

2022-02-02 13:33 UTC, ascandone commented on packages/pyxis-elm/src/Components/Field/Number.elm
> +    = OnInput String
Dalla discussione di prima avevo capito che la validazione andasse fatta fuori
Vedo cosa riesco a fare

2022-02-07 15:21 UTC, alessiosantangelo requested changes

2022-02-07 15:21 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Field/Number.elm
> +        , validation = \_ -> Ok
Qui direi che possiamo scrivere `always Ok`

2022-02-07 15:21 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Field/Number.elm
> +            setValue normalizedValue model
Sposterei questo `let..in` (non vogliamo mai che ce ne siano dentro le funzioni di update) dentro `setValue`, così che quest'ultima riceva in input lo stesso dato che ha nella firma.

2022-02-07 15:29 UTC, alessiosantangelo requested changes

2022-02-07 15:29 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Field/Number.elm
> +    = OnInput String
```elm 
-- Components/Field/Input.elm 
-- Qui lavoriamo con i _value_, quindi possiamo esporre due funzioni: 

-- Questa viene usata nel settaggio dell'attributo _Html.Events.onClick_ per mappare il valore
withOnInputMap : String -> value

-- Questa viene usata nel per leggere il value corrente e stampare _Html.Attributes.value_
withValueMap : value -> String


-- Components/Field/Number.elm
-- Così qua lavoriamo sempre e solo con gli Interi e dentro Input solo ed esclusivamente con i value e li trattiamo 
-- come tali fino al momento della scrittura o del tag di un messaggio
type Msg =
    OnInput Int

2022-02-08 08:24 UTC, alessiosantangelo reviewed
Una

2022-02-08 08:24 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Field/Number.elm
> +@docs Model
```suggestion
@docs Model
@docs create
```

2022-02-08 08:28 UTC, alessiosantangelo approved these changes

2022-02-08 08:28 UTC, merged

2022-02-08 08:32 UTC, ascandone commented on packages/pyxis-elm/src/Components/Field/Number.elm
> +    = OnInput String
Per ora messo
`type Msg = OnInput Int`
Senza passare per 
`withOnInputMap, withValueMap`
perché in effetti si può fare lo stesso, e si lascia semplice e "nativo" l'input (e senza type parameter sul tipo)
Il comportamento esterno (sia per utente che usa la UI sia per utente di pyxis) è lo stesso, quindi si può sempre aggiungere se vediamo che è utile