[PRIMA-12284]: [Pyxis] Add Readme.md
primait/pyxis pull request #61
Opened 2022-02-07 10:19 UTC by emanuelemacri

Add general readme to repository

https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/PRIMA-12284

2022-02-07 14:15 UTC, Gsciarra commented on package.json
> +    "generate:icons": "lerna run generate:icons --stream",
Se il nostro deploy deve essere orientato al singolo progetto, dovremmo andare nell'altra direzione, ossia aggiungere altri script con `--scope`.

2022-02-07 14:16 UTC, Gsciarra commented on packages/pyxis-react/README.md
> +This repository is part of Pyxis Design System, and contain all the components made in React.
This repository is part of the Pyxis Design System and contains all the React components.

2022-02-07 14:31 UTC, alessiosantangelo requested changes

2022-02-07 14:31 UTC, alessiosantangelo commented on README.md
> +This repository hosts libraries for web applications.
```suggestion
This repository is made up of: 
- a representation of our _Design Tokens_
- an _SCSS_ library
- an _Elm_ ui kit 
- a _React_ ui kit
```

2022-02-07 14:31 UTC, alessiosantangelo commented on README.md
> +Here's a full list of packages that we support in this repo.
```suggestion

```

2022-02-07 14:31 UTC, alessiosantangelo commented on README.md
> +To allow you to make the best use of the Design System and its APIs we have structured 3 documentation:
```suggestion
You can take a look at our live-documentation by following:
```

2022-02-07 14:31 UTC, alessiosantangelo commented on README.md
> +- [Elmbook](https://elm-staging.prima.design/buttons) — A documentation about the usage of components made in Elm.
```suggestion
- [SCSS documentation](https://scss-staging.prima.design/)
- [React documentation](https://react-staging.prima.design/)
- [Elm documentation](https://elm-staging.prima.design/) 
```

2022-02-07 14:31 UTC, alessiosantangelo commented on README.md
> +Run the following to setup your local dev environment:
```suggestion
Run the following commands to setup your local dev environment:
```

2022-02-07 14:31 UTC, alessiosantangelo commented on README.md
> +# Launch Elmbook
```suggestion
# Run Elm live-documentation dev server
```

2022-02-07 14:31 UTC, alessiosantangelo commented on README.md
> +```
```suggestion
### Generate icons
Pyxis also includes a repository which contains all icons in svg `@pyxis/icons`, we provide a script to turn icons into components within React and Elm. 

 You can generate icons by running the following command:
```sh
yarn generate:icons
```
```

2022-02-07 14:31 UTC, alessiosantangelo commented on README.md
> +```
```suggestion
### Generate Design Tokens
Pyxis foundations is a set of constants obtained by the Design Token entities. 

To generate fresh tokens, run the following command:
```sh
yarn tokens:build
```
```

2022-02-07 14:59 UTC, emanuelemacri commented on package.json
> +    "generate:icons": "lerna run generate:icons --stream",
Ok, non qui, ma lo terrei a mente per quando effettivamente facciamo i primi test di pubblicazione

2022-02-07 15:07 UTC, emanuelemacri commented on README.md
> +| Package name                               | Description                                                                                           |
La tabella la terrei, mi sembra molto utile per capire com'è strutturato il monorepo, mergio però con la parte sopra, che in effetti diventa così poco utile

2022-02-07 15:13 UTC, emanuelemacri commented on README.md
> +- [Elmbook](https://elm-staging.prima.design/buttons) — A documentation about the usage of components made in Elm.
Non sarebbe meglio spiegare un minimo cosa c'è all'interno?

2022-02-07 15:18 UTC, emanuelemacri commented
@alessiosantangelo @Gsciarra @lauratrapani qui un [esempio](https://github.com/primait/pyxis/tree/PRIMA-12284/task/add-readme-md)

2022-02-07 15:35 UTC, alessiosantangelo commented on README.md
> +| [`@pyxis/scss`](./packages/pyxis-scss)     | Pyxis foundations and components realize in SCSS. This is the base repository for working with Pyxis. |
```suggestion
| [`@pyxis/scss`](./packages/pyxis-scss)     | SCSS foundations and components documentation |
```

2022-02-07 15:36 UTC, alessiosantangelo commented on README.md
> +| [`@pyxis/elm`](./packages/pyxis-elm)       | Pyxis Elm components and Elmbook Documentation.                                                       |
```suggestion
| [`@pyxis/elm`](./packages/pyxis-elm)       | Elm components and Elmbook documentation.                                                       |
```

2022-02-07 15:39 UTC, alessiosantangelo commented on README.md
> +| [`@pyxis/icons`](./packages/pyxis-icons)   | A collection of icons in svg used in our Design System.                                               |
```suggestion
| [`@pyxis/icons`](./packages/pyxis-icons)   | A collection of SVG icons used in our Design System.                                               |
```

2022-02-07 15:41 UTC, alessiosantangelo commented on README.md
> +Run Elm live-documentation dev server
```suggestion
# Run Elm live-documentation dev server
```

2022-02-07 15:41 UTC, alessiosantangelo commented on README.md
> +Pyxis also includes a repository which contains all icons in svg `@pyxis/icons`, we provide a script to turn icons into components within React and Elm.
```suggestion
Pyxis also includes a repository, `@pyxis/icons`, which contains all our SVG icons. We provided a script to turn icons into components within React and Elm.
```

2022-02-07 15:54 UTC, emanuelemacri commented on README.md
> +- [Elmbook](https://elm-staging.prima.design/buttons) — A documentation about the usage of components made in Elm.
Ok, allora per ora qui lascio solo i link, poi spieghiamo meglio nei singoli sotto progetti cosa contengono le doc

2022-02-08 08:30 UTC, alessiosantangelo approved these changes
Sicuramente possiamo migliorare un po' l'inglese (anche le correzioni che ho suggerito io non sono fantastiche) e magari nel tempo cambieremo un po' la struttura dei vari readme, ma per ora può andare più che bene :)

2022-02-08 08:30 UTC, merged