[PRIMA-12321]: [Pyxis Elm] Implement the select API
primait/pyxis pull request #67
Opened 2022-02-11 08:36 UTC by ascandone

https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/PRIMA-12321

2022-02-11 09:02 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Select.elm
> +            if keyCode == spaceKeyCode then
Puoi usare `ifThenMap` dal modulo https://github.com/primait/prima-elm-extra

2022-02-11 09:05 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Select.elm
> +        [ Html.label
La funzione di rendering è un po' troppo complicata da leggersi. 

Splittiamola così: 
- una funzione che stampa la select mobile
- una che stampa la select custom 
- una che stampa una singola option mobile 
- una che stampa una singola option custom

2022-02-11 09:06 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Lens.elm
> +module Lens exposing
Questo modulo si utilizza solo nei tests, quindi lo piazzerei in quello scope in maniera da non sporcare il source code di Pyxis

2022-02-11 09:06 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Select.elm
> +type Select a
Eravamo rimasti che per il momento avremmo usato solo il  `Model`

2022-02-11 09:07 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Select.elm
> +withOptions : List (Option a) -> Select a -> Select a
Mancano tutti i docs e l'ordinamento degli exposings

2022-02-11 09:08 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Select.elm
> +                    ]
Occhio a questi

2022-02-11 09:26 UTC, ascandone reviewed
E' ancora in draft quindi ci sono alcune cose temporanee perché non pensavo sarebbe stata letta
Es. alcuni pezzi non seguono le guidelines di prima perché stavo prototipando come fare funzionare certe cose e non aveva senso fare delle utility per cose che ho cambiato diverse volte

Adesso adattare all'API che decidiamo dovrebbe essere una questione abbastanza veloce, e dopo quello metto i docs dell'API che abbiamo decisa che è pubblica, e mando in review

2022-02-11 09:26 UTC, ascandone commented on packages/pyxis-elm/src/Components/Select.elm
> +                    ]
Copiato da [qua](https://react-staging.prima.design/?path=/story/components-select-%F0%9F%9A%A7-overview--page) (la parte show code)
E' sbagliato?

2022-02-11 09:28 UTC, ascandone commented on packages/pyxis-elm/src/Components/Select.elm
> +type Select a
Avevo capito che ne avremmo parlato oggi con Giampiero
Ho diviso perché unirli una volta che hai modellato la separazione è istantaneo, il contrario no

2022-02-11 10:20 UTC, ascandone commented on packages/pyxis-elm/src/Components/Select.elm
> +type Option a
Questo era in TODO, però gia che ci siamo volevo chiedere:

# 1

Le casistiche che mi vengono in mente sono due:

**1** Le opzioni sono sincrone/hardcoded.

In quel caso sarebbe una cosa del tipo:
```elm
Select.create
  |> Select.withOptions
     [ Select.option ArtigianoCommerciante "ARTIGIANO_COMMERCIANTE"  "Artigiano / Commerciante" 
     ]
```

vs

```elm

-- Pattern matching abbastanza lunghi
mapOccupationValue = ... -- a volte questo potrebbe essere già implementato dal codegen di graphql
mapOccupationLabel = ...

Select.create mapOccupationValue mapOccupationLabel
  |> Select.withOptions
     [ Select.option ArtigianoCommerciante
     ]
```

**2** Le opzioni mi arrivano dal server in un modo tipo: 
```json
{
"occupation": [
    {
      "id": "IMPIEGATO_QUADRO_DIRIGENTE",
      "label": "Impiegato / Quadro / Dirigente"
    },
  ...
  ]
}
```

In quel caso viene:

```elm
-- In questo caso sarebbe probabilmente utile una
-- Select.stringOption value label = Select.option value value label

Select.create
  |> Select.withOptions
     (List.map (\occ -> Select.option occ.id occ.id occ.label) occupations)
```

vs

```elm
mapOccupationValue = identity

-- Dovrei iterare sulle occupations fetchate e trovare quella con quell'id?
-- (E fare un Maybe.withDefault forzato per far tornare String)
-- O c'è un modo più semplice?
mapOccupationLabel = ??

Select.create mapOccupationValue mapOccupationLabel
  |> Select.withOptions  (List.map (\occ -> Select.option occ.id) occupations)

```

In entrambi i casi mi sembra più ergonomico mettere i valori inline
Anche nel caso (come spesso succede) che la funzione `mapOptionValue` sia già implementata (es. perché viene riusata altrove) la prima API va bene comunque

Un altro side effect della seconda API è che per ogni elemento deve iterare su tutti gli elementi per trovare la label, un'altra volta per trovare il value, il tutto due volte (perché c'è sia mobile che desktop da calcolare)
Quindi sarebbe inutilmente O(n**2) anziché O(n)
Non mi aspetto che crei chissa quale problema di performance, ma significa che in una pagina con una manciata di select (che _non_ sono  `Html.Lazy`zzabili, per vari motivi), ogni input immesso (di ogni componente del form)  dietro le quinte deve iterare un if centianaia di volte vs decine
(Comunque la questione della perf mi sembra meno rilevante)

C'è qualche caso d'uso che non mi viene in mente, o comunque un motivo in particolare per cui stai preferendo la seconda? Un motivo che mi viene in mente è che spesso il `mapOptionValue` è già implementato, però mi sembra di vedere in giro che non è sempre così (es. `{ code = "Z106", name = "Città del Vaticano" }`)

# 2
Ma il value distinto dal valore mostrato su schermo, serve proprio? Ho effettivamente la sensazione che serva, ma in realtà non saprei dire il motivo
C'è qualche motivo a livello di accessibilità/funzionamento che lo rende obbligatorio (anziché usare il valore che viene mostrato su schermo)?

2022-02-11 11:25 UTC, ascandone commented on packages/pyxis-elm/src/Components/Select.elm
> +            if keyCode == spaceKeyCode then
Tra poco ci dovranno essere una serie di if/else per gli altri keycode
Mi pare che non si possa fare con quel combinatore

2022-02-14 14:37 UTC, ascandone commented
I docs sono un po' "bare minimum" ed andranno aggiunti esempi più esaustivi del funzionamento, per due motivi:
1. La prossima card è quella dell'accessibilità, e potrebbe uscire qualche requisiti tecnico che cambi in modo più o meno significativo la segnatura dell'api
2. Attualmente non riesco a far girare la preview dei docs, da errore legati ad altri moduli. Ho provato a sistemare il tutto ma stava andando troppo fuori scope

2022-02-14 14:49 UTC, ascandone commented
Altra precisazione:

per ora ho messo l’api del tipo
```elm
|> Select.withOptions
  [ Select.option { value = "DEVELOPER", label = "Developer" }
  , ...
  ]
```

anzichè
```elm
Select.create { mapToLabel = occupationToString }
|> Select.withOptions
  [ Select.option "DEVELOPER"
  , ...
  ]
```

Questo perché la seconda mi usava scomoda da usare nel caso arrivi da remoto una cosa del tipo `[ { name: "Italia", code: "ITA" }, ... ]`

Fatemi sapere se comunque è preferibile la seconda

2022-02-14 14:50 UTC, ascandone commented on packages/pyxis-elm/src/Components/Select.elm
> +                    ]
@emanuelemacri ti taggo per sicurezza

2022-02-14 15:10 UTC, alessiosantangelo requested changes

2022-02-14 15:10 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Select.elm
> +    , Msg, Size, option, render, renderWithCtx
Questo significa che ti sei dimenticato di referenziare alcuni docs

2022-02-14 15:10 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Select.elm
> +type alias ModelConfig ctx a =
Questo va definito dopo il tipo `Model` visto che è un sottotipo

2022-02-14 15:10 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Select.elm
> +    Medium
Per ora continuiamo a prendere le sizes dal tipo generico

2022-02-14 15:10 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Select.elm
> +update : Msg -> ModelWithCtx ctx a -> ( ModelWithCtx ctx a, Cmd Msg )
Perchè ritorna un `Cmd`?

2022-02-14 15:10 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Select.elm
> +init : (Maybe String -> Result String a) -> Model a
Perchè devo dare una validazione alla creazione del Model?

2022-02-14 15:10 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Select.elm
> +        { selectedValue = Nothing
Chiamiamolo `value` come per gli altri fields

2022-02-14 15:10 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Select.elm
> +{-| -}
Docs

2022-02-14 15:10 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Select.elm
> +initWithCtx : (ctx -> Maybe String -> Result String a) -> ModelWithCtx ctx a
Perchè ci sono due diverse funzioni di inizializzazione?

2022-02-14 15:10 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Select.elm
> +        [ Html.label
Anche qui perchè ci sono due diverse render?

2022-02-14 15:10 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Select.elm
> +                    [ Commons.Render.renderMaybe (Maybe.map Html.text select.placeholder) ]
Usa i pipe

2022-02-14 15:10 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Select.elm
> +            , viewErrorMessage (getUiError ctx model)
Pipe

2022-02-14 15:10 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Select.elm
> +                [ IconSet.ChevronDown |> Icon.create |> Icon.render ]
Pipe verticale

2022-02-14 15:10 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Select.elm
> +viewErrorMessage : Result String () -> Html msg
Questa parte andrebbe estratta da qui, l'abbiamo riscritta uguale per ogni componente. Facciamone una funzione di utility distribuita

2022-02-14 15:10 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Select.elm
> +viewNativeOption : Option -> Html msg
Mancano tutti i docs

2022-02-14 15:10 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Select.elm
> +spaceKeyCode : Int
Questo dovrebbe appartenere ad un modulo `Commons.Events.KeyCode`

2022-02-14 15:10 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Select.elm
> +            , Commons.Attributes.renderAttributeIf (not select.isMobile && not select.disabled) (Html.Events.onClick ClickedLabel)
Usa i pipe

2022-02-14 15:10 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Select.elm
> +                , Attributes.classList select.classList
Ordiniamo un po' le cose qui: prima gli attributi statici, poi gli eventi

2022-02-14 15:21 UTC, ascandone commented on packages/pyxis-elm/src/Commons/Attributes.elm
> +    , renderAttributeIf
Ah a quanto pare non si può fare sintatticamente
Suggerisco uno tra:
* `Commons.Attibutes.renderIf`
* `Commons.Attibutes.when`
* `Commons.Attibutes.guard`

2022-02-14 15:25 UTC, ascandone commented on packages/pyxis-elm/src/Components/Select.elm
> +viewNativeOption : Option -> Html msg
Questa sono interne, vanno messi comunque?

2022-02-14 15:36 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Commons/Attributes.elm
> +    , renderAttributeIf
Allora `Commons.Attibutes.renderIf` va benissimo

2022-02-14 15:37 UTC, ascandone commented on packages/pyxis-elm/src/Components/Select.elm
> +            , Commons.Attributes.renderAttributeIf (not select.isMobile && not select.disabled) (Html.Events.onClick ClickedLabel)
Così? 
```elm
Html.Events.onClick ClickedLabel |> Commons.Attributes.renderIf (not select.isMobile && not select.disabled)
```

2022-02-14 15:37 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Select.elm
> +viewNativeOption : Option -> Html msg
Si, con il commento `{- Internal. -}`

2022-02-14 15:39 UTC, ascandone commented on packages/pyxis-elm/src/Components/Select.elm
> +update : Msg -> ModelWithCtx ctx a -> ( ModelWithCtx ctx a, Cmd Msg )
Scritto sopra: probabilmente (spero) andrà levato, lasciato la versione complessa perché magari nella parte di accessibilità serve anche il cmd
Nel caso non serva dovrebbe essere una cosa veloce levarlo e fixare le dipendenze
Però se serve levo subito

2022-02-14 15:51 UTC, ascandone commented on packages/pyxis-elm/src/Components/Select.elm
> +initWithCtx : (ctx -> Maybe String -> Result String a) -> ModelWithCtx ctx a
C'è una versione semplificata per quando la validazione non coinvolge altri campi (quindi quando il ctx è `()`)
Ho pensato potesse essere utile per ridurre la barriera d'ingresso e semplificare il caso comune, non so se nel pratico il 99% delle validazioni coinvolge altri fields e quindi tanto valga lasciare solo la versione più generale

2022-02-14 16:05 UTC, ascandone commented on packages/pyxis-elm/src/Components/Select.elm
> +        [ Html.label
(come sopra)

2022-02-14 16:17 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Select.elm
> +init : (Maybe String -> Result String a) -> Model a
Non ti ho chiesto _come si usa la validazione_ ma _perchè non posso creare uno State/Model senza passare la validazione_?

2022-02-14 16:18 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Select.elm
> +initWithCtx : (ctx -> Maybe String -> Result String a) -> ModelWithCtx ctx a
Ma la funzione `init` copre un solo caso semplicissimo che difficilmente si verificherà. Invece abbiamo sempre detto che le api devono essere coerenti tra i vari fields e questo qui non lo sarebbe

2022-02-14 16:35 UTC, ascandone commented on packages/pyxis-elm/src/Components/Select.elm
> +init : (Maybe String -> Result String a) -> Model a
Ah, per quello basta un

`Select.init Ok`

E il model avrà tipo `Select.Model (Maybe String)` (che è corretto)

2022-02-14 16:35 UTC, ascandone commented on packages/pyxis-elm/src/Components/Select.elm
> +initWithCtx : (ctx -> Maybe String -> Result String a) -> ModelWithCtx ctx a
Ok, sistemo

2022-02-14 16:43 UTC, ascandone commented on packages/pyxis-elm/src/Components/Select.elm
> +initWithCtx : (ctx -> Maybe String -> Result String a) -> ModelWithCtx ctx a
Fatto

2022-02-15 08:16 UTC, ascandone commented on packages/pyxis-elm/src/Components/Select.elm
> +init : (Maybe String -> Result String a) -> Model a
Comunque si può anche fare

Un'api possibile è:
```elm
init: Model ctx (Maybe String)
-- (forse setValidation è più chiaro?)
withValidation : (ctx -> Maybe String -> Result String a) -> Model ctx x -> Model ctx a
```
Però mi sembra una semantica meno chiara (poi perché la validazione dovrebbe essere opzionale? Più che validazione si tratta di un parsing, cioè un mapping dal tipo raw alla rappresentazione desiderata)

(un downside interno è che non si può usare il record update ma va ricreato tutto il record, con tutti i campi tranne uno uguali a quello precedente
Ma non fa niente)

2022-02-15 09:04 UTC, alessiosantangelo requested changes

2022-02-15 09:04 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Field/Select.elm
> +@docs getValue, getValueFromCtx
Questa non esiste più `getValueFromCtx`

2022-02-15 09:04 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Field/Select.elm
> +@docs render
Qui i docs sono sbagliati

2022-02-15 09:04 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Field/Select.elm
> +        -- Select attributes
Questo possiamo rimuoverlo. Metti le chiavi in ordine alfabetico

2022-02-15 09:04 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Field/Select.elm
> +    { value : Maybe String
Chiavi in ordine alfabetico

2022-02-15 09:04 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Result/Extra.elm
> +void : Result error value -> Result error ()
Docs

2022-02-15 09:15 UTC, ascandone commented on packages/pyxis-scss/src/scss/components/forms/dropdown.scss
> +.form-field__dropdown__item--hover {
Scritto in pair con @emanuelemacri 
Serve per la keyboard navigation

2022-02-15 09:17 UTC, ascandone commented on packages/pyxis-elm/src/Components/Field/Select.elm
> +    { value : Maybe String
Ah... ma quindi dovrò riordinare anche tutti gli altri? Negli altri component non c'erano chiavi in ordine alfabetico

2022-02-15 09:21 UTC, ascandone commented on packages/pyxis-elm/src/Components/Field/Internal.elm
> +viewErrorMessage : { r | errorMessage : Maybe String, id : Maybe String } -> Html.Html msg
Era per estrarre il boilerplate del `errorMessage |> Maybe.map (\ err -> viewErrorMessage {errorMessage = err, id = id }) |> renderMaybe`
Allora lo rendo plain `String`
(mentre l'id va tenuto maybe perché in generale non è obbligatorio)

2022-02-15 09:23 UTC, ascandone commented on packages/pyxis-elm/src/Components/Field/Input.elm
> +        , Internals.viewErrorMessage
Non era perché ci sono tanti parametri, è perché ci sono due parametri dello stesso tipo (e per renderlo più leggibile)
Comunque lo cambio

2022-02-15 09:38 UTC, ascandone commented on packages/pyxis-elm/src/Components/Field/Input.elm
> +import Components.Field.Internal as Internals
Fatto, anche se fare un modulo intero per una funzione che renderizza un singolo div mi sembra overkill
Avrei più fatto un singolo modulo (in haskell è idiomatico `Internal`) delle funzioni private condivise da quel namespace, ed estratto in futuro moduli qualora fosse necessario

2022-02-15 10:57 UTC, alessiosantangelo approved these changes

2022-02-15 10:57 UTC, merged