[DS-18]: [Pyxis Elm] Implement the input radio
primait/pyxis pull request #68
Opened 2022-02-11 08:46 UTC by Gsciarra

https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/DS-18

2022-02-11 08:59 UTC, lauratrapani commented on packages/pyxis-elm/src/Components/Field/Radio.elm
> +        [ Html.label
Ma perchè non hai usato il componente Label? e poi non sarebbe meglio fare il componente radio (input + label) e poi il componente group, visto che sostanzialmente il wrapper più elementi radio sarà uguale a quello di più elementi checkbox?

2022-02-11 08:59 UTC, lauratrapani commented on packages/pyxis-elm/src/Components/Field/Radio.elm
> +        [ Attributes.classList [ ( "form-control-group", True ) ]
Perchè due volte `form-control-group`?

2022-02-11 09:41 UTC, Gsciarra commented on packages/pyxis-elm/src/Components/Field/Radio.elm
> +        [ Attributes.classList [ ( "form-control-group", True ) ]
Nella documentazione è così

2022-02-16 09:44 UTC, emanuelemacri requested changes

2022-02-16 09:44 UTC, emanuelemacri commented on packages/pyxis-elm/src/Components/Field/RadioGroup.elm
> +            [ Attributes.classList ([ ( "form-control-group", True ) ] ++ classList)
Bisogna aggiungere uno stato (e una classe) per visualizzare i radio in verticale:
`form-control-group--column`

2022-02-16 09:44 UTC, emanuelemacri commented on packages/pyxis-elm/src/Components/Field/RadioGroup.elm
> +create : String -> (Msg value -> msg) -> value -> Model value ctx msg
Commentiamo tutti i tipi e le funzioni (anche interne)

2022-02-16 09:44 UTC, emanuelemacri commented on packages/pyxis-elm/src/Stories/Chapters/RadioGroup.elm
> +<component with-label="RadioGroup" />
Aggiungiamo anche gli esempi di:
- RadioGroup in verticale
- RadioGroup con errore
- RadioGroup disabilitato

2022-02-17 15:06 UTC, ascandone requested changes

2022-02-17 15:07 UTC, ascandone commented
Ho commentato varie cose ma valuta te quali c'è bisogno di cambiare

2022-02-17 15:20 UTC, Gsciarra commented on packages/pyxis-elm/src/Components/Field/RadioGroup.elm
> +    { errorMessage : Maybe String
Come detto nella call di oggi, la gestione di quando mostrare l'errore è un'implementazione futura.

2022-02-17 15:21 UTC, Gsciarra commented on packages/pyxis-elm/src/Components/Field/RadioGroup.elm
> +    , status : FieldStatus.StatusList
Intendi `status`? Avrebbe senso eliminarlo per il momento, dato che non viene mai utilizzato.

2022-02-17 15:21 UTC, Gsciarra commented on packages/pyxis-elm/src/Components/Field/RadioGroup.elm
> +type Configuration value
Si, già corretti dopo la call di oggi.

2022-02-17 15:22 UTC, Gsciarra commented on packages/pyxis-elm/src/Components/Field/RadioGroup.elm
> +type Msg value
Si, è per la signature di OnCheck. Per me ci sta usare `always (OnCheck value)`

2022-02-17 15:23 UTC, Gsciarra commented on packages/pyxis-elm/src/Components/Field/RadioGroup.elm
> +withVerticalLayout : Bool -> Configuration value -> Configuration value
Non ho preferenze a riguardo. @alessiosantangelo

2022-02-17 15:26 UTC, Gsciarra commented on packages/pyxis-elm/src/Components/Field/RadioGroup.elm
> +viewRadio : String -> Maybe String -> value -> Bool -> Maybe String -> Option value -> Html.Html (Msg value)
Si, la firma è terribile ma non mi è venuto in mente un modo veramente pulito per farlo. L'extensible type mi sembra già un miglioramento. @alessiosantangelo

2022-02-17 15:29 UTC, Gsciarra commented on packages/pyxis-elm/src/Components/Field/RadioGroup.elm
> +        (CA.compose
Mi sembra si fosse già detto che `Common.Attributes.maybe` rendesse il codice più chiaro, quindi implementerei io quello.

2022-02-17 15:35 UTC, ascandone commented on packages/pyxis-elm/src/Components/Field/RadioGroup.elm
> +    , status : FieldStatus.StatusList
Si, status
Così si semplifica un po' il codice visto che è un'invariante da mantenere

2022-02-18 15:09 UTC, alessiosantangelo requested changes

2022-02-18 15:09 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Field/RadioGroup.elm
> +withAriaLabelledby : String -> Configuration value -> Configuration value
Docs

2022-02-18 15:09 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Field/RadioGroup.elm
> +        (CA.compose
Si anche io pensionerei `compose` per usate `Commons.Attributes.maybe`

2022-02-18 15:09 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Field/RadioGroup.elm
> +            ++ [ Maybe.map (viewError configuration.id) model.errorMessage |> CR.renderMaybe ]
Qui puoi usare il pipe anche sul Maybe.map

2022-02-18 15:09 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Field/RadioGroup.elm
> +validate ctx ((Model { selectedValue, validation }) as model) =
Teniamola ma trasformiamola nella funzione che ci ritorna il valore post-validazione (ex. `getValidatedValue`) https://github.com/primait/pyxis/blob/master/packages/pyxis-elm/src/Components/Field/Input.elm#L454

2022-02-18 15:09 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Field/RadioGroup.elm
> +setValue : value -> Model value ctx -> Model value ctx
Docs anche qui

2022-02-18 15:09 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Field/RadioGroup.elm
> +resultToErrorMessage result =
Non credo serva più visto che c'è [il componente](https://github.com/primait/pyxis/blob/master/packages/pyxis-elm/src/Components/Field/Error.elm)

2022-02-18 15:54 UTC, ascandone commented on packages/pyxis-elm/src/Components/Field/RadioGroup.elm
> +isValid ctx (Model { validation, selectedValue }) =
Se vuoi stringere un po' di più puoi mettere Result.Extra.isOk (validation ctx selectedValue)

2022-02-18 15:55 UTC, ascandone commented on packages/pyxis-elm/src/Components/Field/RadioGroup.elm
> +            )
Graficamente mi sa che viene un po' più pulito se fai:
```elm
Attributes.classList
  [ ( "form-control-group", True )
  , ( "form-control-group--column", configuration.layout == Vertical )
  ]
, Attributes.classList configuration.classList
```
, che si comporta allo stesso modo

2022-02-22 11:30 UTC, alessiosantangelo requested changes
Due cavolatine, il resto è ok

2022-02-22 11:30 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Field/RadioGroup.elm
> +isValid ctx (Model { validation, selectedValue }) =
Visto che questa funzione non esiste negli altri moduli, se la aggiungi qui fallo anche per gli altri fields per favore.

2022-02-22 11:30 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Field/RadioGroup.elm
> +viewRadio { id, name, isDisabled } selectedValue isValueValid (Option { value, label }) =
Giusto per mantenere la nomenclatura: `renderRadio`

2022-02-22 11:30 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Field/RadioGroup.elm
> +viewLabel label id =
Giusto per mantenere la nomenclatura: `renderLabel`

2022-02-22 12:17 UTC, alessiosantangelo approved these changes

2022-02-22 12:17 UTC, merged