[DS-39]: [Pyxis Scss] Implement form item
primait/pyxis pull request #72
Opened 2022-02-16 10:10 UTC by lauratrapani

https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/DS-39

Implementig `form-item` class, removing absolute positioning on error message.

2022-02-16 17:08 UTC, emanuelemacri requested changes

2022-02-16 17:08 UTC, emanuelemacri commented on packages/pyxis-react/src/stories/components/TextField/TextField.tsx
> +      {hint && <div className="form-item__hint" id="hint">Hint</div>}
Anche se è un implementazione provvisoria metterei il controllo sull'hint:
```
{hint && !error && <div className="form-item__hint" id="hint">Hint</div>}
```
(anche sugli altri componenti)

2022-02-16 17:08 UTC, emanuelemacri commented on packages/pyxis-react/src/stories/components/Textarea/TextArea.stories.tsx
> +
Dato che abbiamo le storie delle hint forse aggiungerei già in questa card l'esempio dell'hint nell'Overview dei vari componenti. Forse il posto migliore (per non creare un altra sezione apposita) è nella tabella degli `state`, sotto l'errore, che dici?

2022-02-16 17:11 UTC, lauratrapani commented on packages/pyxis-react/src/stories/components/Textarea/TextArea.stories.tsx
> +
Non è propriamente uno state ma come soluzione provvisoria può andare

2022-02-17 11:46 UTC, emanuelemacri approved these changes
🤟

2022-02-18 10:25 UTC, alessiosantangelo approved these changes

2022-02-18 10:25 UTC, merged