[DS-13]: [Pyxis Elm] Implement the select accessibility
primait/pyxis pull request #75
Opened 2022-02-16 16:44 UTC by ascandone

https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/DS-13

2022-02-21 16:35 UTC, alessiosantangelo requested changes
Ci sono una marea di conflitti da risolvere

2022-02-21 16:35 UTC, alessiosantangelo commented on packages/pyxis-elm/src/List/Extra.elm
> +module List.Extra exposing (find, findNext, findPrevious, last, paired, withPreviousAndNext)
Abbiamo già installato `List.Extra`

2022-02-21 16:35 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Field/Select.elm
> +    Browser.Dom.focus >> Task.attempt (\_ -> FocusedSelect)
```suggestion
    Browser.Dom.focus >> Task.attempt (always FocusedSelect)
```

2022-02-21 16:35 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Field/Select.elm
> +        ( FocusedItem _, _ ) ->
Come ti ho già detto almeno altre 3 volte non è questo il modo in cui scriviamo l'update.

Usa `prima-elm-extra` per fare `ifThenMap`. Il case va fatto solo sul `msg`

2022-02-21 16:35 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Field/Select.elm
> +config : { isMobile : Bool, id : String } -> Config
```suggestion
config : Bool -> String -> Config
```

2022-02-21 16:35 UTC, alessiosantangelo commented on packages/pyxis-elm/tests/ListExtraTest.elm
> +import Expect
Avendo `List.Extra` questa si può buttare

2022-02-21 16:35 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Field/Select.elm
> +    | Blurred { id : String }
```suggestion
    | Blurred String
```

2022-02-21 16:35 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Field/Select.elm
> +    { r | dropDownState : DropDownState, value : Maybe String }
Questo non è il `Model`?

2022-02-21 16:41 UTC, ascandone commented on packages/pyxis-elm/src/Components/Field/Select.elm
> +        ( FocusedItem _, _ ) ->
Non basta fare un if, è un pattern match su dropDownState (a cui in effetti dovrei levare la D maiuscola btw)
Posso fare un pattern match interno ogni volta, se pensi sia più leggibile
Però diventa tutto più verboso

2022-02-21 16:44 UTC, ascandone commented on packages/pyxis-elm/src/Components/Field/Select.elm
> +config : { isMobile : Bool, id : String } -> Config
Ora lo metto così, però poi quando hai una firma `Bool -> String -> Config` e ti devi ogni volta andare a riguarda sulla documentazione cosa significa la String (valore iniziale? id?) mi sembra un po' scomodo
Vale anche per gli altri appunti della review, non capisco cosa ci sia di male a usare i record, in generale

2022-02-21 16:45 UTC, ascandone commented on packages/pyxis-elm/tests/ListExtraTest.elm
> +import Expect
Mh qualcosa sarà duplicata, ora controllo, però non posso buttarlo perché ci sono funzioni molto specifiche che uso per il select
Però allora devo cambiare namespace, `Commons.List` va bene ?

2022-02-21 16:46 UTC, ascandone commented on packages/pyxis-elm/src/Components/Field/Select.elm
> +    { r | dropDownState : DropDownState, value : Maybe String }
Si, però così invece di passare tutto il record si vedeva dalla segnatura quali argomenti servivano
Correggo

2022-02-21 16:55 UTC, ascandone commented
Ahia mi sembrava di avere risolto i conflitti ma devo aver fatto casini con l'IDE
Domani mattina sistemo il rebase

2022-02-22 09:34 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Field/Select.elm
> +config : { isMobile : Bool, id : String } -> Config
Perchè abbiamo detto che ogni componente deve avere la stessa firma e se ogni volta che ne sviluppiamo uno nuovo iniziamo ad aggiungere uno standard diverso allora non si parla più di standard.

Inoltre quel `Bool` come abbiamo detto è un dato provvisorio che dovremo gestire in modo diverso.

2022-02-22 09:37 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Field/Select.elm
> +        ( FocusedItem _, _ ) ->
Il pattern matching lo puoi benissimo fare anche in delle funzioni invocate dall'update. Quello che mi interessa è che venga mantenuto lo standard di scrittura, e il nostro standard prevede che la funzione di update sia estremamente chiara e facile da leggere. Per farlo ci avvaliamo di piccole funzioni componibili tra loro che esprimono il cambiamento che avviene nel model.

2022-02-22 10:36 UTC, ascandone commented on packages/pyxis-elm/src/Components/Field/Select.elm
> +        ( FocusedItem _, _ ) ->
Ok quindi una cosa del genere?

```elm
update msg =
  case msg of
     ClickedLabel pointerEvent ->
        handleClickedLabel pointerEvent.pointerType model
   ...

handleClickedLabel : Maybe Commons.Events.PointerType -> Model ctx a -> PrimaUpdate.PrimaUpdate (Model ctx a) msg
handleClickedLabel pointerType ((Model { dropDownState }) as model) =
    case dropDownState of
        Closed ->
            case Maybe.withDefault Commons.Events.Mouse pointerType of
                Commons.Events.Mouse ->
                    model
                        |> setIsOpen True
                        |> PrimaUpdate.withoutCmds

                _ ->
                    model
                        |> PrimaUpdate.withoutCmds

        _ ->
            model
                |> PrimaUpdate.withoutCmds
```

giusto?

2022-02-22 10:38 UTC, ascandone commented on packages/pyxis-elm/src/Components/Field/Select.elm
> +config : { isMobile : Bool, id : String } -> Config
Va bene, allora appena posso comincio anche a segnare nella wiki anche le convenzioni sugli argomenti di config così ci allineiamo sullo stesso ordine degli argomenti, ecc

2022-02-22 10:50 UTC, ascandone commented on packages/pyxis-elm/src/Components/Field/Select.elm
> +    | Blurred { id : String }
Questo vale per tutti quanti i costruttori? E quindi in generale come regola generale (cioè i messages devono avere sempre argomenti posizionali e mai "labeled"?)
Ma così come faccio a far capire cosa rappresenta quella string che viene data al costruttore? Metto un commento là in mezzo ai Msg?
Oppure posso semplicemente creare un alias di quel record e passare quello?

2022-02-22 11:50 UTC, alessiosantangelo requested changes

2022-02-22 11:50 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Field/Select.elm
> +        ( FocusedItem _, _ ) ->
No, una cosa simile: 
```elm
update : Msg -> Model ctx a -> ( Model ctx a, Cmd Msg )
update msg model = 
   case msg of 
       ClickedLabel pointerEvent ->
          model 
             |> setClickedLabel pointerEvent
             |> PrimaUpdate.withoutCmds
             
       Blurred id ->
           model 
              |> setBlurred 
              |> PrimaUpdate.withoutCmds
              
       ....

```

In sostanza fai pattern matching solo sul `msg`, dopodichè fai una funzione _a parte e fuori dall'update_ la quale riceve il model ed eventuali altri metadati se necessari. 

In questo modo: 
- ogni funzione dipende dal model, esprime cosa fa e non come lo fa
- non si utilizzano riferimenti "obsoleti" al model nel senso che questo non viene destrutturato all'inizio e non ci si basa su dei dati che possono essere stati modificati all'interno della pipeline di update 
- la funzione di update è molto espressiva 
- le funzioni che vengono invocate dentro model sono riutilizzabili 
- meno overhead cognitivo per leggere il codice

2022-02-22 11:50 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Field/Select.elm
>      { blurredAtLeastOnce : Bool
Questo abbiamo detto che non serve più

2022-02-22 11:50 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Field/Select.elm
> +    , isBlurringInternally : Bool
Suppongo anche questo

2022-02-22 11:50 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Field/Select.elm
> +viewDropdownItem { dropDownState, value } (Config configData) ( previous, ( index, Option option_ ), next ) =
```suggestion
renderDropdownItem :
    ModelData ctx a
    -> Config
    -> ( ( Int, Option ), ( Int, Option ), ( Int, Option ) )
    -> Html Msg
renderDropdownItem { dropDownState, value } (Config configData) ( previous, ( index, Option option_ ), next ) =
```

2022-02-22 11:50 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Field/Select.elm
> +viewError id error =
```suggestion
renderError : String -> String -> Html msg
renderError id error =
```

2022-02-22 11:50 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Field/Select.elm
> +viewDropdownWrapper (Model model) (Config select) =
```suggestion
renderDropdownWrapper : Model ctx x -> Config -> Html Msg
renderDropdownWrapper (Model model) (Config select) =
```

2022-02-22 12:48 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Field/Select.elm
> +    | Blurred { id : String }
No vale solo per i costruttori che accettano un solo parametro, infatti il costruttore `SelectKeyDown` va bene così com'è in quanto ha due parametri di cui uno è un record.

2022-02-22 12:49 UTC, ascandone commented on packages/pyxis-elm/src/Components/Field/Select.elm
> +    | Blurred { id : String }
Ok, quindi per documentare il significato di quell'argomento String che faccio? Metto semplicemente un commento là allora?

2022-02-22 14:01 UTC, ascandone commented on packages/pyxis-elm/src/Components/Field/Select.elm
> +    , isBlurringInternally : Bool
Nono questo è un'altra cosa, fa parte dei vari hack per gestire keyboard nav

2022-02-22 14:59 UTC, merged