[DS-43]: [Pyxis Elm] Implement the Message component
primait/pyxis pull request #78
Opened 2022-02-18 15:38 UTC by lauratrapani

https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/DS-43

Implementing Message component in Elm

2022-02-21 11:13 UTC, alessiosantangelo requested changes

2022-02-21 11:13 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Message.elm
> +    = Model (Configuration msg)
Nella nuova convenzione che abbiamo stabilito questo tipo di configurazione, che riguarda solo la vista si deve chiamare `Config`.

```suggestion
type Config msg
    = Config (ConfigData msg)
```

2022-02-21 11:13 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Message.elm
> +    , customIcon : Maybe IconSet.Icon
La chiamerei semplicemente `icon`.
```suggestion
    , icon : Maybe IconSet.Icon
```

2022-02-21 11:13 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Message.elm
> +    , text : List (Html msg)
Lo chiamerei `content`
```suggestion
    , content : List (Html msg)
```

2022-02-21 11:13 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Message.elm
> +withCustomIcon : IconSet.Icon -> Model msg -> Model msg
```suggestion
withIcon : IconSet.Icon -> Model msg -> Model msg
```

2022-02-21 11:13 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Message.elm
> +    , customIcon : Maybe IconSet.Icon
Attenzione però che se abbiamo un'icona di default, come mi pare di capire che sia, questa non dovrebbe essere rappresentata come `Maybe IconSet.Icon` bensì semplicemente possiamo fare a meno del `Maybe` utilizzando l'icona di default direttamente nella inizializzazione

2022-02-21 11:13 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Message.elm
> +create =
```suggestion
config : Config msg
config =
```

2022-02-21 11:13 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Message.elm
> +        , customIcon = Nothing
Qui mi aspetterei che ci fosse l'icona di default così da non dover gestire un `Maybe` nella funzione `render`.

2022-02-21 11:13 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Message.elm
> +    Model { configuration | type_ = type_ }
Sposterei tutte queste funzioni e tipi prima di `withClassList`, questo perchè `withClassList, withId & co`  sono dei _generics_ mentre `withType` è un particolare tipo di opzione dotata di un `type`

2022-02-21 11:13 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Message.elm
> +    Default Error
Possiamo far ricevere a `default` direttamente la `Variant`

```suggestion
defaultStyle : Variant -> Style
defaultStyle =
    Default
```

2022-02-21 11:13 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Message.elm
> +    WithBackgroundColor Error
```suggestion
backgroundStyle : Variant -> Style
backgroundStyle =
    WithBackgroundColor 
```

2022-02-21 11:13 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Message.elm
> +setRole : Style -> String
Questa non è una set

2022-02-21 11:13 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Message.elm
> +setDefaultIcon : Style -> IconSet.Icon
Idem

2022-02-21 11:13 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Message.elm
> +            CommonsAttributes.none
Queste due vanno messe vicino a `type Type msg` prima di `withType`

2022-02-21 14:38 UTC, lauratrapani commented on packages/pyxis-elm/src/Components/Message.elm
> +    Model { configuration | type_ = type_ }
Ho cambiato leggermente l'implementazione per rendere il message dismissible, in ogni caso ho riordinato il file.

2022-02-22 11:00 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Message.elm
> +    @docs coloredBackground
```suggestion
    ## Style
    
    @docs Style
    @docs defaultBackground
    @docs coloredBackground
```

2022-02-22 11:01 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Message.elm
> +    @docs Config
Occhio che questi tab non ci vogliono, altrimenti la docs non viene formattata per bene, te ne puoi accorgere dal fatto che gli _exposing_ non sono ordinati nello stesso modo in cui hai scritto i docs

2022-02-22 11:24 UTC, ascandone approved these changes
daje

2022-02-22 11:52 UTC, alessiosantangelo approved these changes

2022-02-22 11:52 UTC, merged