[DS-17]: [Pyxis Storybook] Documentation for Form Grid
primait/pyxis pull request #84
Opened 2022-02-22 17:23 UTC by emanuelemacri

Add form grid documentation

https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/DS-17

2022-02-23 16:50 UTC, alessiosantangelo requested changes
Molto figo il rendering della griglia!

2022-02-23 16:50 UTC, alessiosantangelo commented on packages/pyxis-react/src/stories/components/Form/Overview.tsx
> +        <strong>Default</strong> is used generally on all simple form item, like: text, textarea, select.
```suggestion
        <strong>Default gap</strong> is generally used on simple form items like text, textarea, select.
```

2022-02-23 16:50 UTC, alessiosantangelo commented on packages/pyxis-react/src/stories/components/Form/Overview.tsx
> +        <strong>Large</strong> is used generally on visual element, like: Legend, RadioCard, Message.
```suggestion
        <strong>Large gap</strong> is generally used on visual elements like legend, radio card, message.
```

2022-02-23 16:50 UTC, alessiosantangelo commented on packages/pyxis-react/src/stories/components/Form/Overview.tsx
> +        different spacings to the internal elements.
```suggestion
        You can create a sub-grid by putting a new grid inside the <code>Row</code. Doing so allows you to control how items span inside columns.
```

2022-02-23 16:50 UTC, alessiosantangelo commented on packages/pyxis-react/src/stories/components/Form/Overview.tsx
> +  </p>
```suggestion
  <p>
    A <code>legend</code> should always be used inside a <code>fieldset</code>.
    Check out the <span className="link" onClick={linkTo('components-form-🚧-all-stories--real-world-example')}>real world example</span>.
  </p>
```

2022-02-23 16:50 UTC, alessiosantangelo commented on packages/pyxis-react/src/stories/components/Form/Overview.tsx
> +    The Form Item is used to group: label, field, error/hint or other custom HTML.
```suggestion
    The Form Item is used to group labels, fields, errors, hints and any other custom Html you provide.
```

2022-02-23 16:50 UTC, alessiosantangelo commented on packages/pyxis-react/src/stories/components/Form/Overview.tsx
> +    Check out the <span className="link" onClick={linkTo('components-form-🚧-all-stories--real-world-example')}>real world example</span>.
```suggestion
  <p>
    A <code>legend</code> should always be used inside a <code>fieldset</code>.
    Check out the <span className="link" onClick={linkTo('components-form-🚧-all-stories--real-world-example')}>real world example</span>.
```

2022-02-23 16:50 UTC, alessiosantangelo commented on packages/pyxis-react/src/stories/components/Form/Overview.tsx
> +    'The Form Item is used to group: label, field, error/hint or other custom HTML.'
```suggestion
    'The Form Item is used to group labels, fields, errors, hints and any other custom Html you provide.'
```

2022-02-23 16:50 UTC, alessiosantangelo commented on packages/pyxis-react/src/stories/components/Form/Overview.tsx
> +    'The Form Row is used to define the width of grid and to group the columns inside.'
```suggestion
    'The Form Row is used to define the width of grid and to group the columns inside it.'
```

2022-02-23 17:15 UTC, lauratrapani requested changes

2022-02-23 17:15 UTC, lauratrapani commented on packages/pyxis-react/src/stories/components/Form/Item/Overview.tsx
> +    The Form item has a wrapper inside on which the spacing between the elements can be changed.
```suggestion
    Form item has a wrapper inside on which the spacing between the elements can be changed.
```

2022-02-23 17:15 UTC, lauratrapani commented on packages/pyxis-react/src/stories/components/Form/Legend/Overview.tsx
> +    <Canvas className="full-width">
Idem

2022-02-23 17:51 UTC, emanuelemacri commented on packages/pyxis-react/src/stories/components/Form/Item/Overview.tsx
> +    <Canvas className="full-width">
La storia l'ho messa per poter controllare l'html direttamente da lì, in ogni caso non faceva impazzire neanche me, ho lasciato la storia ma levato la tabella, mi sembra più pulito

2022-02-24 08:17 UTC, alessiosantangelo approved these changes

2022-02-24 09:17 UTC, lauratrapani approved these changes

2022-02-24 09:20 UTC, merged