[DS-52]: [Pyxis Elm] Implement the input checkbox
primait/pyxis pull request #87
Opened 2022-02-24 15:49 UTC by ascandone

https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/DS-52

2022-02-24 15:59 UTC, ascandone commented
Ho usato, per settare una proprietà del singolo checkbox, la nomenclatura
```elm
CheckboxGroup.option { value = Elixir, label = "Elixir" }
            |> CheckboxGroup.withDisabledOption True
```
non sono sicuro che sia proprio chiaro, se ci sono nomi meno peggio commentate

2022-02-24 17:06 UTC, alessiosantangelo requested changes
Due cavolate di numero, il resto mi sembra ottimo. Bravo!

2022-02-24 17:06 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Components/Field/CheckboxGroup.elm
> +config : Config value
In tutte le altre config ci siamo fatti passare l'id come obbligatorio, dovremmo farlo pure qui.

2022-02-24 17:06 UTC, alessiosantangelo commented on packages/pyxis-elm/src/Commons.elm
> +applyMaybe : (arg -> pipeValue -> pipeValue) -> Maybe arg -> pipeValue -> pipeValue
Questa funzione mi sembra poco utile, si può sostituire con un normalissimo `Maybe.map`, comunque sotto trovi il commento sull'id che la renderebbe obsoleta.

2022-02-25 08:25 UTC, ascandone commented on packages/pyxis-elm/src/Components/Field/CheckboxGroup.elm
> +config : Config value
Fatto; segnalo solo che adesso c'è, esposto pubblicamente

`single : String -> Config value`

che è diventato

`single : String -> String -> Config value`

che è probabilmente meno chiaro
(io mi sono già sbagliato e ho dovuto fare un secondo commit per ricorreggere gli esempi - però sto ancora dormendo quindi non so se vale)

per adesso direi che si può lasciare anche così, e vedere a posteriori, con le api complete, se c'è bisogno di usare records o basta accordarsi su convenzioni globali

2022-02-25 09:36 UTC, alessiosantangelo approved these changes

2022-02-25 09:36 UTC, merged