[DS-42]: [Pyxis Elm] Implement the FormGrid
primait/pyxis pull request #88
Opened 2022-02-24 16:50 UTC by emanuelemacri

Implement form grid in elm

https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/DS-42

2022-03-03 11:56 UTC, lauratrapani requested changes

2022-03-03 11:56 UTC, lauratrapani commented on packages/pyxis-elm/src/Stories/Chapters/FormGrid.elm
> +import Components.Form as Form
Questi abbiamo deciso di non metterli perché fuorvianti

2022-03-03 11:56 UTC, lauratrapani commented on packages/pyxis-elm/src/Stories/Chapters/FormGrid.elm
> +```
Forse spezzerei la doc in due in modo da documentare meglio i modificatori di fieldset e organizzare meglio il contenuto di grid.

2022-03-03 11:56 UTC, lauratrapani commented on packages/pyxis-elm/tests/Components/FormGridTest.elm
> +        , Test.describe "whit row"
```suggestion
        , Test.describe "with row"
```

2022-03-03 11:56 UTC, lauratrapani commented on packages/pyxis-elm/tests/Components/FormGridTest.elm
> +        , Test.describe "whit column"
```suggestion
        , Test.describe "with column"
```

2022-03-03 13:25 UTC, ascandone commented on packages/pyxis-elm/src/Examples/Form/View.elm
> +                    [ Column.oneSpan
Come mai alla fine hai fatto di nuovo annidato? A questo punto non era meglio la soluzione usando le tuple? es
```elm
Row.withColumns
  [ ( Column.oneSpan
   , "pw"
      ... |> Text.render ...
]

```

2022-03-03 15:08 UTC, ascandone commented on packages/pyxis-elm/src/Examples/Form/View.elm
> +                    [ Column.oneSpan
Si son d'accordo

2022-03-04 08:56 UTC, ascandone approved these changes

2022-03-04 13:58 UTC, merged