[DS-50]: [Pyxis Elm] Implement the ButtonRow component
primait/pyxis pull request #90
Opened 2022-02-28 09:28 UTC by Gsciarra

https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/DS-50

2022-03-01 11:44 UTC, lauratrapani approved these changes

2022-03-01 11:52 UTC, ascandone approved these changes
Metto approve, ma non vanno messe le stories? Anche giusto un esempio per capire visivamente di che si tratta? Magari nello stesso chapter di Button

2022-03-01 12:25 UTC, ascandone approved these changes

2022-03-02 09:27 UTC, emanuelemacri requested changes
Una modifica e una domanda

2022-03-02 09:27 UTC, emanuelemacri commented on packages/pyxis-react/src/stories/components/Form/Form.tsx
>              {/* Row with button group */}
```suggestion
            {/* Row with button row */}
```

2022-03-02 10:32 UTC, lauratrapani commented on packages/pyxis-elm/src/Components/ButtonRow.elm
> +        , classList = []
Non lo so, questo componente sembra monco anche a me così, però in realtà non possiamo pensare a _tutte_ le combinazioni possibili.

2022-03-02 10:43 UTC, Gsciarra commented on packages/pyxis-elm/src/Components/ButtonRow.elm
> +        , classList = []
Questo componente è un div con delle classi. Io cancellerei proprio il componente 😄

2022-03-02 10:44 UTC, lauratrapani commented on packages/pyxis-elm/src/Components/ButtonRow.elm
> +        , classList = []
Sono d'acccordo con @Gsciarra

2022-03-02 10:54 UTC, ascandone commented on packages/pyxis-elm/src/Components/ButtonRow.elm
> +        , classList = []
Io in questi casi uso delle cose tipo
```ts
<div className={ buttonGroupClass({ centered: true }) }> .... </div>
```
quando so che si tratta veramente solo di delle classi in un componente senza struttura complessa dentro

Però sarebbe un po' inconsistente dal resto, quindi non credo sia il caso


(in questo caso potrebbe essere `div [ ButtonGroup.class ButtonGroup.centered ] []` o cose così)

2022-03-09 16:31 UTC, closed without merging