Add contributing section on Pyxis
primait/pyxis pull request #98
Opened 2022-03-07 11:14 UTC by alessiosantangelo

Adds a _Contributing_ section which can help in addressing issues.

2022-03-07 15:49 UTC, lauratrapani commented on README.md
> +Keep in mind that Pyxis belongs to anyone in Prima, so is your responsibility to open the issue and collaborate with the Pyxis team in order to solve the problem. Opening an issue and then forgot abo
```suggestion
Keep in mind that Pyxis belongs to anyone in Prima, so it is your responsibility to open the issue and collaborate with the Pyxis team in order to solve the problem. Opening an issue and then forgetting about that is not the way things should be done.
```

2022-03-07 15:57 UTC, emanuelemacri requested changes
Un paio di cosine.
Più che altro, molti creano un file: `CONTRIBUTING.md` e in questa sezione del `README` si fa solo riferimento a quel file.

Per iniziare comunque questa lista di cose vanno bene, poi lo possiamo estendere come in questi esempi:

- https://github.com/uber/baseweb
- https://github.com/adobe/react-spectrum
- https://github.com/ant-design/ant-design/
- https://github.com/aws-amplify/amplify-ui/
- https://github.com/at-ui/at-ui

2022-03-07 15:57 UTC, emanuelemacri commented on README.md
> +Pyxis is still in development (and hopefully will always be!) and often you'll find yourself stuck in creating something is currently not allowed to be done via Pyxis' apis.
```suggestion
Pyxis is still in development (and hopefully will always be!) and often you'll find yourself stuck in creating something is currently not allowed to be done via Pyxis'APIs.
```

2022-03-07 15:57 UTC, emanuelemacri commented on README.md
> +Not only the mockup should _have been validated by designers_ but also needs to be created _by only using foundations, components and \_design tokens_ which are the basic bricks for building everythi
```suggestion
Not only the mockup should _have been validated by designers_ but also needs to be created _by only using foundations, components and design tokens_ which are the basic bricks for building everything with Pyxis.
```

2022-03-07 15:57 UTC, emanuelemacri commented on README.md
> +## Contributing
```suggestion
## 💜 Contributing
```

2022-03-07 15:57 UTC, emanuelemacri commented on README.md
> +4. _[optional]_ **a suggestion** of how the issue's solution should be addressed. This will be the basic of the discussion. Keep in mind that this kind of solution should follow our code guidelines a
Magari possiamo specificare che si può anche proporre una PR?

2022-03-08 09:41 UTC, alessiosantangelo commented on README.md
> +4. _[optional]_ **a suggestion** of how the issue's solution should be addressed. This will be the basic of the discussion. Keep in mind that this kind of solution should follow our code guidelines a
Vorrei fare usare solo le issues per non ritrovarci PR aperte da altri di cui non sappiamo esattamente il motivo. Passando invece dalla issue dovrebbe essere possibile al team Pyxis l'indirizzare la soluzione prima di ricevere una PR da mergiare.

2022-03-08 09:57 UTC, merged